import type { Framework } from "@regunav/types";

/**
 * APPI — Act on the Protection of Personal Information (個人情報の保護
 * に関する法律). Japan's general personal-information statute. Act No.
 * 57 of 2003, amended substantively in 2015 (effective 30 May 2017),
 * 2020 (effective 1 April 2022) and 2021 (effective 1 April 2023 for
 * the public-sector merger). The 2022 amendments introduced mandatory
 * breach notification, the pseudonymously-processed-information (仮名加工
 * 情報) regime, the personal-related-information (個人関連情報) third-party-
 * provision restriction, enhanced cross-border-transfer disclosure, and
 * the extraterritorial-enforcement basis.
 *
 * Regulator: Personal Information Protection Commission (個人情報保護
 * 委員会 / PPC) — https://www.ppc.go.jp/en/
 *
 * Sources:
 *   - PPC English legal portal:  https://www.ppc.go.jp/en/legal/
 *   - PPC enforcement rules + guidelines:
 *     https://www.ppc.go.jp/en/legal/guidelines/
 *
 * Article numbering follows the consolidated APPI in force from
 * 1 April 2022. Clauses, controls and questions cite the published Act
 * by Article — they are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const APPI_JAPAN: Framework = {
  schemaVersion: 1,
  code: "APPI_JAPAN",
  name: "Japan APPI",
  version: "2003 (Act No. 57); amended 2020 (effective 2022) + 2021",
  description:
    "Japan's general statute on the protection of personal information. Establishes the obligations of Personal-Information-Handling Business Operators (PIHBO / 個人情報取扱事業者), the special category of 'special-care-required personal information' (要配慮個人情報), the pseudonymously-processed (仮名加工情報) and anonymously-processed (匿名加工情報) regimes, the personal-related-information (個人関連情報) third-party-provision restriction, mandatory leakage reporting + individual notification, the rights of individuals (disclosure / correction / suspension of use / suspension of provision / disclosure-method choice), cross-border-transfer restrictions, and the PPC's enforcement powers. The 2022 amendments extended extraterritorial application and added administrative-fine exposure up to JPY 100 million for legal persons (Art. 179).",
  jurisdiction: ["JP"],
  referenceUrl: "https://www.ppc.go.jp/en/legal/",

  // ─── Clauses (17 of the most-cited Articles) ─────────────────────────────
  clauses: [
    { clauseRef: "Art. 2",         title: "Definitions — personal information, retained personal data, special-care, pseudonymous, anonymous", description: "Defines: personal information (information about a living individual identifying them, including by combination, and individual-identification codes); retained personal data (personal data the PIHBO has authority to disclose/correct/suspend); special-care-required personal information (race, creed, social status, medical history, criminal record, victim-of-crime status and similar facts requiring particular care); pseudonymously-processed information (information that cannot identify a specific individual without other information); anonymously-processed information (information that cannot identify a specific individual and that cannot be restored).", mandatory: true },
    { clauseRef: "Art. 17",        title: "Specification of utilisation purpose",                            description: "A PIHBO shall, when handling personal information, specify the purpose of utilisation as explicitly as possible. The PIHBO shall not change the utilisation purpose beyond the scope reasonably recognised as having relevance to the originally specified purpose.", mandatory: true },
    { clauseRef: "Art. 18",        title: "Restriction by utilisation purpose",                              description: "A PIHBO shall not handle personal information beyond the scope necessary to achieve the utilisation purpose specified under Art. 17, without obtaining the prior consent of the individual, except where based on laws and regulations, urgent need to protect life/body/property, particularly necessary to improve public health or promote sound nurture of children, or cooperation with State organs, etc.", mandatory: true },
    { clauseRef: "Art. 19",        title: "Inappropriate use prohibition",                                    description: "A PIHBO shall not handle personal information by means that may foster or induce illegal or improper acts.", mandatory: true },
    { clauseRef: "Art. 20",        title: "Proper acquisition + special-care-required PI consent",            description: "A PIHBO shall not acquire personal information by deception or other improper means. A PIHBO shall not acquire special-care-required personal information (Art. 2(3)) without the prior consent of the individual, except for the limited cases prescribed by the Act (laws and regulations, life/body/property urgency, public health, sound-nurture of children, cooperation with State organs, public disclosure by the individual or by State organ / academic-research / press, etc.).", mandatory: true },
    { clauseRef: "Art. 21",        title: "Notice or public announcement of utilisation purpose",             description: "A PIHBO shall, when acquiring personal information, promptly notify the individual of the utilisation purpose or publicly announce it (e.g., on the PIHBO's website). For information acquired directly in writing from the individual, the utilisation purpose shall be expressly indicated in advance — except for the prescribed exemptions (urgency, harm to the individual, harm to the PIHBO's rights, cooperation with State organs, etc.).", mandatory: true },
    { clauseRef: "Art. 23",        title: "Security control measures",                                        description: "A PIHBO shall take necessary and appropriate measures to prevent the leakage, loss or damage of personal data, and otherwise for security control of personal data. The PPC Guidelines elaborate the four pillars: organisational security (responsibilities, rules, audit), human security (training, NDA), physical security (premises, devices), and technical security (access control, encryption, monitoring, transfer protection).", mandatory: true },
    { clauseRef: "Art. 24-25",     title: "Supervision of employees + entrusted parties",                    description: "Art. 24: A PIHBO shall exercise necessary and appropriate supervision over its employees handling personal data. Art. 25: Where handling of personal data is entrusted (e.g., to a processor or cloud provider) in whole or in part, the PIHBO shall exercise necessary and appropriate supervision over the entrustee to ensure security control of personal data.", mandatory: true },
    { clauseRef: "Art. 26",        title: "Reporting + notification of leakage etc.",                         description: "A PIHBO shall, where a leakage, loss, damage or other situation prescribed by the Rules of the PPC occurs in respect of personal data, report the matter to the PPC AND notify the affected individuals (or publicly announce when notification to individuals is difficult and alternative measures are taken). The Rules specify the reportable categories: leakage involving special-care-required PI; leakage that may cause property damage by improper use; leakage by intentional wrongdoing; leakage involving more than 1,000 individuals. A preliminary report within 3-5 days and a final report within 30 days (60 days for intentional wrongdoing) are required.", mandatory: true },
    { clauseRef: "Art. 27",        title: "Restriction on provision of personal data to a third party",       description: "A PIHBO shall not provide personal data to a third party without the prior consent of the individual, except for: (i) provision based on laws and regulations; (ii) urgent need to protect life/body/property; (iii) particularly necessary to improve public health or promote sound nurture of children; (iv) cooperation with State organs; (v) academic-research exemptions; and (vi) the opt-out provision regime under Art. 27(2) (subject to advance PPC notification + public announcement — and excluded for special-care-required PI, illegally-acquired PI and personal-related-information-derived PI). Joint-use, entrustment, and business-succession scenarios are not 'third-party provision' (Art. 27(5)).", mandatory: true },
    { clauseRef: "Art. 28",        title: "Provision to a third party in a foreign country",                  description: "A PIHBO shall, when providing personal data to a third party in a foreign country (other than a country recognised by PPC Rules as having a personal-information-protection system equivalent to Japan's — currently the EEA and the UK — and other than a recipient with continuous-equivalent-protection measures under PPC Rules), obtain prior consent of the individual to the foreign-transfer AND provide the individual in advance with information on (i) the name of the country, (ii) the personal-information-protection system of that country and (iii) the measures taken by the recipient. Where the recipient has continuous-equivalent-protection measures, the PIHBO shall take measures necessary to ensure their continued implementation and respond to inquiries from the individual.", mandatory: true },
    { clauseRef: "Art. 29-30",     title: "Recording obligation on provider + recipient of third-party provision", description: "Art. 29: A PIHBO providing personal data to a third party shall record the date, the recipient, and the items provided. Art. 30: A PIHBO receiving personal data from a third party shall confirm the recipient's identity and the circumstances of acquisition, and record the same. Records retained for 1-3 years per Rule.", mandatory: true },
    { clauseRef: "Art. 31",        title: "Personal-related information — third-party provision",            description: "Where a PIHBO provides personal-related information (information that is not 'personal information' to the PIHBO — e.g., cookie identifiers, terminal identifiers, browsing history — but that the recipient is expected to acquire as personal data when combined with its own data) to a third party, the PIHBO shall confirm that the recipient has obtained the individual's consent to receive it as personal data, and shall record the confirmation. The foreign-transfer-disclosure rules of Art. 28 apply.", mandatory: true },
    { clauseRef: "Art. 32-39",     title: "Rights of individuals — disclosure, correction, suspension",       description: "Individuals have the right to request, in relation to retained personal data: (Art. 32) disclosure of the utilisation purpose; (Art. 33) disclosure of the retained data itself — including electromagnetic-record disclosure at the individual's choice; (Art. 34) correction, addition or deletion where the data is not correct; (Art. 35) suspension of utilisation or deletion where the data is handled in violation of Art. 18 / 19 / 20 / 27 / 28, OR where the PIHBO no longer needs the data, OR where a leakage situation under Art. 26 has occurred, OR where the handling may infringe the rights or legitimate interests of the individual; (Art. 36) cessation of third-party provision; (Art. 37) procedures for receiving requests; (Art. 38) charges for disclosure (within a reasonable range); (Art. 39) preceding-pursuit court-action requirement.", mandatory: true },
    { clauseRef: "Art. 41-42",     title: "Pseudonymously-processed information regime",                      description: "Personal information processed in accordance with PPC-Rule-specified standards such that the individual cannot be identified unless combined with other information. PIHBOs handling pseudonymously-processed information are: relieved from Art. 17(2) purpose-change restriction, Art. 26 reporting/notification, and Art. 32-39 rights — provided the deletion-information + processing-method are not disclosed, the data is not used to identify the individual, and the data is not provided to third parties (except for entrustment / joint-use). Art. 42 governs anonymously-processed information (匿名加工情報): publicly disclose categories + provision method; do not collate with other information to re-identify.", mandatory: false },
    { clauseRef: "Art. 171",       title: "Extraterritorial application + enforcement",                       description: "The PPC's reporting + on-site-inspection + recommendation + order powers (Art. 143-148) apply to a PIHBO in a foreign country that handles personal information of an individual in Japan acquired in connection with providing goods or services to that individual. The PPC may share information with foreign authorities to facilitate enforcement (Art. 172).", mandatory: true },
    { clauseRef: "Art. 178-179",   title: "Penalties + administrative fines",                                  description: "Penalties include: failure to comply with a PPC order (Art. 178) — up to 1 year imprisonment OR a fine up to JPY 1 million for the responsible person; provision or theft of a personal-information database for unjust purposes (Art. 179) — up to 1 year imprisonment OR a fine up to JPY 500,000. Doubled-liability for legal persons: up to JPY 100 million for failure to comply with a PPC order or for unjust provision of a personal-information database (Art. 184). False reports / non-cooperation with PPC inspection: fines up to JPY 500,000.", mandatory: true },
  ],

  // ─── Controls (12 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "APPI-PURP-001",    title: "Utilisation-purpose specification + restriction (Art. 17-18)",       description: "Every processing activity has an explicit utilisation purpose recorded; handling outside that purpose requires either an Art. 18(3) exemption OR fresh consent; purpose-change limited to scope reasonably related to the original.",                                                                                                                              category: "data-protection",      evidenceTypes: ["policy","procedure","attestation","configuration"],     clauseRefs: ["Art. 17","Art. 18"],                  riskLevel: "high"   },
    { controlRef: "APPI-ACQ-001",     title: "Proper acquisition + special-care consent (Art. 19-20)",              description: "No deceptive or improper acquisition; explicit prior consent captured before acquiring special-care-required PI (race, creed, social status, medical, criminal record, victim status, etc.); exemption analysis recorded where consent is not relied upon.",                                                                                                                category: "data-protection",      evidenceTypes: ["procedure","log","attestation","screenshot"],           clauseRefs: ["Art. 19","Art. 20"],                  riskLevel: "high"   },
    { controlRef: "APPI-NOTICE-001",  title: "Utilisation-purpose notice / announcement (Art. 21)",                 description: "Notice or public announcement of the utilisation purpose for all acquired personal information; in-writing acquisitions display the purpose in advance; updates on purpose-change.",                                                                                                                                                                            category: "data-protection",      evidenceTypes: ["policy","screenshot","report"],                         clauseRefs: ["Art. 21"],                            riskLevel: "high"   },
    { controlRef: "APPI-SEC-001",     title: "Four-pillar security control measures (Art. 23)",                     description: "Organisational (responsibility assignment, rules, audit), human (training, NDA), physical (premises, devices, media), and technical (access control, encryption-at-rest + in-transit, log monitoring) security control measures aligned with the PPC Guidelines; periodic review.",                                                                              category: "data-protection",      evidenceTypes: ["policy","procedure","configuration","attestation"],     clauseRefs: ["Art. 23"],                            riskLevel: "high"   },
    { controlRef: "APPI-SUPER-001",   title: "Supervision of employees + entrusted parties (Art. 24-25)",           description: "Documented supervision of employees handling personal data (training, monitoring, sanctions); written-contract + due-diligence + audit-right + breach-reporting obligation for every entrusted party (sub-processor cascade addressed).",                                                                                                                          category: "data-protection",      evidenceTypes: ["policy","procedure","contract","training_record"],      clauseRefs: ["Art. 24-25"],                  riskLevel: "high"   },
    { controlRef: "APPI-BREACH-001",  title: "Leakage reporting + individual notification (Art. 26)",                description: "Documented procedure to assess every leakage / loss / damage event against the four PPC reportable categories (special-care PI; property-damage risk; intentional wrongdoing; >1,000 individuals). Preliminary report to the PPC within 3-5 days, final report within 30 days (60 for intentional wrongdoing); individual notification or substitute public announcement.", category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"],   clauseRefs: ["Art. 26"],                            riskLevel: "high"   },
    { controlRef: "APPI-3RD-001",     title: "Third-party provision + opt-out regime (Art. 27)",                     description: "Default rule: no third-party provision without prior consent. Where the opt-out regime is used, prior PPC notification + public announcement of the prescribed items; opt-out excluded for special-care PI, illegally-acquired PI and personal-related-information-derived PI. Joint-use / entrustment / business-succession exemption flows documented separately.",      category: "data-protection",      evidenceTypes: ["policy","procedure","contract","configuration"],        clauseRefs: ["Art. 27"],                            riskLevel: "high"   },
    { controlRef: "APPI-XBORDER-001", title: "Foreign-country transfer + enhanced disclosure (Art. 28)",             description: "For every foreign-country provision, classify the destination: (i) PPC-recognised equivalent country (EEA / UK) — no extra consent; (ii) recipient with continuous-equivalent-protection measures — ongoing supervision + inquiry-response; (iii) other countries — prior consent + advance disclosure of country name + protection system + recipient measures.",      category: "data-protection",      evidenceTypes: ["contract","procedure","screenshot","attestation"],     clauseRefs: ["Art. 28"],                            riskLevel: "high"   },
    { controlRef: "APPI-REC-001",     title: "Provider + recipient recording (Art. 29-30) + personal-related info confirmation (Art. 31)", description: "Records of every third-party provision (date, recipient, items) on the provider side; records of recipient identity + acquisition circumstances on the recipient side; retention for the PPC-Rule-specified period (1-3 years). For personal-related-information transfers, confirm + record that the recipient has obtained the individual's consent to receive as personal data.", category: "data-protection",      evidenceTypes: ["log","procedure","report","configuration"],             clauseRefs: ["Art. 29-30","Art. 31"],        riskLevel: "high"   },
    { controlRef: "APPI-RIGHTS-001",  title: "Individual-rights workflow (Art. 32-39)",                              description: "Documented intake + identity-verification + fulfilment workflow for disclosure (with electromagnetic-record-format choice), correction, suspension of utilisation, suspension of third-party provision, and utilisation-purpose disclosure; reasonable charges; reasons given on refusal; preceding-pursuit-letter step for litigation.",                                  category: "data-protection",      evidenceTypes: ["procedure","log","report","screenshot"],                clauseRefs: ["Art. 32-39"], riskLevel: "high"   },
    { controlRef: "APPI-PSEUDO-001",  title: "Pseudonymous + anonymous information regimes (Art. 41-42)",            description: "Where pseudonymously-processed information is used, the PPC-Rule processing standard is applied; deletion-info + processing-method protected; no third-party provision (except entrustment / joint-use); no re-identification attempts. Where anonymously-processed information is used, categories + provision method publicly disclosed; collation prohibited.",   category: "data-protection",      evidenceTypes: ["procedure","report","configuration","attestation"],     clauseRefs: ["Art. 41-42"],                  riskLevel: "limited"},
    { controlRef: "APPI-ENF-001",     title: "PPC-enforcement + penalty exposure (Art. 171, 178-179, 184)",          description: "Risk register reflects: extraterritorial PPC reporting + inspection + recommendation + order powers; criminal-liability schedule (up to 1 year + JPY 1m responsible-person / JPY 100m legal-person for PPC-order violation; up to JPY 500k / 1 year for unjust database provision); cross-border PPC enforcement-cooperation.",                                          category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                        clauseRefs: ["Art. 171","Art. 178-179"],     riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "APPI-Q-001", text: "Has the utilisation purpose (利用目的) been specified as explicitly as possible for every processing activity, with the change-of-purpose constraint observed (Art. 17)?",                                                                                                                                                category: "purpose",        riskWeight: 1.0, clauseRefs: ["Art. 17"] },
    { questionRef: "APPI-Q-002", text: "Is the handling of personal information limited to the scope necessary to achieve the specified purpose, with an Art. 18(3) exemption analysis or fresh consent recorded for any deviation?",                                                                                                                            category: "purpose",        riskWeight: 1.0, clauseRefs: ["Art. 18"] },
    { questionRef: "APPI-Q-003", text: "Has special-care-required personal information (要配慮個人情報 — race / creed / social status / medical / criminal / victim status etc.) been acquired only with prior consent or under an Art. 20(2) exemption?",                                                                                                       category: "special-care",   riskWeight: 1.0, clauseRefs: ["Art. 20"] },
    { questionRef: "APPI-Q-004", text: "Is the utilisation purpose notified to the individual or publicly announced under Art. 21, with the in-writing-acquisition advance-indication requirement met?",                                                                                                                                                          category: "notice",         riskWeight: 0.9, clauseRefs: ["Art. 21"] },
    { questionRef: "APPI-Q-005", text: "Are the four pillars of security control measures (organisational / human / physical / technical) implemented in line with the PPC Guidelines (Art. 23)?",                                                                                                                                                                category: "security",       riskWeight: 1.0, clauseRefs: ["Art. 23"] },
    { questionRef: "APPI-Q-006", text: "Is necessary and appropriate supervision exercised over employees handling personal data AND every entrusted party (Art. 24-25), with written contracts + due diligence + audit rights?",                                                                                                                                category: "supervision",    riskWeight: 0.9, clauseRefs: ["Art. 24-25"] },
    { questionRef: "APPI-Q-007", text: "Can a leakage / loss / damage event be assessed against the four PPC reportable categories and reported within 3-5 days (preliminary) / 30 days (final, 60 for intentional) under Art. 26?",                                                                                                                              category: "breach",         riskWeight: 1.0, clauseRefs: ["Art. 26"] },
    { questionRef: "APPI-Q-008", text: "For third-party provision (Art. 27), is prior consent obtained or an opt-out regime properly notified to the PPC + publicly announced, with the special-care / illegally-acquired / personal-related exclusions respected?",                                                                                              category: "third-party",    riskWeight: 1.0, clauseRefs: ["Art. 27"] },
    { questionRef: "APPI-Q-009", text: "For foreign-country provision (Art. 28), is the destination classified as PPC-equivalent (EEA/UK) / continuous-equivalent-protection / other-country, with the consent + advance-disclosure obligations met as applicable?",                                                                                              category: "transfers",      riskWeight: 1.0, clauseRefs: ["Art. 28"] },
    { questionRef: "APPI-Q-010", text: "Are provider records (Art. 29) + recipient records (Art. 30) + personal-related-information confirmation records (Art. 31) maintained for the PPC-Rule retention period?",                                                                                                                                                category: "records",        riskWeight: 0.8, clauseRefs: ["Art. 29-30","Art. 31"] },
    { questionRef: "APPI-Q-011", text: "Can the rights of disclosure / correction / suspension of utilisation / suspension of third-party provision (Art. 32-36) be fulfilled, including electromagnetic-record disclosure choice + reasonable charges + reasons on refusal?",                                                                                  category: "rights",         riskWeight: 1.0, clauseRefs: ["Art. 32-39"] },
    { questionRef: "APPI-Q-012", text: "Where pseudonymously-processed information (Art. 41) is used, is the PPC-Rule processing standard applied + deletion information protected + re-identification prohibited + third-party-provision restriction observed?",                                                                                                category: "pseudonymous",   riskWeight: 0.7, clauseRefs: ["Art. 41-42"] },
    { questionRef: "APPI-Q-013", text: "Where anonymously-processed information (Art. 42) is provided, are the categories + provision method publicly disclosed and collation-prohibited?",                                                                                                                                                                       category: "anonymous",      riskWeight: 0.6, clauseRefs: ["Art. 41-42"] },
    { questionRef: "APPI-Q-014", text: "Where the entity handles personal information of an individual in Japan acquired in connection with providing goods or services to that individual (Art. 171), is the extraterritorial PPC reporting + inspection + order exposure reflected in the risk register?",                                                    category: "extraterritorial", riskWeight: 0.8, clauseRefs: ["Art. 171"] },
    { questionRef: "APPI-Q-015", text: "Is the penalty exposure (up to JPY 100m legal-person for PPC-order violation under Art. 184; up to 1 year + JPY 1m responsible-person under Art. 178; up to JPY 500k / 1 year for unjust database provision under Art. 179) reflected in the risk register?",                                                            category: "penalties",      riskWeight: 0.6, clauseRefs: ["Art. 178-179"] },
  ],
};
