import type { Framework } from "@regunav/types";

/**
 * CCPA / CPRA — California Consumer Privacy Act (2018) as amended by the
 * California Privacy Rights Act of 2020 (CPRA), codified at Cal. Civ.
 * Code §§ 1798.100-1798.199.100. The CPRA introduced the right to
 * correct, the right to limit use of sensitive personal information, the
 * "sharing" concept for cross-context behavioural advertising, and the
 * California Privacy Protection Agency (CPPA) as the dedicated enforcer.
 *
 * Sources:
 *   - Cal. Civ. Code Title 1.81.5 (CCPA/CPRA):
 *     https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CIV&division=3.&title=1.81.5.
 *   - California Attorney General CCPA pages:
 *     https://oag.ca.gov/privacy/ccpa
 *   - CPPA rule-making page:
 *     https://cppa.ca.gov/regulations/
 *
 * Clauses, controls and questions below cite the California Civil Code
 * by section. They are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const CCPA: Framework = {
  schemaVersion: 1,
  code: "CCPA",
  name: "CCPA / CPRA",
  version: "2024",
  description:
    "California state privacy law applying to for-profit businesses doing business in California that (a) had annual gross revenues over $25 million in the preceding year, (b) annually buy/sell/share the personal information of 100,000+ California consumers or households, or (c) derive 50%+ of annual revenue from selling/sharing California consumers' personal information. Establishes seven consumer rights, three opt-out mechanisms (sale, sharing, sensitive PI), a notice + transparency regime, business-purpose service-provider + contractor + third-party distinctions, and a private right of action for certain data breaches. Enforced by the California Privacy Protection Agency (CPPA) + the California Attorney General.",
  jurisdiction: ["US-CA"],
  referenceUrl: "https://oag.ca.gov/privacy/ccpa",

  // ─── Clauses (17 — CCPA/CPRA sections) ──────────────────────────────────
  clauses: [
    { clauseRef: "§1798.100",          title: "Right to know about personal information collected (general)",                description: "A consumer shall have the right to request that a business that collects a consumer's personal information disclose to that consumer the categories and specific pieces of personal information the business has collected, sold or shared about that consumer. The business shall provide the information in a portable and, to the extent technically feasible, readily useable format. The business shall not retain personal information for longer than is reasonably necessary for the disclosed purpose.", mandatory: true },
    { clauseRef: "§1798.105",          title: "Right to delete personal information",                                        description: "A consumer shall have the right to request that a business delete any personal information about the consumer which the business has collected from the consumer. Business shall direct any service providers, contractors or third parties to delete the consumer's personal information from their records and notify all third parties to whom the business has sold or shared the consumer's personal information to delete the consumer's personal information.", mandatory: true },
    { clauseRef: "§1798.106",          title: "Right to correct inaccurate personal information",                            description: "A consumer shall have the right to request a business that maintains inaccurate personal information about the consumer to correct that inaccurate personal information, taking into account the nature of the personal information and the purposes of the processing.", mandatory: true },
    { clauseRef: "§1798.110",          title: "Right to know — categories + specific pieces collected",                      description: "A consumer shall have the right to request that a business that collects personal information about the consumer disclose: the categories of personal information collected; the categories of sources; the business or commercial purpose for collecting/selling/sharing; the categories of third parties with whom the business shares; the specific pieces of personal information collected.", mandatory: true },
    { clauseRef: "§1798.115",          title: "Right to know — sale + sharing disclosures",                                   description: "A consumer shall have the right to request that a business that sells or shares the consumer's personal information, or that discloses it for a business purpose, disclose to the consumer: the categories of personal information sold/shared/disclosed; the categories of third parties to whom each category was sold/shared/disclosed.", mandatory: true },
    { clauseRef: "§1798.120",          title: "Right to opt-out of sale or sharing",                                          description: "A consumer shall have the right, at any time, to direct a business that sells or shares personal information about the consumer to third parties not to sell or share the consumer's personal information. This right is referred to as the 'right to opt-out of sale or sharing'. Businesses shall honour an opt-out preference signal (Global Privacy Control / GPC).", mandatory: true },
    { clauseRef: "§1798.121",          title: "Right to limit use + disclosure of sensitive personal information",           description: "A consumer shall have the right, at any time, to direct a business that collects sensitive personal information about the consumer to limit its use of the consumer's sensitive personal information to that use which is necessary to perform the services or provide the goods reasonably expected by an average consumer who requests such goods or services.", mandatory: true },
    { clauseRef: "§1798.125",          title: "Right to non-discrimination for exercising rights",                            description: "A business shall not discriminate against a consumer because the consumer exercised any of the rights conferred by this title — including by denying goods/services, charging different prices, providing a different level of quality, or suggesting that the consumer will receive a different price/quality. Permits financial-incentive programmes that are reasonably related to the value provided to the business by the consumer's data.", mandatory: true },
    { clauseRef: "§1798.130",          title: "Notice + disclosure requirements",                                              description: "A business shall, in a form that is reasonably accessible to consumers: provide two or more designated methods for submitting requests for information; disclose + deliver the required information to a consumer free of charge, correct inaccurate personal information, or delete a consumer's personal information within 45 days of receiving the request (with a one-time 45-day extension allowed when reasonably necessary). Update privacy policy at least once every 12 months.", mandatory: true },
    { clauseRef: "§1798.135",          title: "Methods — 'Do Not Sell or Share' + 'Limit the Use of My Sensitive PI'",        description: "Where a business sells or shares consumers' personal information, the business shall provide a clear and conspicuous link on the business's internet homepages, titled 'Do Not Sell or Share My Personal Information'. Where a business uses or discloses sensitive personal information for purposes other than those set forth in §1798.121(a), the business shall provide a clear and conspicuous link, titled 'Limit the Use of My Sensitive Personal Information'.", mandatory: true },
    { clauseRef: "§1798.140",          title: "Definitions",                                                                   description: "Defines 'personal information', 'sensitive personal information', 'business', 'service provider', 'contractor', 'third party', 'sell', 'share' (for cross-context behavioural advertising), 'business purpose', 'commercial purpose', 'consumer', 'cross-context behavioural advertising', 'deidentified', 'aggregate consumer information', 'verifiable consumer request', 'minor'.", mandatory: true },
    { clauseRef: "§1798.140(ag)",      title: "Service provider + contractor contractual requirements",                       description: "A service provider or contractor is any entity that processes personal information on behalf of a business pursuant to a written contract that prohibits the entity from selling/sharing the personal information; retaining/using/disclosing the personal information for any purpose other than for the business purposes specified; retaining/using/disclosing the information outside of the direct business relationship; combining the personal information with personal information from other sources.", mandatory: true },
    { clauseRef: "§1798.145",          title: "Exemptions + interactions with other laws",                                    description: "Sets out exemptions including: medical information governed by CMIA; protected health information collected by a covered entity or business associate subject to HIPAA; personal information collected, processed, sold or disclosed pursuant to specific federal laws (GLBA, FCRA, Driver's Privacy Protection Act); personal information collected by a business about a natural person in the course of the person acting as an employee, owner, director, officer, medical staff, contractor or agent.", mandatory: true },
    { clauseRef: "§1798.150",          title: "Private right of action for certain data breaches",                            description: "A consumer whose nonencrypted and nonredacted personal information (as defined in §1798.81.5) is subject to an unauthorised access and exfiltration, theft or disclosure as a result of the business's violation of the duty to implement and maintain reasonable security procedures and practices appropriate to the nature of the information may institute a civil action for statutory damages in an amount not less than $100 and not greater than $750 per consumer per incident or actual damages, whichever is greater, plus injunctive relief.", mandatory: true },
    { clauseRef: "§1798.155",          title: "Civil penalties (AG + CPPA enforcement)",                                       description: "Any business, service provider, contractor, or other person that violates this title shall be subject to an injunction and liable for an administrative fine of not more than $2,500 for each violation or $7,500 for each intentional violation and violations involving the personal information of consumers known to be less than 16 years of age, which shall be assessed and recovered in a civil action brought in the name of the people of the State of California by the Attorney General or in an administrative enforcement action by the California Privacy Protection Agency.", mandatory: true },
    { clauseRef: "§1798.185",          title: "CPPA rulemaking + automated decision-making + risk assessments + cybersecurity audits", description: "The CPPA shall adopt regulations governing access + opt-out rights for businesses' use of automated decision-making technology (ADMT), mandatory annual cybersecurity audits for businesses whose processing presents significant risk to consumer privacy/security, and risk assessments for processing that presents significant risk to consumer privacy/security. Final CPPA regulations on ADMT, risk assessments + cybersecurity audits are expected to be effective in 2025-2026.", mandatory: true },
    { clauseRef: "§1798.199",          title: "California Privacy Protection Agency (CPPA)",                                   description: "Establishes the California Privacy Protection Agency, an independent state agency, with full administrative power to implement and enforce the title. Includes a five-member board, rule-making authority, investigative and audit powers, and the authority to issue administrative fines.", mandatory: true },
  ],

  // ─── Controls (13 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "CCPA-NOTICE-001",     title: "Notice at Collection + privacy-policy refresh",                description: "Notice at collection delivered at or before the point of collection covering categories of PI/SPI collected, purposes, retention period, whether PI is sold or shared, consumer rights. Privacy policy refreshed at least every 12 months. Maps §1798.100 + §1798.130.",                                                                                                                                                category: "data-protection",      evidenceTypes: ["screenshot","policy","report"],                          clauseRefs: ["§1798.100","§1798.130"],            riskLevel: "high"   },
    { controlRef: "CCPA-RIGHTS-001",     title: "Consumer-rights intake + 45-day fulfilment workflow",            description: "Documented intake + identity-verification + fulfilment workflow for the right to know (§1798.100/§1798.110/§1798.115), right to delete (§1798.105), right to correct (§1798.106), with a 45-day SLA + one 45-day extension. Communicates downstream-deletion requests to service providers/contractors/third parties.",                                                                                                  category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],               clauseRefs: ["§1798.100","§1798.105","§1798.106","§1798.110","§1798.115"], riskLevel: "high"   },
    { controlRef: "CCPA-OPT-001",        title: "Opt-out of sale/sharing + GPC honouring",                        description: "Clear and conspicuous 'Do Not Sell or Share My Personal Information' link on every homepage; honour Global Privacy Control (GPC) browser/device signal; downstream notification to recipients; record of opt-outs retained.",                                                                                                                                                                                          category: "data-protection",      evidenceTypes: ["screenshot","configuration","log","report"],            clauseRefs: ["§1798.120","§1798.135"],             riskLevel: "high"   },
    { controlRef: "CCPA-SPI-001",        title: "Limit-Use-of-Sensitive-PI mechanism",                              description: "Clear and conspicuous 'Limit the Use of My Sensitive Personal Information' link on every homepage where SPI is processed beyond reasonably-expected purposes; honour the consumer's preference; record retained.",                                                                                                                                                                                                  category: "data-protection",      evidenceTypes: ["screenshot","configuration","log","report"],            clauseRefs: ["§1798.121","§1798.135"],             riskLevel: "high"   },
    { controlRef: "CCPA-NONDISC-001",    title: "Non-discrimination + financial-incentive governance",             description: "Operational controls that prevent discriminatory treatment of consumers who exercise CCPA rights; documented basis (reasonably related to the value provided to the business by the consumer's data) for any financial-incentive programme.",                                                                                                                                                                            category: "data-protection",      evidenceTypes: ["policy","procedure","report","attestation"],            clauseRefs: ["§1798.125"],                          riskLevel: "limited" },
    { controlRef: "CCPA-DEF-001",        title: "PI/SPI classification + scoping",                                  description: "Per-system classification of personal information against the §1798.140 definitions, with attention to sensitive personal information categories (precise geolocation, racial/ethnic origin, religious beliefs, union membership, genetic data, biometric data, health, sex life, citizenship/immigration status, communications contents). Drives applicable consumer-rights workflows.",                                category: "data-protection",      evidenceTypes: ["report","configuration","procedure","attestation"],     clauseRefs: ["§1798.140"],                          riskLevel: "high"   },
    { controlRef: "CCPA-SP-001",         title: "Service-provider + contractor + third-party contracts",            description: "Written contracts with every service provider/contractor that satisfy §1798.140(ag): prohibit sale/share, restrict use to specified business purpose, prohibit cross-context combination, audit + cooperation rights; distinct treatment for third parties + downstream-notification obligations.",                                                                                                                  category: "vendor-management",    evidenceTypes: ["contract","report","procedure","attestation"],         clauseRefs: ["§1798.140(ag)"],                     riskLevel: "high"   },
    { controlRef: "CCPA-EXEMPT-001",     title: "Exemption tracking",                                                description: "Documentation tracking which data sets are exempt under §1798.145 (CMIA, HIPAA, GLBA, FCRA, employee/B2B carve-outs as applicable in the year covered), with the basis + the data flow.",                                                                                                                                                                                                                              category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                        clauseRefs: ["§1798.145"],                          riskLevel: "limited" },
    { controlRef: "CCPA-SEC-001",        title: "Reasonable security procedures (§1798.150)",                        description: "Implementation + maintenance of reasonable security procedures and practices appropriate to the nature of the personal information (encryption + access control + monitoring + incident response). Reduces exposure to the private right of action for statutory damages ($100-$750 per consumer per incident).",                                                                                                category: "encryption",           evidenceTypes: ["configuration","report","procedure","attestation"],     clauseRefs: ["§1798.150"],                          riskLevel: "high"   },
    { controlRef: "CCPA-ENF-001",        title: "Enforcement-risk awareness (CPPA + AG)",                            description: "Risk register includes administrative fine exposure ($2,500 / violation; $7,500 / intentional violation or violation involving minors), private right of action statutory damages, injunctive relief. Includes monitoring of CPPA enforcement actions and rulings.",                                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                        clauseRefs: ["§1798.155","§1798.199"],            riskLevel: "limited" },
    { controlRef: "CCPA-CHILDREN-001",   title: "Minors handling (under-16 opt-in)",                                  description: "Affirmative opt-in for sale/share of personal information of consumers known to be under 16, with parental consent required for those under 13; suppression of opt-in defaults; record retention. Heightened civil penalty exposure for violations involving minors.",                                                                                                                                                category: "data-protection",      evidenceTypes: ["procedure","log","screenshot","report"],                clauseRefs: ["§1798.120","§1798.155"],            riskLevel: "high"   },
    { controlRef: "CCPA-ADMT-001",       title: "Automated decision-making transparency + opt-out (CPPA reg.)",     description: "Tracking of CPPA's rulemaking on automated decision-making technology (§1798.185(a)(15)-(16)); pre-deployment readiness for the access + opt-out requirements once final regulations take effect (expected 2025-2026).",                                                                                                                                                                                              category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                     clauseRefs: ["§1798.185"],                          riskLevel: "high"   },
    { controlRef: "CCPA-RISK-AUDIT-001", title: "Risk assessment + cybersecurity audit (CPPA reg.)",                 description: "Risk-assessment programme for processing that presents significant risk to consumer privacy/security; annual cybersecurity-audit programme. Both required by CPPA regulations issued under §1798.185(a)(14)-(15), expected effective 2025-2026.",                                                                                                                                                                    category: "data-protection",      evidenceTypes: ["report","procedure","attestation"],                     clauseRefs: ["§1798.185"],                          riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "CCPA-Q-001", text: "Does the business meet any of the three CCPA thresholds — annual gross revenue > $25M, processing PI of 100k+ California consumers/households, or 50%+ revenue from selling/sharing California PI?",                       category: "applicability",   riskWeight: 1.0, clauseRefs: ["§1798.140"] },
    { questionRef: "CCPA-Q-002", text: "Is a Notice at Collection delivered at/before the point of collection, and is the privacy policy refreshed at least every 12 months (§1798.100 + §1798.130)?",                                                              category: "notice",          riskWeight: 0.9, clauseRefs: ["§1798.100","§1798.130"] },
    { questionRef: "CCPA-Q-003", text: "Can consumer rights — know, delete, correct, know-sale/share — be fulfilled within 45 days (one 45-day extension allowed)?",                                                                                                category: "rights",          riskWeight: 1.0, clauseRefs: ["§1798.100","§1798.105","§1798.106","§1798.110","§1798.115"] },
    { questionRef: "CCPA-Q-004", text: "Is a 'Do Not Sell or Share My Personal Information' link in place on every homepage, and is the Global Privacy Control (GPC) signal honoured (§1798.120 + §1798.135)?",                                                    category: "opt-out",         riskWeight: 1.0, clauseRefs: ["§1798.120","§1798.135"] },
    { questionRef: "CCPA-Q-005", text: "Where SPI is processed beyond reasonably-expected purposes, is a 'Limit the Use of My Sensitive Personal Information' link in place (§1798.121 + §1798.135)?",                                                              category: "spi",             riskWeight: 0.9, clauseRefs: ["§1798.121","§1798.135"] },
    { questionRef: "CCPA-Q-006", text: "Are operational controls in place preventing discrimination against consumers who exercise rights, with any financial-incentive programmes documented (§1798.125)?",                                                       category: "non-discrim",     riskWeight: 0.7, clauseRefs: ["§1798.125"] },
    { questionRef: "CCPA-Q-007", text: "Is personal information classified against §1798.140 definitions, with SPI categories explicitly tracked?",                                                                                                                category: "classification",  riskWeight: 0.9, clauseRefs: ["§1798.140"] },
    { questionRef: "CCPA-Q-008", text: "Do every service provider + contractor + third-party arrangement have a written contract satisfying §1798.140(ag)?",                                                                                                       category: "contracts",       riskWeight: 1.0, clauseRefs: ["§1798.140(ag)"] },
    { questionRef: "CCPA-Q-009", text: "Are §1798.145 exemptions (CMIA, HIPAA, GLBA, FCRA, employee/B2B) documented with the basis and the data flow?",                                                                                                              category: "exemptions",      riskWeight: 0.7, clauseRefs: ["§1798.145"] },
    { questionRef: "CCPA-Q-010", text: "Are reasonable security procedures + practices implemented to reduce exposure to the private right of action under §1798.150?",                                                                                            category: "security",        riskWeight: 1.0, clauseRefs: ["§1798.150"] },
    { questionRef: "CCPA-Q-011", text: "For minors: affirmative opt-in for sale/share of under-16s, parental consent for under-13s, no opt-in defaults?",                                                                                                          category: "minors",          riskWeight: 0.9, clauseRefs: ["§1798.120","§1798.155"] },
    { questionRef: "CCPA-Q-012", text: "Is enforcement-risk exposure ($2,500 / violation, $7,500 / intentional or minor-related, private statutory damages $100-$750/consumer/incident) reflected in the risk register?",                                          category: "enforcement",     riskWeight: 0.6, clauseRefs: ["§1798.155","§1798.150"] },
    { questionRef: "CCPA-Q-013", text: "Is the CPPA rulemaking on ADMT + risk assessments + annual cybersecurity audits tracked, with pre-effective-date readiness in place (§1798.185)?",                                                                          category: "cppa-reg",        riskWeight: 0.8, clauseRefs: ["§1798.185"] },
  ],
};
