import type { Framework } from "@regunav/types";

/**
 * DORA — Digital Operational Resilience Act.
 * Regulation (EU) 2022/2554 of the European Parliament and of the Council
 * of 14 December 2022 on digital operational resilience for the financial
 * sector.
 *
 * Source: https://eur-lex.europa.eu/eli/reg/2022/2554/oj
 *
 * Key dates (encoded in the rule-pack manifest at
 * packages/frameworks/manifests/dora.manifest.json):
 *   2022-12-14 — adopted
 *   2023-01-16 — in force
 *   2025-01-17 — applicable
 *
 * Clauses, controls and questions below cite the published text. They are
 * structural references to the regulation, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const DORA: Framework = {
  schemaVersion: 1,
  code: "DORA",
  name: "DORA",
  version: "(EU) 2022/2554",
  description:
    "EU regulation establishing uniform requirements for the security of network and information systems supporting business processes of financial entities in the Union, and for the digital operational resilience of those entities. Covers ICT risk management (Chapter II), ICT-related incident reporting (Chapter III), digital operational resilience testing including TLPT (Chapter IV), ICT third-party risk (Chapter V), information-sharing arrangements (Chapter VI) and oversight of critical ICT third-party service providers (Chapter V Section II).",
  jurisdiction: ["EU", "EEA"],
  referenceUrl: "https://eur-lex.europa.eu/eli/reg/2022/2554/oj",

  // ─── Clauses (22 of the most-cited Articles) ─────────────────────────────
  clauses: [
    { clauseRef: "Art. 2",   title: "Scope — financial entities and ICT third-party service providers",                 description: "DORA applies to financial entities including credit institutions, payment institutions, electronic-money institutions, investment firms, crypto-asset service providers, central securities depositories, central counterparties, trading venues, trade repositories, AIFMs, UCITS management companies, data-reporting service providers, insurance and reinsurance undertakings, insurance and reinsurance intermediaries (with proportionality), institutions for occupational retirement provision, credit rating agencies, administrators of critical benchmarks, crowdfunding service providers, securitisation repositories, and ICT third-party service providers.", mandatory: true },
    { clauseRef: "Art. 5",   title: "ICT risk management framework — governance and organisation",                       description: "Financial entities shall have in place an internal governance and control framework that ensures an effective and prudent management of ICT risk. The management body shall define, approve, oversee and be responsible for the implementation of all arrangements related to the ICT risk management framework. Top management has ultimate accountability for managing ICT risk.", mandatory: true },
    { clauseRef: "Art. 6",   title: "ICT risk management framework — full lifecycle",                                    description: "Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system, which enables them to address ICT risk quickly, efficiently and comprehensively, and to ensure a high level of digital operational resilience.", mandatory: true },
    { clauseRef: "Art. 7",   title: "ICT systems, protocols and tools",                                                  description: "Financial entities shall use and maintain updated ICT systems, protocols and tools that are appropriate to the magnitude of operations, support performance of activities and provision of services, resilient and reliable enough to handle peak demand and process data securely.", mandatory: true },
    { clauseRef: "Art. 8",   title: "Identification of ICT-supported business functions, sources of ICT risk and assets", description: "Financial entities shall identify, classify and adequately document all ICT-supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their interdependencies. They shall identify on a continuous basis all sources of ICT risk, classify them according to criticality and risk level, and review the risk scenarios at least yearly.", mandatory: true },
    { clauseRef: "Art. 9",   title: "Protection and prevention",                                                          description: "Financial entities shall continuously monitor and control the security and functioning of ICT systems and tools, minimise the impact of ICT risk on ICT systems through the deployment of appropriate ICT security tools, policies and procedures, and maintain mechanisms and policies to limit the impact of ICT incidents.", mandatory: true },
    { clauseRef: "Art. 10",  title: "Detection",                                                                          description: "Financial entities shall have in place mechanisms to promptly detect anomalous activities, including ICT network performance issues and ICT-related incidents, and identify potential material single points of failure. Detection mechanisms shall be tested on a regular basis.", mandatory: true },
    { clauseRef: "Art. 11",  title: "Response and recovery",                                                              description: "Financial entities shall put in place a comprehensive ICT business continuity policy, response and recovery plans, including arrangements for backup, restoration and recovery, and shall periodically test those plans. Recovery time and recovery point objectives shall be set out per critical or important function.", mandatory: true },
    { clauseRef: "Art. 12",  title: "Backup policies and procedures, restoration and recovery procedures and methods",   description: "Financial entities shall develop, document and implement backup policies and procedures specifying the scope of data subject to backup, the minimum frequency, based on the criticality of the information or the confidentiality level of the data, and recovery procedures including the test of restored data.", mandatory: true },
    { clauseRef: "Art. 13",  title: "Learning and evolving",                                                              description: "Financial entities shall have capabilities and staff to gather information on vulnerabilities, cyber threats and ICT-related incidents, particularly cyber-attacks, and analyse their likely impact on their digital operational resilience. Post-incident reviews shall examine causes of disruption and identify required improvements.", mandatory: true },
    { clauseRef: "Art. 14",  title: "Communication",                                                                       description: "Financial entities shall have crisis-communication plans enabling responsible disclosure of major ICT-related incidents or vulnerabilities to clients and counterparts as well as to the public, as appropriate, with clear responsibilities and approval procedures.", mandatory: true },
    { clauseRef: "Art. 17",  title: "ICT-related incident management process",                                            description: "Financial entities shall define, establish and implement an ICT-related incident management process to detect, manage and notify ICT-related incidents. The process shall set out indicators for early warning, procedures to identify, track, log, categorise and classify, and define the roles and responsibilities for incident response.", mandatory: true },
    { clauseRef: "Art. 18",  title: "Classification of ICT-related incidents and cyber threats",                         description: "Financial entities shall classify ICT-related incidents based on impact criteria set out in regulatory technical standards (number/relevance of clients or counterparts affected, geographic spread, data losses, severity of impact on ICT systems, duration, criticality of services affected, economic impact, etc.). Major ICT-related incidents shall be reported.", mandatory: true },
    { clauseRef: "Art. 19",  title: "Reporting of major ICT-related incidents and voluntary notification of significant cyber threats", description: "Financial entities shall report major ICT-related incidents to the relevant competent authority. Initial notification, intermediate report and final report shall be submitted within the time frames set out in the RTS adopted under Article 20.", mandatory: true },
    { clauseRef: "Art. 24",  title: "General requirements for the performance of digital operational resilience testing", description: "Financial entities other than microenterprises shall establish, maintain and review a sound and comprehensive digital operational resilience testing programme, applying a risk-based approach taking into account the criteria set out in Article 4(2). The testing programme shall include a range of assessments, tests, methodologies, practices and tools.", mandatory: true },
    { clauseRef: "Art. 26",  title: "Advanced testing of ICT tools, systems and processes based on TLPT",                description: "Financial entities identified by the competent authority shall perform at least every 3 years advanced testing by means of threat-led penetration testing (TLPT). The TLPT shall cover several critical or important functions and be performed on live production systems supporting such functions.", mandatory: true },
    { clauseRef: "Art. 28",  title: "General principles for sound management of ICT third-party risk",                    description: "Financial entities shall manage ICT third-party risk as an integral component of ICT risk, in accordance with the principles in Article 5. The management body remains fully responsible for compliance with ICT third-party risk management requirements. Financial entities shall adopt and review a strategy on ICT third-party risk.", mandatory: true },
    { clauseRef: "Art. 29",  title: "Preliminary assessment of ICT concentration risk and further subcontracting arrangements", description: "Financial entities shall assess whether the contractual arrangement covers an ICT service supporting a critical or important function and whether it could lead to ICT concentration risk. The assessment shall take into account other contractual arrangements and the subcontracting chain.", mandatory: true },
    { clauseRef: "Art. 30",  title: "Key contractual provisions",                                                          description: "Contractual arrangements with ICT third-party service providers shall include, among others: a complete description of the services, locations where the data is processed, service-level descriptions, provisions on data accessibility, integrity and security, full audit and access rights, exit strategies, cooperation with competent authorities, and termination rights.", mandatory: true },
    { clauseRef: "Art. 31",  title: "Designation of critical ICT third-party service providers",                          description: "The European Supervisory Authorities (ESAs) shall designate critical ICT third-party service providers based on criteria including systemic impact on stability/continuity/quality of financial services, systemic character or importance of the financial entities, reliance of financial entities, degree of substitutability.", mandatory: true },
    { clauseRef: "Art. 35",  title: "Powers of the Lead Overseer",                                                          description: "Each critical ICT third-party service provider shall be subject to oversight by a Lead Overseer designated from among ESAs, with powers including requesting all relevant information and documentation, conducting general investigations and on-site inspections, issuing recommendations on areas covered by the oversight tasks.", mandatory: true },
    { clauseRef: "Art. 45",  title: "Information-sharing arrangements on cyber threat information and intelligence",       description: "Financial entities may exchange amongst themselves cyber threat information and intelligence, including indicators of compromise, tactics, techniques and procedures, cyber security alerts and configuration tools, to the extent that the sharing arrangements protect the potentially sensitive nature of the information.", mandatory: true },
  ],

  // ─── Controls (14 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "DORA-GOV-001",   title: "ICT risk management governance + board accountability",      description: "Documented governance framework with management-body approval of ICT risk policy, defined roles and authority, board-level reporting cadence, and demonstrable management-body accountability for the framework. Maps Art. 5.",                                                                                                          category: "ai-system-governance",  evidenceTypes: ["policy","attestation","report"],                       clauseRefs: ["Art. 5"],                          riskLevel: "high"   },
    { controlRef: "DORA-RM-001",    title: "ICT risk management framework — full lifecycle",             description: "Comprehensive ICT risk management framework: identify, protect, detect, respond, recover, learn. Documented as a single artefact with annual review and on material change. Maps Art. 6.",                                                                                                                                          category: "ai-system-governance",  evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["Art. 6"],                          riskLevel: "high"   },
    { controlRef: "DORA-ASSETS-001",title: "ICT-supported business function + asset inventory",          description: "Inventory of ICT-supported business functions, information assets, ICT assets and interdependencies; classification by criticality + risk level; annual review of sources of ICT risk and risk scenarios. Maps Art. 7-8.",                                                                                                            category: "ai-system-governance",  evidenceTypes: ["report","configuration","attestation"],                clauseRefs: ["Art. 7","Art. 8"],                 riskLevel: "high"   },
    { controlRef: "DORA-PROT-001",  title: "Protection + prevention controls",                            description: "Continuous monitoring + control of ICT system security, deployment of ICT security tools (encryption, access control, network segmentation, vulnerability mgmt), policy + procedure layer governing them. Maps Art. 9.",                                                                                                              category: "data-protection",       evidenceTypes: ["configuration","policy","procedure","attestation"],   clauseRefs: ["Art. 9"],                          riskLevel: "high"   },
    { controlRef: "DORA-DET-001",   title: "Detection + monitoring",                                       description: "Mechanisms to promptly detect anomalous activities and ICT-related incidents, tested on a regular basis. Includes SOC alerting + SPOF identification + threshold-based escalation. Maps Art. 10.",                                                                                                                                  category: "logging-monitoring",    evidenceTypes: ["configuration","log","report","procedure"],            clauseRefs: ["Art. 10"],                         riskLevel: "high"   },
    { controlRef: "DORA-BCM-001",   title: "Business continuity, response and recovery",                  description: "ICT business-continuity policy, response and recovery plans, backup policy with per-asset frequency, RTO/RPO per critical or important function, periodic test of restored data. Maps Art. 11-12.",                                                                                                                                category: "business-continuity",   evidenceTypes: ["procedure","report","configuration","attestation"],   clauseRefs: ["Art. 11","Art. 12"],               riskLevel: "high"   },
    { controlRef: "DORA-LEARN-001", title: "Post-incident learning + vulnerability + threat intel",       description: "Process for gathering information on vulnerabilities, cyber threats and ICT-related incidents; post-incident reviews documenting root cause and improvements; threat-intel feed into the framework. Maps Art. 13.",                                                                                                                category: "ai-system-governance",  evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 13"],                         riskLevel: "high"   },
    { controlRef: "DORA-COMMS-001", title: "Crisis-communication plans",                                  description: "Documented crisis-communication plans covering responsible disclosure to clients, counterparts and the public; roles, approval gates, communication templates. Maps Art. 14.",                                                                                                                                                    category: "incident-response",     evidenceTypes: ["procedure","report","attestation"],                    clauseRefs: ["Art. 14"],                         riskLevel: "high"   },
    { controlRef: "DORA-INC-001",   title: "ICT incident management process + classification",            description: "Incident-management process with detection indicators, identification, tracking, logging, categorisation, classification per Article 18 criteria. Includes major-incident determination workflow. Maps Art. 17-18.",                                                                                                                category: "incident-response",     evidenceTypes: ["procedure","incident_record","configuration"],         clauseRefs: ["Art. 17","Art. 18"],               riskLevel: "high"   },
    { controlRef: "DORA-REP-001",   title: "Major ICT-related incident reporting workflow",               description: "Workflow for the initial notification, intermediate report and final report to the relevant competent authority within the time frames in the Article-20 RTS. Includes evidence preservation + cooperation procedure. Maps Art. 19.",                                                                                            category: "incident-response",     evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 19"],                         riskLevel: "high"   },
    { controlRef: "DORA-TEST-001",  title: "Digital operational resilience testing programme",            description: "Risk-based testing programme with a documented scope, methodologies (vulnerability assessments, scenario-based tests, performance tests, end-to-end tests, penetration tests), and remediation tracking. Microenterprises out of scope. Maps Art. 24.",                                                                              category: "vulnerability-management", evidenceTypes: ["report","procedure","configuration"],               clauseRefs: ["Art. 24"],                         riskLevel: "high"   },
    { controlRef: "DORA-TLPT-001",  title: "Threat-led penetration testing (TLPT)",                       description: "TLPT every 3 years (or more frequently if required), conducted on live production systems supporting critical or important functions, against a defined threat scenario. Includes red-team + blue-team coordination + attestation. Maps Art. 26.",                                                                                  category: "vulnerability-management", evidenceTypes: ["report","attestation","configuration"],             clauseRefs: ["Art. 26"],                         riskLevel: "high"   },
    { controlRef: "DORA-3P-001",    title: "ICT third-party risk management + Art. 30 contractual terms", description: "ICT third-party risk strategy; preliminary assessment of concentration risk and subcontracting; contractual arrangements satisfying Article 30 (service description, data locations, SLAs, audit rights, exit strategy, cooperation with competent authorities, termination rights). Maps Art. 28-30.",                                category: "vendor-management",     evidenceTypes: ["contract","report","attestation","procedure"],         clauseRefs: ["Art. 28","Art. 29","Art. 30"],     riskLevel: "high"   },
    { controlRef: "DORA-CTPP-001",  title: "Critical-TPP awareness + cooperation with Lead Overseer",     description: "Identification of contractual arrangements with TPPs designated as critical by the ESAs; preparation for Lead-Overseer oversight including information requests, on-site inspections, recommendations response. Maps Art. 31 + 35.",                                                                                              category: "vendor-management",     evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Art. 31","Art. 35"],               riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "DORA-Q-001", text: "Is the entity in scope as a financial entity or ICT third-party service provider (Art. 2)?",                                                                                                  category: "applicability",      riskWeight: 1.0, clauseRefs: ["Art. 2"] },
    { questionRef: "DORA-Q-002", text: "Has the management body defined, approved and oversees the ICT risk management framework, with documented accountability (Art. 5)?",                                                          category: "governance",         riskWeight: 1.0, clauseRefs: ["Art. 5"] },
    { questionRef: "DORA-Q-003", text: "Is a sound, comprehensive ICT risk management framework in place, reviewed at least annually and on material change (Art. 6)?",                                                                category: "rm-framework",       riskWeight: 1.0, clauseRefs: ["Art. 6"] },
    { questionRef: "DORA-Q-004", text: "Are ICT-supported business functions, information assets and ICT assets inventoried and classified by criticality (Art. 7-8)?",                                                                category: "asset-inventory",    riskWeight: 0.9, clauseRefs: ["Art. 7","Art. 8"] },
    { questionRef: "DORA-Q-005", text: "Are appropriate protection + prevention ICT security tools, policies and procedures deployed and reviewed (Art. 9)?",                                                                          category: "protection",         riskWeight: 0.9, clauseRefs: ["Art. 9"] },
    { questionRef: "DORA-Q-006", text: "Are detection mechanisms for anomalous activities + incidents implemented and tested regularly (Art. 10)?",                                                                                    category: "detection",          riskWeight: 0.9, clauseRefs: ["Art. 10"] },
    { questionRef: "DORA-Q-007", text: "Is an ICT business-continuity policy with response/recovery plans and tested backup procedures in place, with RTO/RPO per critical function (Art. 11-12)?",                                    category: "bcm",                riskWeight: 1.0, clauseRefs: ["Art. 11","Art. 12"] },
    { questionRef: "DORA-Q-008", text: "Are post-incident reviews + threat-intel capabilities operating and feeding back into the framework (Art. 13)?",                                                                                category: "learn",              riskWeight: 0.7, clauseRefs: ["Art. 13"] },
    { questionRef: "DORA-Q-009", text: "Are crisis-communication plans documented and tested, with clear responsibilities and approval gates (Art. 14)?",                                                                              category: "comms",              riskWeight: 0.7, clauseRefs: ["Art. 14"] },
    { questionRef: "DORA-Q-010", text: "Is an ICT-related incident management process defined, with classification per Article 18 RTS criteria (Art. 17-18)?",                                                                          category: "incident",           riskWeight: 1.0, clauseRefs: ["Art. 17","Art. 18"] },
    { questionRef: "DORA-Q-011", text: "Can a major ICT-related incident be reported via the initial / intermediate / final reports within the Article-20 RTS time frames (Art. 19)?",                                                  category: "reporting",          riskWeight: 1.0, clauseRefs: ["Art. 19"] },
    { questionRef: "DORA-Q-012", text: "Is a digital operational resilience testing programme established and operating, applying a risk-based approach (Art. 24)?",                                                                  category: "testing",            riskWeight: 0.9, clauseRefs: ["Art. 24"] },
    { questionRef: "DORA-Q-013", text: "Where required by the competent authority, is TLPT performed at least every 3 years on live production systems supporting critical or important functions (Art. 26)?",                         category: "tlpt",               riskWeight: 0.8, clauseRefs: ["Art. 26"] },
    { questionRef: "DORA-Q-014", text: "Is an ICT third-party risk strategy in place, with preliminary assessment of concentration risk + subcontracting (Art. 28-29)?",                                                                category: "tpp",                riskWeight: 0.9, clauseRefs: ["Art. 28","Art. 29"] },
    { questionRef: "DORA-Q-015", text: "Do contractual arrangements with ICT TPPs satisfy Article 30 (service description, data locations, SLA, full audit + access rights, exit strategy, cooperation with competent authorities, termination)?", category: "contract",           riskWeight: 1.0, clauseRefs: ["Art. 30"] },
    { questionRef: "DORA-Q-016", text: "Where critical-TPP designations apply, are contractual + governance arrangements in place to support Lead-Overseer oversight (Art. 31, Art. 35)?",                                              category: "ctpp",               riskWeight: 0.7, clauseRefs: ["Art. 31","Art. 35"] },
    { questionRef: "DORA-Q-017", text: "Are information-sharing arrangements (cyber threat intelligence + IOCs) in place where appropriate, protecting sensitive information (Art. 45)?",                                              category: "info-sharing",       riskWeight: 0.5, clauseRefs: ["Art. 45"] },
  ],
};
