import type { Framework } from "@regunav/types";

/**
 * DPDP — Digital Personal Data Protection Act, 2023 (India). Act No. 22
 * of 2023, assented to by the President of India on 11 August 2023.
 * Implements India's first general personal data protection framework
 * applying to digital personal data. The Act's provisions come into
 * force in stages by notification of the Central Government; the Draft
 * DPDP Rules 2025 (issued by MeitY for consultation in early 2025)
 * operationalise the obligations and the Data Protection Board of India.
 *
 * Sources:
 *   - DPDP Act 2023:
 *     https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf
 *   - MeitY data-protection page:
 *     https://www.meity.gov.in/data-protection-framework
 *
 * Clauses, controls and questions below cite the published Act by
 * section. They are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const DPDP_INDIA: Framework = {
  schemaVersion: 1,
  code: "DPDP_INDIA",
  name: "India DPDP Act",
  version: "2023",
  description:
    "India's general personal data protection statute. Regulates the processing of digital personal data of Data Principals (individuals) by Data Fiduciaries (determines the purpose + means) and Data Processors. Establishes the Data Protection Board of India as the regulator, sets out lawful bases (consent + 'certain legitimate uses' — DPDP's 'lawful purpose'), rights and duties of Data Principals, additional obligations for 'Significant Data Fiduciaries', a default 'cross-border-transfer-allowed unless restricted' regime, and penalties up to ₹250 crore per breach. Children + persons with disability receive heightened protection (verifiable parental consent + restrictions on tracking + targeted advertising).",
  jurisdiction: ["IN"],
  referenceUrl: "https://www.meity.gov.in/data-protection-framework",

  // ─── Clauses (16 — DPDP Act sections) ────────────────────────────────────
  clauses: [
    { clauseRef: "§3",   title: "Application of the Act",                                                          description: "The Act applies to the processing of digital personal data within India, including data that was collected in non-digital form and digitised subsequently. It also applies to the processing of digital personal data outside India where such processing is in connection with any activity related to offering of goods or services to Data Principals within India. The Act does not apply to processing for personal/domestic purposes or to data made public by the Data Principal or by law.", mandatory: true },
    { clauseRef: "§4",   title: "Grounds for processing of personal data",                                          description: "A Data Fiduciary may process the personal data of a Data Principal only in accordance with the provisions of this Act, and only for a lawful purpose — meaning either (a) for which the Data Principal has given consent, or (b) for certain legitimate uses (as defined in §7 — e.g. specified purposes for which the Data Principal has voluntarily provided data, performance of state functions, compliance with legal obligations, response to medical emergency, employment-related processing).", mandatory: true },
    { clauseRef: "§5",   title: "Notice to Data Principal",                                                          description: "Every request for consent shall be accompanied by, or preceded by, a notice given by the Data Fiduciary informing the Data Principal of: (i) the personal data to be processed and the specified purpose; (ii) the manner of exercising rights and lodging complaints with the Data Protection Board. Notice shall be in clear and plain language. Where consent was given before the Act's commencement, notice as soon as reasonably practicable.", mandatory: true },
    { clauseRef: "§6",   title: "Consent",                                                                            description: "Consent shall be free, specific, informed, unconditional, unambiguous, with a clear affirmative action signifying agreement to the processing for the specified purpose. The Data Principal may withdraw consent at any time, with ease comparable to giving it. On withdrawal, the Data Fiduciary shall cease processing (and cause its Data Processors to cease) within a reasonable time, unless required to retain the data under law.", mandatory: true },
    { clauseRef: "§7",   title: "Certain legitimate uses",                                                            description: "Personal data may be processed for the following legitimate uses without consent: (a) for which the Data Principal has voluntarily provided personal data + has not indicated non-consent; (b) for the State + its instrumentalities for permitted purposes; (c) compliance with any judgment or decree; (d) responding to a medical emergency involving a threat to life or immediate threat to the health of any Data Principal or any other person; (e) measures to provide medical treatment / health services during an epidemic, outbreak of disease, or any other threat to public health; (f) measures to ensure safety of any person during disaster or breakdown of public order; (g) for the purposes of employment, or those related to safeguarding the employer from loss/liability/threats.", mandatory: true },
    { clauseRef: "§8",   title: "General obligations of Data Fiduciary",                                              description: "The Data Fiduciary shall be responsible for complying with the Act and these Rules in respect of any processing it undertakes (whether on its own or through a Data Processor), including ensuring completeness/accuracy/consistency of personal data used to make any decision affecting the Data Principal; implementing technical + organisational measures to ensure effective observance; taking reasonable security safeguards to prevent personal data breach.", mandatory: true },
    { clauseRef: "§8(6)", title: "Breach notification",                                                                description: "In the event of a personal data breach, the Data Fiduciary shall give the Board and each affected Data Principal intimation of such breach, in such form and manner as may be prescribed (DPDP Rules). The notice describes the breach, its likely consequences, and the measures taken or proposed to mitigate.", mandatory: true },
    { clauseRef: "§9",   title: "Processing of personal data of children",                                            description: "The Data Fiduciary shall, before processing any personal data of a child, obtain verifiable consent of the parent (or lawful guardian) of such child. The Data Fiduciary shall not undertake such processing of personal data of a child that is likely to cause any detrimental effect on the well-being of the child, nor shall it undertake tracking or behavioural monitoring of children or targeted advertising directed at children.", mandatory: true },
    { clauseRef: "§10",  title: "Additional obligations of Significant Data Fiduciary",                              description: "Where the Central Government has notified a Data Fiduciary or class of Data Fiduciaries as a 'Significant Data Fiduciary' (based on volume + sensitivity, risk to electoral democracy, security of the State, public order, etc.), the SDF shall additionally: appoint a Data Protection Officer based in India; appoint an Independent Data Auditor; undertake periodic Data Protection Impact Assessment + periodic audit; undertake other measures the Government prescribes.", mandatory: true },
    { clauseRef: "§11",  title: "Right of Data Principal to information about personal data",                         description: "The Data Principal shall have the right to obtain from the Data Fiduciary, upon making a request in such manner as may be prescribed: (a) a summary of personal data being processed and the processing activities; (b) the identities of all other Data Fiduciaries and Data Processors with whom the personal data has been shared; (c) any other information related to the personal data of such Data Principal and its processing as may be prescribed.", mandatory: true },
    { clauseRef: "§12",  title: "Right to correction and erasure",                                                    description: "The Data Principal whose personal data has been processed shall have the right to correction, completion, updating and erasure of personal data for processing of which consent was given or processed for a legitimate use under §7, unless the data is required to be retained.", mandatory: true },
    { clauseRef: "§13",  title: "Right of grievance redressal",                                                        description: "The Data Principal shall have the right to readily available means of grievance redressal provided by the Data Fiduciary or Consent Manager. The Data Fiduciary / Consent Manager shall respond within the period prescribed. The Data Principal may then approach the Data Protection Board of India.", mandatory: true },
    { clauseRef: "§14",  title: "Right to nominate",                                                                    description: "The Data Principal shall have the right to nominate, in such manner as may be prescribed, any other individual, who shall, in the event of death or incapacity of the Data Principal, exercise the rights of the Data Principal in accordance with the Act.", mandatory: true },
    { clauseRef: "§16",  title: "Processing of personal data outside India",                                          description: "The Central Government may, by notification, restrict the transfer of personal data by a Data Fiduciary for processing to such country or territory outside India as may be so notified. Where no such notification has been issued, cross-border transfer of personal data is permitted, subject to compliance with other provisions of this Act. (Default-allow regime, distinct from EU GDPR's default-restrict.)", mandatory: true },
    { clauseRef: "§17",  title: "Exemptions",                                                                          description: "Provides exemptions for processing necessary for enforcing legal rights or claims; for judicial/quasi-judicial functions; for prevention/detection/investigation of offences; for processing of personal data of Data Principals not within the territory of India by a Data Fiduciary in India that has its operations elsewhere; for research, archiving, or statistical purposes if the data is not used to take any decision specific to a Data Principal; and for start-ups as notified by the Central Government.", mandatory: true },
    { clauseRef: "§33",  title: "Penalties",                                                                            description: "The Schedule to the Act prescribes penalties: up to ₹250 crore for failure to take reasonable security safeguards to prevent breach; up to ₹200 crore for failure to give intimation of personal data breach or for failure relating to children; up to ₹150 crore for breach of additional obligations of Significant Data Fiduciary; up to ₹50 crore for breach of duties of Data Principal; up to ₹10,000 + ₹50 crore for other breaches. The Data Protection Board determines and imposes penalties.", mandatory: true },
  ],

  // ─── Controls (11 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "DPDP-LAWFUL-001",  title: "Lawful-purpose register (consent + legitimate uses)",          description: "For every processing activity, document the lawful purpose under §4 (consent or §7 legitimate use). Where §7 is relied on, the specific clause and supporting evidence. Reviewed at material change.",                                                                                                                                                                                                                          category: "data-protection", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["§4","§7"],                          riskLevel: "high"   },
    { controlRef: "DPDP-NOTICE-001",  title: "§5 notice + consent capture",                                  description: "Notice in clear + plain language accompanying or preceding every consent request, describing the personal data, the specified purpose, the manner of exercising rights and lodging complaints with the Board. Notice for pre-commencement consent provided as soon as reasonably practicable.",                                                                                                                                  category: "data-protection", evidenceTypes: ["policy","screenshot","procedure","report"],            clauseRefs: ["§5"],                                riskLevel: "high"   },
    { controlRef: "DPDP-CONSENT-001", title: "§6 free + specific + informed consent + easy withdrawal",     description: "Consent capture meeting §6: free + specific + informed + unconditional + unambiguous + clear affirmative action. Withdrawal mechanism as easy as giving consent; cessation of processing (incl. through Data Processors) within reasonable time on withdrawal.",                                                                                                                                                                  category: "data-protection", evidenceTypes: ["log","screenshot","procedure","configuration"],        clauseRefs: ["§6"],                                riskLevel: "high"   },
    { controlRef: "DPDP-FIDUCIARY-001",title: "General Data Fiduciary obligations (§8)",                     description: "Accuracy + completeness + consistency of personal data used in any Data-Principal-affecting decision; T&O measures for compliance; reasonable security safeguards to prevent breach; downstream control of Data Processors via contract.",                                                                                                                                                                                            category: "data-protection", evidenceTypes: ["policy","procedure","configuration","attestation"],   clauseRefs: ["§8"],                                riskLevel: "high"   },
    { controlRef: "DPDP-BREACH-001",  title: "§8(6) Board + Data-Principal breach notification",             description: "Breach-detection capability tied to the incident-response runbook; classification + risk assessment; Board notification + Data-Principal notification in the form + manner prescribed by the DPDP Rules; documentation of consequences + mitigation measures.",                                                                                                                                                                  category: "incident-response", evidenceTypes: ["procedure","incident_record","report","attestation"],  clauseRefs: ["§8"],                                riskLevel: "high"   },
    { controlRef: "DPDP-CHILDREN-001",title: "Children + persons-with-disability protections (§9)",          description: "Pre-processing verifiable parental consent capture for any data of a child (under 18); no detrimental processing affecting child well-being; no tracking + behavioural monitoring of children; no targeted advertising directed at children. Persons-with-disability protections per DPDP Rules.",                                                                                                                                category: "data-protection", evidenceTypes: ["procedure","log","screenshot","attestation"],           clauseRefs: ["§9"],                                riskLevel: "high"   },
    { controlRef: "DPDP-SDF-001",     title: "Significant Data Fiduciary additional obligations (§10)",      description: "Where notified as a Significant Data Fiduciary: India-based DPO; Independent Data Auditor; periodic DPIA; periodic data-protection audit; other measures the Central Government prescribes.",                                                                                                                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["report","attestation","procedure"],                    clauseRefs: ["§10"],                              riskLevel: "high"   },
    { controlRef: "DPDP-RIGHTS-001",  title: "Data Principal rights workflow (§11-14)",                       description: "Documented intake + identity-verification + fulfilment workflow for the right to information (§11), correction/erasure (§12), grievance redressal (§13) and nomination (§14). Timeframes per DPDP Rules; appeal-route to the Data Protection Board.",                                                                                                                                                                          category: "data-protection", evidenceTypes: ["procedure","log","report","attestation"],              clauseRefs: ["§11","§12","§13","§14"],            riskLevel: "high"   },
    { controlRef: "DPDP-XBORDER-001", title: "§16 cross-border-transfer awareness",                          description: "Tracking of Central Government notifications restricting transfer of personal data to specified countries / territories; maintenance of the list of restricted destinations in the routing controls; safeguards-equivalent measures where transfers go to destinations of higher risk.",                                                                                                                                            category: "data-protection", evidenceTypes: ["report","configuration","attestation","procedure"],   clauseRefs: ["§16"],                              riskLevel: "high"   },
    { controlRef: "DPDP-EXEMPT-001",  title: "§17 exemption tracking",                                        description: "Documentation tracking which processing relies on which §17 exemption (legal rights or claims, judicial/quasi-judicial functions, offences prevention/detection/investigation, foreign-origin data without India-data-principal nexus, research/archiving/statistical without individual-targeting, notified start-ups). Basis + data flow retained.",                                                                          category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                       clauseRefs: ["§17"],                              riskLevel: "limited" },
    { controlRef: "DPDP-PEN-001",     title: "§33 penalty-exposure awareness + Board cooperation",            description: "Risk register reflects the DPDP penalty schedule (up to ₹250 crore for security-safeguards failure leading to breach; ₹200 crore for breach-intimation or children-related failures; ₹150 crore for SDF additional-obligations failures; etc.). Board-cooperation register tracking ongoing inquiries.",                                                                                                                            category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                       clauseRefs: ["§33"],                              riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "DPDP-Q-001",  text: "Does processing fall within DPDP scope — within India, OR processing outside India in connection with offering goods/services to Data Principals within India (§3)?",                                                category: "applicability",   riskWeight: 1.0, clauseRefs: ["§3"] },
    { questionRef: "DPDP-Q-002",  text: "Is the lawful purpose declared for each processing activity — §4 (consent + certain legitimate uses)?",                                                                                                                category: "lawful-purpose",  riskWeight: 1.0, clauseRefs: ["§4","§7"] },
    { questionRef: "DPDP-Q-003",  text: "Is a §5 notice (clear + plain language) provided with or before each consent request, covering data + purpose + rights + how to lodge complaints?",                                                                  category: "notice",          riskWeight: 0.9, clauseRefs: ["§5"] },
    { questionRef: "DPDP-Q-004",  text: "Is §6 consent free + specific + informed + unconditional + unambiguous, with easy withdrawal and prompt cessation across Data Processors?",                                                                            category: "consent",         riskWeight: 1.0, clauseRefs: ["§6"] },
    { questionRef: "DPDP-Q-005",  text: "Are §8 Data Fiduciary obligations met — accuracy/completeness/consistency for decision-affecting data, T&O measures, security safeguards?",                                                                            category: "fiduciary-obligs",riskWeight: 1.0, clauseRefs: ["§8"] },
    { questionRef: "DPDP-Q-006",  text: "Is a breach-notification workflow in place that notifies the Data Protection Board AND each affected Data Principal in the form + manner prescribed (§8(6))?",                                                       category: "breach",          riskWeight: 1.0, clauseRefs: ["§8"] },
    { questionRef: "DPDP-Q-007",  text: "Where processing children's data: verifiable parental consent captured? No tracking + behavioural monitoring of children? No targeted advertising to children (§9)?",                                                  category: "children",        riskWeight: 1.0, clauseRefs: ["§9"] },
    { questionRef: "DPDP-Q-008",  text: "Where designated as a Significant Data Fiduciary: India-based DPO, Independent Data Auditor, periodic DPIA + audit (§10)?",                                                                                          category: "sdf",             riskWeight: 0.9, clauseRefs: ["§10"] },
    { questionRef: "DPDP-Q-009",  text: "Can the four Data Principal rights (information, correction/erasure, grievance redressal, nomination) be fulfilled within the timeframes prescribed (§11-14)?",                                                       category: "rights",          riskWeight: 0.9, clauseRefs: ["§11","§12","§13","§14"] },
    { questionRef: "DPDP-Q-010", text: "Is the list of Central-Government-restricted cross-border destinations tracked, and are transfers routed accordingly (§16)?",                                                                                          category: "transfers",       riskWeight: 0.8, clauseRefs: ["§16"] },
    { questionRef: "DPDP-Q-011", text: "Are §17 exemptions (legal-rights enforcement, judicial functions, offence prevention, foreign-origin processing, research, notified start-ups) documented with basis + data flow?",                                    category: "exemptions",      riskWeight: 0.6, clauseRefs: ["§17"] },
    { questionRef: "DPDP-Q-012", text: "Is DPDP penalty exposure (up to ₹250 crore per breach, ₹200 crore for children/breach-intimation, ₹150 crore for SDF) reflected in the risk register?",                                                                category: "penalties",       riskWeight: 0.6, clauseRefs: ["§33"] },
    { questionRef: "DPDP-Q-013", text: "Is the Data Protection Board of India relationship register tracking open inquiries + correspondence?",                                                                                                                category: "board",           riskWeight: 0.6, clauseRefs: ["§33"] },
  ],
};
