import type { Framework } from "@regunav/types";

/**
 * EU AI Act — Regulation (EU) 2024/1689 of the European Parliament and of the
 * Council of 13 June 2024 laying down harmonised rules on artificial
 * intelligence.
 *
 * Sources:
 *   - Regulation text: https://eur-lex.europa.eu/eli/reg/2024/1689/oj
 *   - European Commission AI Act standardisation / implementation page:
 *     https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai
 *
 * Key dates (encoded in the rule-pack manifest at
 * packages/frameworks/manifests/eu-ai-act.manifest.json):
 *   2024-08-01 — in force
 *   2025-02-02 — Article 5 prohibitions applicable
 *   2025-08-02 — GPAI provisions applicable
 *   2026-08-02 — main applicability date
 *   2027-08-02 — high-risk Annex III applicability date (baseline, Art. 113)
 *
 * dateNotes — Digital Omnibus revision (high-risk applicability)
 * ----------------------------------------------------------------
 * The high-risk applicability dates in Art. 113 are the subject of the
 * European Commission's Digital Omnibus proposal, which would link those
 * dates to the availability of supporting tools (harmonised standards,
 * common specifications, guidance, conformity-assessment infrastructure).
 *
 *   - Original baseline: 2 Aug 2026 for high-risk systems per Regulation
 *     (EU) 2024/1689 Article 113 (with Annex III systems following the
 *     general application date and Annex I product-linked systems on
 *     their own track).
 *   - Digital Omnibus revised baseline: 2 Dec 2027 for Annex III
 *     high-risk systems and 2 Aug 2028 for Annex I product-related
 *     high-risk systems, in each case conditional on the availability of
 *     support tools; the earlier of the support-tool availability date
 *     or the revised baseline would govern.
 *   - Status: subject to formal adoption / support-tool availability —
 *     the revised dates are not yet in force. Implementers should plan
 *     against the original baseline and monitor the Digital Omnibus
 *     legislative track for the final dates.
 *
 * Clauses, controls and questions below cite the published text. They are
 * structural references to the regulation, not legal advice. See
 * `packages/ontology/LEGAL_DISCLAIMER.md`.
 */
export const EU_AI_ACT: Framework = {
  schemaVersion: 1,
  code: "EU_AI_ACT",
  name: "EU AI Act",
  version: "(EU) 2024/1689",
  description:
    "Risk-based regulation of AI systems and general-purpose AI models in the EU/EEA. Prohibited practices (Art. 5), high-risk requirements (Title III + Annex III), transparency obligations (Art. 50), and GPAI provisions (Title VIII Chapter V). Applies to providers, deployers, importers, distributors and authorised representatives.",
  jurisdiction: ["EU", "EEA"],
  referenceUrl: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",

  // ─── Clauses (25 of the most-cited Articles + 2 Annexes) ──────────────────
  clauses: [
    { clauseRef: "Art. 3",          title: "Definitions",                                                            description: "Defines 'AI system', 'general-purpose AI model', 'provider', 'deployer', 'importer', 'distributor', 'authorised representative', 'serious incident', 'making available on the market', 'placing on the market', 'putting into service'.", mandatory: true },
    { clauseRef: "Art. 4",          title: "AI literacy",                                                            description: "Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf.", mandatory: true },
    { clauseRef: "Art. 5(1)(a)",    title: "Prohibited — subliminal techniques distorting behaviour",                description: "Prohibits the placing on the market, putting into service, or use of an AI system that deploys subliminal techniques beyond a person's consciousness, or purposefully manipulative or deceptive techniques, with the objective or effect of materially distorting the behaviour of a person or a group, causing significant harm.", mandatory: true },
    { clauseRef: "Art. 5(1)(b)",    title: "Prohibited — exploitation of vulnerabilities",                          description: "Prohibits AI systems that exploit any of the vulnerabilities of a natural person or specific group due to age, disability, or social/economic situation, with the objective or effect of materially distorting their behaviour and causing significant harm.", mandatory: true },
    { clauseRef: "Art. 5(1)(c)",    title: "Prohibited — social scoring by public authorities",                     description: "Prohibits AI systems for the evaluation or classification of natural persons over time based on social behaviour or personality characteristics where the social score leads to detrimental or unfavourable treatment in contexts unrelated to those in which the data was originally generated, or that is unjustified or disproportionate.", mandatory: true },
    { clauseRef: "Art. 5(1)(d)",    title: "Prohibited — predictive policing based solely on profiling",            description: "Prohibits AI systems making risk assessments of natural persons in order to assess or predict the risk of committing a criminal offence, based solely on profiling or on assessing personality traits.", mandatory: true },
    { clauseRef: "Art. 5(1)(e)",    title: "Prohibited — untargeted scraping of facial images",                     description: "Prohibits AI systems that create or expand facial recognition databases through the untargeted scraping of facial images from the internet or CCTV footage.", mandatory: true },
    { clauseRef: "Art. 5(1)(f)",    title: "Prohibited — emotion inference in workplaces and educational institutions", description: "Prohibits AI systems that infer emotions of a natural person in the areas of workplace and educational institutions, except where the use of the AI system is intended to be put in place or into the market for medical or safety reasons.", mandatory: true },
    { clauseRef: "Art. 5(1)(g)",    title: "Prohibited — biometric categorisation by sensitive attributes",         description: "Prohibits biometric categorisation systems that categorise individually natural persons based on their biometric data to deduce or infer their race, political opinions, trade union membership, religious or philosophical beliefs, sex life or sexual orientation.", mandatory: true },
    { clauseRef: "Art. 6",          title: "Classification rules for high-risk AI systems",                         description: "An AI system is high-risk if it is intended to be used as a safety component of a product, or is itself a product, covered by the Union harmonisation legislation listed in Annex I AND required to undergo third-party conformity assessment. AI systems referred to in Annex III are also high-risk, subject to the Art. 6(3) carve-outs (narrow procedural task, improving a previously completed human activity, detecting decision-making patterns, or preparatory tasks).", mandatory: true },
    { clauseRef: "Art. 9",          title: "Risk management system",                                                description: "A risk management system shall be established, implemented, documented and maintained for high-risk AI systems. It shall be a continuous iterative process planned and run throughout the entire lifecycle of the system.", mandatory: true },
    { clauseRef: "Art. 10",         title: "Data and data governance",                                              description: "Training, validation and testing data sets shall be subject to appropriate data governance and management practices, including data origin and lineage, bias examination, representativeness, completeness, and gap remediation in view of the intended purpose.", mandatory: true },
    { clauseRef: "Art. 11",         title: "Technical documentation",                                               description: "Technical documentation of a high-risk AI system shall be drawn up before placing on the market or putting into service and kept up-to-date. Content is set out in Annex IV.", mandatory: true },
    { clauseRef: "Art. 12",         title: "Record-keeping (logs)",                                                 description: "High-risk AI systems shall technically allow for the automatic recording of events ('logs') over the duration of the system's lifetime, sufficient for traceability appropriate to the intended purpose.", mandatory: true },
    { clauseRef: "Art. 13",         title: "Transparency and provision of information to deployers",                description: "High-risk AI systems shall be sufficiently transparent for deployers to interpret a system's output and use it appropriately, with concise, complete, correct and clear instructions for use provided in an appropriate digital format.", mandatory: true },
    { clauseRef: "Art. 14",         title: "Human oversight",                                                       description: "High-risk AI systems shall be designed to be effectively overseen by natural persons during use. Oversight measures shall enable the assigned individual to intervene on operation or interrupt the system through a 'stop' control.", mandatory: true },
    { clauseRef: "Art. 15",         title: "Accuracy, robustness and cybersecurity",                                description: "High-risk AI systems shall achieve appropriate levels of accuracy, robustness and cybersecurity, consistent throughout their lifecycle. Accuracy levels and metrics shall be declared in the instructions for use.", mandatory: true },
    { clauseRef: "Art. 17",         title: "Quality management system",                                             description: "Providers of high-risk AI systems shall put a QMS in place that ensures compliance with this Regulation, documented as written policies, procedures and instructions.", mandatory: true },
    { clauseRef: "Art. 18",         title: "Documentation keeping",                                                 description: "Providers shall keep technical documentation, QMS documentation, notified-body change approvals (where applicable) and the EU declaration of conformity for at least 10 years after the system is placed on the market or put into service.", mandatory: true },
    { clauseRef: "Art. 19",         title: "Automatically generated logs",                                          description: "Providers shall keep logs automatically generated by their high-risk AI systems for at least six months, where the logs are under their control, unless otherwise required.", mandatory: true },
    { clauseRef: "Art. 26",         title: "Obligations of deployers of high-risk AI systems",                      description: "Deployers shall use high-risk AI systems per the instructions for use, assign human oversight to a competent person, ensure input-data appropriateness, monitor operation, retain logs, and inform workers' representatives and affected workers of use.", mandatory: true },
    { clauseRef: "Art. 27",         title: "Fundamental rights impact assessment (FRIA)",                           description: "Deployers that are bodies governed by public law, private operators providing public services, and deployers using Annex III(5)(b) and (5)(c) high-risk AI systems shall assess the impact on fundamental rights before deployment.", mandatory: true },
    { clauseRef: "Art. 50",         title: "Transparency obligations for certain AI systems (limited-risk)",        description: "Providers shall ensure that AI systems interacting directly with natural persons disclose their AI nature unless this is obvious. Deployers of AI systems generating deep fakes shall disclose that the content has been artificially generated or manipulated.", mandatory: true },
    { clauseRef: "Art. 53",         title: "Obligations for providers of general-purpose AI models",                description: "GPAI providers shall maintain technical documentation, provide downstream-integrator documentation, implement an EU copyright-compliance policy, and publish a sufficiently detailed summary of training-content.", mandatory: true },
    { clauseRef: "Art. 55",         title: "Obligations for providers of GPAI models with systemic risk",           description: "GPAI providers classified as systemic-risk shall perform model evaluation including adversarial testing, assess and mitigate systemic risks, track and report serious incidents, and ensure cybersecurity protection of model and infrastructure.", mandatory: true },
    { clauseRef: "Art. 72",         title: "Post-market monitoring by providers",                                   description: "Providers shall establish and document a post-market monitoring system proportionate to the nature of the AI technologies and the risks of the high-risk AI system, feeding back into the Art. 9 risk-management cycle.", mandatory: true },
    { clauseRef: "Art. 73",         title: "Reporting of serious incidents",                                        description: "Providers shall report any serious incident to the market surveillance authorities of the affected Member States within 15 days of becoming aware of a causal link or reasonable likelihood of one.", mandatory: true },
    { clauseRef: "Art. 113",        title: "Entry into force and application",                                      description: "Sets the staggered entry-into-application schedule: 2 February 2025 for the Art. 5 prohibitions, 2 August 2025 for GPAI provisions, 2 August 2026 as the general applicability date (baseline for high-risk obligations), and 2 August 2027 for high-risk AI systems referred to in Article 6(1) (Annex I product-linked). Subject to the Digital Omnibus proposal, which would link the high-risk application dates to the availability of supporting tools — proposed revised baselines of 2 December 2027 for Annex III high-risk systems and 2 August 2028 for Annex I product-related high-risk systems, conditional on support-tool availability. The Digital Omnibus revision is subject to formal adoption / support-tool availability; until then the published Art. 113 dates apply.", mandatory: true },
    { clauseRef: "Annex III",       title: "High-risk AI systems referred to in Article 6(2)",                      description: "Eight enumerated areas: (1) biometrics, (2) critical infrastructure, (3) education and vocational training, (4) employment and worker management, (5) access to essential private and public services and benefits, (6) law enforcement, (7) migration/asylum/border control, (8) administration of justice and democratic processes. Dual-dating note: high-risk obligations for Annex III systems are baselined at 2 August 2026 per Art. 113 of Regulation (EU) 2024/1689; the Digital Omnibus proposal would shift the Annex III applicability date to 2 December 2027 (and 2 August 2028 for Annex I product-related high-risk systems), conditional on the availability of supporting tools — subject to formal adoption / support-tool availability.", mandatory: true },
    { clauseRef: "Annex IV",        title: "Technical documentation referred to in Article 11(1)",                  description: "Required content includes the general description of the AI system, detailed description of elements and processes, performance metrics and their appropriateness, risk-management system detail, relevant changes over the lifecycle, harmonised standards applied, EU declaration of conformity, and post-market performance evaluation system.", mandatory: true },
  ],

  // ─── Controls (16 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "EUAI-RM-001",     title: "Continuous risk-management lifecycle",                  description: "Iterative risk-identification, analysis, evaluation and treatment process run throughout the AI system's lifecycle. Outputs include a risk register, treatment plan, and residual-risk acceptance record signed by the AI governance owner.",                                                          category: "ai-system-governance",     evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["Art. 9"],                            riskLevel: "high" },
    { controlRef: "EUAI-DG-001",     title: "Data governance for training, validation and testing",  description: "Documented design choices, lineage, bias examination and data-gap remediation across the training/validation/test sets. Captures origin, representativeness, error rate and bias mitigations.",                                                                                  category: "data-protection",          evidenceTypes: ["policy","procedure","report","report"],           clauseRefs: ["Art. 10"],                           riskLevel: "high" },
    { controlRef: "EUAI-DOC-001",    title: "Annex IV technical documentation pack",                 description: "Versioned, change-tracked Annex IV technical-documentation bundle covering system description, risk management, performance metrics, changes through lifecycle, harmonised standards, EU declaration of conformity and post-market plan. Maintained up to date.",                  category: "ai-system-governance",     evidenceTypes: ["report","configuration","attestation"],              clauseRefs: ["Art. 11","Annex IV"],                riskLevel: "high" },
    { controlRef: "EUAI-LOG-001",    title: "Automated event logging",                               description: "Tamper-evident automatic logging of inputs, decisions, model identifier and model version. Logs retained for at least six months unless a longer retention is required, integrated with the platform's hash-chained audit trail.",                                                  category: "logging-monitoring",       evidenceTypes: ["log","log","configuration"],          clauseRefs: ["Art. 12","Art. 19"],                 riskLevel: "high" },
    { controlRef: "EUAI-TRANS-001",  title: "Deployer-facing transparency information",              description: "Instructions for use covering intended purpose, level of accuracy/robustness/cybersecurity, foreseeable risks, performance metrics, validation/test data characteristics, and human-oversight measures. Provided in a digital format that survives downstream redistribution.",     category: "ai-system-governance",     evidenceTypes: ["policy","procedure","report"],                       clauseRefs: ["Art. 13"],                           riskLevel: "high" },
    { controlRef: "EUAI-HO-001",     title: "Effective human oversight",                             description: "Named oversight role with the competence, authority and tooling to intervene, interrupt or override the AI system's output. Includes a documented escalation path and a 'stop' control.",                                                                                          category: "ai-system-governance",     evidenceTypes: ["policy","procedure","training_record","screenshot"], clauseRefs: ["Art. 14"],                           riskLevel: "high" },
    { controlRef: "EUAI-AR-001",     title: "Accuracy, robustness and cybersecurity metrics",        description: "Pre-release evaluation of accuracy / robustness / cybersecurity against declared thresholds. Adversarial-robustness testing for systems exposed to untrusted input. Metrics published in the instructions for use.",                                                              category: "ai-system-governance",     evidenceTypes: ["report","configuration","report"],               clauseRefs: ["Art. 15"],                           riskLevel: "high" },
    { controlRef: "EUAI-QMS-001",    title: "AI quality management system",                          description: "Documented QMS covering design, development, testing, deployment and post-market processes for high-risk AI systems. Compatible with ISO/IEC 42001 AIMS so the same QMS satisfies both regimes.",                                                                            category: "ai-system-governance",     evidenceTypes: ["policy","procedure","attestation","report"],         clauseRefs: ["Art. 17"],                           riskLevel: "high" },
    { controlRef: "EUAI-RET-001",    title: "10-year documentation retention",                       description: "Retention of technical documentation, QMS documentation, notified-body change approvals (where applicable) and EU declaration of conformity for at least 10 years after the system is placed on the market or put into service.",                                              category: "data-protection",          evidenceTypes: ["policy","attestation","configuration"],              clauseRefs: ["Art. 18"],                           riskLevel: "high" },
    { controlRef: "EUAI-DEP-001",    title: "Deployer obligation compliance",                        description: "For each deployed high-risk AI system: human-oversight assignment with documented competence, input-data appropriateness checks, monitoring of operation against instructions for use, log retention, and worker/affected-person notification.",                              category: "ai-system-governance",     evidenceTypes: ["policy","procedure","training_record","log"],        clauseRefs: ["Art. 26"],                           riskLevel: "high" },
    { controlRef: "EUAI-FRIA-001",   title: "Fundamental Rights Impact Assessment",                  description: "Pre-deployment FRIA covering processes in which the high-risk AI system will be used, time period of use, categories of natural persons likely to be affected, specific risks of harm likely to impact those persons, human-oversight measures, and risk-mitigation steps.",   category: "ai-system-governance",     evidenceTypes: ["fria","report","attestation"],                       clauseRefs: ["Art. 27"],                           riskLevel: "high" },
    { controlRef: "EUAI-TR-001",     title: "Limited-risk transparency disclosure",                  description: "Front-of-experience disclosure for AI systems interacting directly with natural persons. Deep-fake content carries a machine-readable label disclosing artificial generation/manipulation.",                                                                              category: "ai-system-governance",     evidenceTypes: ["screenshot","configuration","procedure"],            clauseRefs: ["Art. 50"],                           riskLevel: "limited" },
    { controlRef: "EUAI-GPAI-001",   title: "GPAI provider documentation pack",                      description: "For every GPAI model placed on the EU market: model technical documentation, downstream-integrator documentation, EU copyright-compliance policy and a publicly-available training-content summary.",                                                                  category: "ai-system-governance",     evidenceTypes: ["report","report","policy","configuration"],      clauseRefs: ["Art. 53"],                           riskLevel: "high" },
    { controlRef: "EUAI-GPAI-002",   title: "GPAI systemic-risk evaluation and incident reporting",  description: "For GPAI models classified as systemic-risk: model evaluation including adversarial testing, systemic-risk assessment + mitigation plan, tracking and prompt reporting of serious incidents, and cybersecurity protection of model + infrastructure.",                category: "ai-system-governance",     evidenceTypes: ["report","report","incident_record"],             clauseRefs: ["Art. 55"],                           riskLevel: "high" },
    { controlRef: "EUAI-PMM-001",    title: "Post-market monitoring system",                         description: "Active, systematic collection of performance and incident signals across the deployed fleet. Drives the iterative risk-management cycle in EUAI-RM-001. Documented in the QMS.",                                                                                          category: "ai-system-governance",     evidenceTypes: ["procedure","report","log","report"],              clauseRefs: ["Art. 72"],                           riskLevel: "high" },
    { controlRef: "EUAI-INC-001",    title: "Serious-incident reporting (15-day window)",            description: "Serious-incident notification to the market-surveillance authorities of the affected Member States within 15 days of provider/deployer becoming aware of the incident — immediately upon establishing a causal link or reasonable likelihood of one.",                  category: "incident-response",        evidenceTypes: ["incident_record","report","attestation"],            clauseRefs: ["Art. 73"],                           riskLevel: "high" },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "EUAI-Q-001", text: "Does the system meet the Art. 3(1) AI-system definition (machine-based, varying levels of autonomy, infers from input how to generate outputs that can influence physical or virtual environments)?", category: "applicability",       riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "EUAI-Q-002", text: "Are you a provider, deployer, importer, distributor, or authorised representative as defined in Art. 3?",                                                                                                  category: "applicability",       riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "EUAI-Q-003", text: "Will the AI system be placed on the EU market, put into service in the EU, or its output used in the EU?",                                                                                                category: "applicability",       riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "EUAI-Q-004", text: "Does the system use any of the Art. 5 prohibited practices (subliminal, vulnerability exploitation, social scoring, predictive policing-by-profiling, facial scraping, workplace/educational emotion inference, biometric categorisation by sensitive attributes)?", category: "prohibited",          riskWeight: 1.0, clauseRefs: ["Art. 5(1)(a)","Art. 5(1)(b)","Art. 5(1)(c)","Art. 5(1)(d)","Art. 5(1)(e)","Art. 5(1)(f)","Art. 5(1)(g)"] },
    { questionRef: "EUAI-Q-005", text: "Is the system intended as a safety component of a product covered by Annex I AND subject to third-party conformity assessment?",                                                                          category: "high-risk-class",     riskWeight: 0.9, clauseRefs: ["Art. 6"] },
    { questionRef: "EUAI-Q-006", text: "Does the use case fall within any of the eight Annex III categories (biometrics; critical infrastructure; education; employment; essential services; law enforcement; migration/asylum/border; justice/democratic process)?",                                                category: "high-risk-class",     riskWeight: 0.9, clauseRefs: ["Annex III"] },
    { questionRef: "EUAI-Q-007", text: "Does the system fall under any Art. 6(3) carve-out (narrow procedural task; improving a previously completed human activity; detecting decision-making patterns; preparatory task)?",                       category: "high-risk-class",     riskWeight: 0.8, clauseRefs: ["Art. 6"] },
    { questionRef: "EUAI-Q-008", text: "Is a continuous risk-management system established and documented (Art. 9)?",                                                                                                                                category: "risk-management",     riskWeight: 0.8, clauseRefs: ["Art. 9"] },
    { questionRef: "EUAI-Q-009", text: "Are training/validation/test data sets governed for representativeness, relevance, bias and completeness (Art. 10)?",                                                                                       category: "data-governance",     riskWeight: 0.8, clauseRefs: ["Art. 10"] },
    { questionRef: "EUAI-Q-010", text: "Is Annex IV technical documentation drawn up and maintained (Art. 11)?",                                                                                                                                     category: "documentation",       riskWeight: 0.8, clauseRefs: ["Art. 11","Annex IV"] },
    { questionRef: "EUAI-Q-011", text: "Do automatic logs cover the lifecycle of the system and are they retained for at least six months (Art. 12 + Art. 19)?",                                                                                    category: "logging",             riskWeight: 0.7, clauseRefs: ["Art. 12","Art. 19"] },
    { questionRef: "EUAI-Q-012", text: "Are instructions for use sufficient for deployers to interpret and use the output appropriately (Art. 13)?",                                                                                                category: "transparency",        riskWeight: 0.7, clauseRefs: ["Art. 13"] },
    { questionRef: "EUAI-Q-013", text: "Is human oversight assigned to a competent person with the authority and tooling to intervene/interrupt (Art. 14)?",                                                                                        category: "human-oversight",     riskWeight: 0.8, clauseRefs: ["Art. 14"] },
    { questionRef: "EUAI-Q-014", text: "Are accuracy, robustness and cybersecurity metrics declared, tested, and aligned with the intended purpose (Art. 15)?",                                                                                     category: "accuracy-robustness", riskWeight: 0.8, clauseRefs: ["Art. 15"] },
    { questionRef: "EUAI-Q-015", text: "Is a quality management system established and documented for the high-risk AI system (Art. 17)?",                                                                                                          category: "qms",                 riskWeight: 0.7, clauseRefs: ["Art. 17"] },
    { questionRef: "EUAI-Q-016", text: "Is required documentation retained for 10 years (Art. 18)?",                                                                                                                                                 category: "documentation",       riskWeight: 0.6, clauseRefs: ["Art. 18"] },
    { questionRef: "EUAI-Q-017", text: "Are deployer obligations (input data, oversight competence, log retention, worker notification) satisfied (Art. 26)?",                                                                                       category: "deployer",            riskWeight: 0.7, clauseRefs: ["Art. 26"] },
    { questionRef: "EUAI-Q-018", text: "Is a Fundamental Rights Impact Assessment (FRIA) completed pre-deployment for Art. 27-scoped systems?",                                                                                                      category: "fria",                riskWeight: 0.8, clauseRefs: ["Art. 27"] },
    { questionRef: "EUAI-Q-019", text: "If the system interacts with natural persons or produces deep-fake content, is the required disclosure displayed (Art. 50)?",                                                                                category: "transparency",        riskWeight: 0.6, clauseRefs: ["Art. 50"] },
    { questionRef: "EUAI-Q-020", text: "If you provide a general-purpose AI model, is the Art. 53 documentation pack (model technical doc, downstream-integrator info, EU copyright policy, training-content summary) maintained?",                  category: "gpai",                riskWeight: 0.8, clauseRefs: ["Art. 53"] },
    { questionRef: "EUAI-Q-021", text: "If your GPAI model is classified as systemic-risk, are Art. 55 obligations (adversarial evaluation, systemic-risk mitigation, serious-incident reporting, cybersecurity) satisfied?",                       category: "gpai-systemic",       riskWeight: 0.9, clauseRefs: ["Art. 55"] },
    { questionRef: "EUAI-Q-022", text: "Is a post-market monitoring system established (Art. 72) and feeding back into the Art. 9 risk-management cycle?",                                                                                          category: "post-market",         riskWeight: 0.7, clauseRefs: ["Art. 72"] },
    { questionRef: "EUAI-Q-023", text: "Is a serious-incident reporting procedure with a 15-day notification window to the market-surveillance authority operational (Art. 73)?",                                                                    category: "incident",            riskWeight: 0.8, clauseRefs: ["Art. 73"] },
    { questionRef: "EUAI-Q-024", text: "Is AI literacy training in place for staff and other persons dealing with the operation and use of AI systems on your behalf (Art. 4)?",                                                                     category: "ai-literacy",         riskWeight: 0.5, clauseRefs: ["Art. 4"] },
  ],
};
