import type { Framework } from "@regunav/types";

/**
 * EU CRA — Regulation (EU) 2024/2847 of the European Parliament and of
 * the Council of 23 October 2024 on horizontal cybersecurity requirements
 * for products with digital elements.
 *
 * Source: https://eur-lex.europa.eu/eli/reg/2024/2847/oj
 *
 * Key dates (encoded in the rule-pack manifest at
 * packages/frameworks/manifests/eu-cra.manifest.json):
 *   2024-10-23 — adopted
 *   2024-12-10 — in force
 *   2026-09-11 — vulnerability + serious-incident reporting obligations
 *                (Art. 14) start applying (21 months after entry into force)
 *   2027-12-11 — general applicability of the remaining provisions
 *                (36 months after entry into force)
 *
 * Clauses, controls and questions below cite the published text. They are
 * structural references to the regulation, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const EU_CRA: Framework = {
  schemaVersion: 1,
  code: "EU_CRA",
  name: "EU Cyber Resilience Act",
  version: "2024",
  description:
    "EU horizontal cybersecurity regulation for products with digital elements (hardware + software that can be connected to a device or network). Establishes essential cybersecurity requirements (Annex I), vulnerability handling obligations, conformity-assessment procedures (Annex VIII), CE marking, and 24-hour / 72-hour / 14-day vulnerability + incident reporting. Applies to manufacturers + importers + distributors placing products with digital elements on the EU market. Special categories: important products with digital elements (Annex III) and critical products with digital elements (Annex IV) require stricter conformity assessment routes.",
  jurisdiction: ["EU", "EEA"],
  referenceUrl: "https://eur-lex.europa.eu/eli/reg/2024/2847/oj",

  // ─── Clauses (18 of the most-cited Articles + 3 Annexes) ─────────────────
  clauses: [
    { clauseRef: "Art. 1",   title: "Subject matter",                                                       description: "This Regulation lays down rules for the placing on the market of products with digital elements to ensure their cybersecurity, essential requirements for the design/development/production of products with digital elements, essential requirements for vulnerability-handling processes, and rules on market surveillance + enforcement.", mandatory: true },
    { clauseRef: "Art. 2",   title: "Scope",                                                                 description: "Applies to products with digital elements made available on the Union market the intended purpose or reasonably foreseeable use of which includes a direct or indirect data connection to a device or network. Exclusions: products covered by specific EU regulation (medical devices under MDR/IVDR, motor vehicles, civil aviation, certain marine equipment, certifications under defence + national security).", mandatory: true },
    { clauseRef: "Art. 3",   title: "Definitions",                                                            description: "Defines 'product with digital elements', 'remote data processing solution', 'critical product with digital elements', 'important product with digital elements', 'cybersecurity risk', 'significant cybersecurity risk', 'actively exploited vulnerability', 'manufacturer', 'importer', 'distributor', 'placing on the market', 'making available on the market', 'support period'.", mandatory: true },
    { clauseRef: "Art. 6",   title: "Important products with digital elements",                              description: "Important products with digital elements (Annex III) — class I (e.g. identity-management systems, password managers, smart-home with security functions, network management systems) and class II (e.g. hypervisors + container runtimes, firewalls, tamper-resistant microprocessors). Subject to stricter conformity-assessment routes than ordinary products.", mandatory: true },
    { clauseRef: "Art. 7",   title: "Critical products with digital elements",                                description: "Critical products with digital elements (Annex IV) — products that warrant the highest level of cybersecurity scrutiny (e.g. hardware devices with security boxes, smart meter gateways, smartcards or similar). Mandatory European cybersecurity certification by an accredited conformity-assessment body.", mandatory: true },
    { clauseRef: "Art. 13",  title: "Obligations of manufacturers",                                           description: "Manufacturers shall ensure that products with digital elements placed on the market have been designed/developed/produced in accordance with the essential cybersecurity requirements set out in Annex I. They shall perform a cybersecurity risk assessment; address all categories of risk; provide a support period (≥5 years by default, or the lifecycle if shorter); maintain technical documentation; and undergo conformity assessment.", mandatory: true },
    { clauseRef: "Art. 14",  title: "Reporting obligations of manufacturers",                                 description: "Manufacturers shall notify ENISA + the relevant CSIRT designated under NIS2 of any actively exploited vulnerability contained in the product with digital elements that they become aware of, and any severe incident having impact on the security of the product. Cadence: 24-hour early warning, 72-hour incident notification, 14-day final report.", mandatory: true },
    { clauseRef: "Art. 19",  title: "Obligations of importers",                                                description: "Importers shall place on the Union market only products with digital elements that comply with the essential requirements. They shall verify that the manufacturer has carried out the conformity-assessment procedure, drawn up the technical documentation, affixed the CE marking, and complied with documentation + reporting obligations.", mandatory: true },
    { clauseRef: "Art. 20",  title: "Obligations of distributors",                                            description: "Distributors shall act with due care in relation to the requirements of this Regulation. Before making a product with digital elements available on the market, they shall verify the CE marking, the documentation, the instructions and information for the user are accessible, and the manufacturer + importer have complied with their respective obligations.", mandatory: true },
    { clauseRef: "Art. 21",  title: "Cases in which obligations of manufacturers apply to importers and distributors", description: "An importer or distributor shall be considered a manufacturer for the purposes of this Regulation and shall be subject to the obligations of the manufacturer where they place a product with digital elements on the market under their own name or trademark, or carry out a substantial modification of the product with digital elements.", mandatory: true },
    { clauseRef: "Art. 27",  title: "Presumption of conformity",                                              description: "Products with digital elements that are in conformity with harmonised standards or parts thereof, the references of which have been published in the Official Journal of the European Union, shall be presumed to be in conformity with the essential requirements covered by those standards or parts thereof.", mandatory: true },
    { clauseRef: "Art. 28",  title: "European cybersecurity certification schemes",                            description: "Member States shall presume conformity with the essential requirements where a European cybersecurity certification scheme adopted pursuant to the Cybersecurity Act and applicable to the product covers those requirements at an assurance level corresponding to the relevant risks.", mandatory: true },
    { clauseRef: "Art. 31",  title: "Conformity assessment procedures",                                        description: "Manufacturers shall demonstrate conformity with the essential requirements by carrying out an appropriate conformity-assessment procedure set out in Annex VIII (module A internal control, module B+C type-examination + conformity-to-type, module H full quality assurance, full-quality-assurance procedure for important class II, mandatory European cybersecurity certification for critical products).", mandatory: true },
    { clauseRef: "Art. 32",  title: "EU declaration of conformity",                                            description: "The EU declaration of conformity shall state that the fulfilment of the essential cybersecurity requirements has been demonstrated. It shall be drawn up in accordance with the model set out in Annex V and shall be translated into the language or languages required by the Member State in which the product is placed on the market.", mandatory: true },
    { clauseRef: "Art. 30",  title: "CE marking",                                                              description: "Products with digital elements that comply with this Regulation shall bear the CE marking before being placed on the market. The CE marking shall be affixed visibly, legibly and indelibly to the product. Where this is not possible or warranted because of the nature of the product, it shall be affixed to the packaging and to the documents accompanying the product.", mandatory: true },
    { clauseRef: "Annex I",  title: "Essential cybersecurity requirements",                                    description: "Section 1 — Security properties of products with digital elements: appropriate level of cybersecurity, no known exploitable vulnerabilities, secure default configuration, security updates, protection from unauthorised access (e.g. authentication + identity + access management), confidentiality + integrity + availability of stored/transmitted/processed data, processing only of minimum amount of data, resilience against DoS, minimised attack surface, vulnerability detection + mitigation. Section 2 — Vulnerability handling requirements: identify + document, address + remediate, regular tests + reviews, public information, policy on coordinated vulnerability disclosure, mechanism to securely distribute updates.", mandatory: true },
    { clauseRef: "Annex II", title: "Information and instructions to the user",                                description: "Information that manufacturers must provide with the product: identity + contact details of the manufacturer, name/type/identification of the product, intended purpose, type of data the product is designed to process, support period during which security updates will be provided, technical security characteristics, instructions on how to make secure use of the product, automatic security-update mechanism + how to disable, point of contact to report vulnerabilities.", mandatory: true },
    { clauseRef: "Annex IV", title: "Technical documentation",                                                 description: "Required content for the technical documentation: general description (intended purpose, software versions, hardware specifications), description of the design + development + production of the product, assessment of the cybersecurity risks against which the product is designed + developed + produced, list of applied harmonised standards, copy of the EU declaration of conformity, security-update policy, support-period definition + rationale.", mandatory: true },
  ],

  // ─── Controls (13 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "CRA-RM-001",       title: "Cybersecurity risk assessment for the product",          description: "Documented cybersecurity risk assessment carried out before placing the product on the market. Assessment shall identify all categories of risk, the intended purpose + reasonably foreseeable use, the support period, and the relevant essential requirements. Maps Art. 13 + Annex I Section 1.",                                                                                category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Art. 13"],                            riskLevel: "high"   },
    { controlRef: "CRA-DD-001",       title: "Secure design + development + production",                description: "Engineering practices that satisfy Annex I Section 1 security properties: appropriate level of cybersecurity, no known exploitable vulns at release, secure-by-default configuration, IAM, confidentiality + integrity + availability, data minimisation, DoS resilience, minimised attack surface. Maps Annex I Section 1.",                                                category: "change-management",   evidenceTypes: ["procedure","configuration","report","attestation"],   clauseRefs: ["Annex I"],                            riskLevel: "high"   },
    { controlRef: "CRA-VH-001",       title: "Vulnerability handling process",                         description: "Vulnerability identification + documentation, remediation procedures, regular testing + reviews, coordinated-disclosure policy, secure update distribution. Maps Annex I Section 2.",                                                                                                                                                                                              category: "vulnerability-management", evidenceTypes: ["policy","procedure","report","attestation"],       clauseRefs: ["Annex I"],                            riskLevel: "high"   },
    { controlRef: "CRA-UPD-001",      title: "Security update distribution + support period",          description: "Mechanism to securely distribute security updates throughout the support period (≥5 years by default, or product lifecycle if shorter); automatic-update default + opt-out; documented support-period rationale. Maps Art. 13 + Annex I Section 2.",                                                                                                                            category: "change-management",   evidenceTypes: ["configuration","procedure","report","attestation"],   clauseRefs: ["Art. 13","Annex I"],                  riskLevel: "high"   },
    { controlRef: "CRA-REP-001",      title: "Vulnerability + serious-incident reporting (24h/72h/14d)", description: "Workflow that delivers an early warning to ENISA + relevant CSIRT within 24 hours of awareness of an actively exploited vulnerability or severe incident, an incident notification within 72 hours, and a final report within 14 days. Tracks vulnerability identifier + CVE + affected versions + mitigation. Maps Art. 14.",                                                category: "incident-response",   evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 14"],                            riskLevel: "high"   },
    { controlRef: "CRA-CONF-001",     title: "Conformity-assessment route selection",                  description: "Determination of whether the product is ordinary / important class I / important class II / critical; selection of the corresponding Annex VIII module (A internal control, B+C type-examination + conformity-to-type, H full quality assurance, mandatory European cybersecurity certification for critical). Maps Art. 6 + 7 + 31.",                                       category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Art. 6","Art. 7","Art. 31"],          riskLevel: "high"   },
    { controlRef: "CRA-DOC-001",      title: "Annex IV technical documentation pack",                  description: "Versioned + change-tracked Annex IV technical documentation: general description, design/development/production, risk assessment, harmonised standards applied, EU declaration of conformity, security-update policy, support-period rationale. Maintained up to date for at least 10 years after the product is placed on the market. Maps Art. 13 + Annex IV.",                  category: "ai-system-governance", evidenceTypes: ["report","configuration","attestation"],                clauseRefs: ["Annex IV"],                            riskLevel: "high"   },
    { controlRef: "CRA-DOC-002",      title: "EU declaration of conformity (Annex V)",                  description: "EU declaration of conformity drawn up using the Annex V template; translated into Member-State languages where required; signed by the manufacturer or authorised representative.",                                                                                                                                                                                                category: "ai-system-governance", evidenceTypes: ["attestation","report","contract"],                     clauseRefs: ["Art. 32"],                            riskLevel: "high"   },
    { controlRef: "CRA-CE-001",       title: "CE marking",                                              description: "CE marking affixed visibly + legibly + indelibly to the product (or packaging + accompanying documents where the product is too small / nature does not warrant). Marking applied only after successful conformity assessment.",                                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["screenshot","report","attestation"],                    clauseRefs: ["Art. 30"],                            riskLevel: "limited" },
    { controlRef: "CRA-INFO-001",     title: "User information + instructions (Annex II)",              description: "Documentation provided with the product covering manufacturer identity + contact, product identification, intended purpose, data types processed, support period, technical security characteristics, secure-use instructions, automatic-update mechanism + opt-out, vulnerability-reporting contact. Maps Annex II.",                                                          category: "ai-system-governance", evidenceTypes: ["screenshot","report","procedure"],                     clauseRefs: ["Annex II"],                            riskLevel: "high"   },
    { controlRef: "CRA-IMP-001",      title: "Importer + distributor due-diligence",                   description: "Where acting as importer: verify manufacturer has performed conformity assessment, drawn up technical documentation, affixed CE marking, complied with Annex II + reporting obligations. Where acting as distributor: verify CE marking, accessibility of documentation + instructions, manufacturer/importer compliance with their obligations. Maps Art. 19 + 20.",                category: "vendor-management",   evidenceTypes: ["procedure","report","attestation","contract"],         clauseRefs: ["Art. 19","Art. 20"],                  riskLevel: "high"   },
    { controlRef: "CRA-MOD-001",      title: "Substantial-modification + own-brand awareness",          description: "Process to determine whether importer/distributor activity constitutes placing under own name/trademark or substantial modification, which would trigger manufacturer obligations under Art. 21.",                                                                                                                                                                              category: "ai-system-governance", evidenceTypes: ["procedure","report","attestation"],                    clauseRefs: ["Art. 21"],                            riskLevel: "high"   },
    { controlRef: "CRA-STD-001",      title: "Use of harmonised standards + European cybersecurity certification", description: "Use of harmonised standards referenced in the OJ to claim presumption of conformity under Art. 27, OR European cybersecurity certification under Art. 28. Inventory + currency-tracking of selected standards/certifications.",                                                                                                                                                category: "ai-system-governance", evidenceTypes: ["report","configuration","attestation"],                clauseRefs: ["Art. 27","Art. 28"],                  riskLevel: "limited" },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "EU-CRA-Q-001",  text: "Is the product a 'product with digital elements' whose intended or reasonably foreseeable use includes a direct or indirect data connection to a device or network, and not excluded under Art. 2?",                                       category: "applicability",     riskWeight: 1.0, clauseRefs: ["Art. 1","Art. 2"] },
    { questionRef: "EU-CRA-Q-002",  text: "Has the product's category been determined (ordinary / important class I / important class II / critical) to select the conformity-assessment route (Art. 6, 7, 31)?",                                                                    category: "classification",    riskWeight: 1.0, clauseRefs: ["Art. 6","Art. 7","Art. 31"] },
    { questionRef: "EU-CRA-Q-003",  text: "Has a cybersecurity risk assessment been performed before the product is placed on the market, addressing all categories of risk (Art. 13)?",                                                                                              category: "risk-assessment",   riskWeight: 1.0, clauseRefs: ["Art. 13"] },
    { questionRef: "EU-CRA-Q-004",  text: "Are the Annex I Section 1 security properties (no known exploitable vulns, secure-by-default, IAM, CIA, data minimisation, DoS resilience, minimised attack surface) implemented?",                                                       category: "security-properties", riskWeight: 1.0, clauseRefs: ["Annex I"] },
    { questionRef: "EU-CRA-Q-005",  text: "Is a vulnerability-handling process in place per Annex I Section 2 (identify + document, address + remediate, regular tests, coordinated-disclosure policy, secure update distribution)?",                                                  category: "vuln-handling",     riskWeight: 1.0, clauseRefs: ["Annex I"] },
    { questionRef: "EU-CRA-Q-006",  text: "Is a security-update mechanism in place that supports the documented support period (≥5 years by default or product lifecycle if shorter) with automatic updates by default (Art. 13 + Annex I)?",                                         category: "updates",           riskWeight: 0.9, clauseRefs: ["Art. 13","Annex I"] },
    { questionRef: "EU-CRA-Q-007",  text: "Can ENISA + relevant CSIRT receive a 24h early warning, 72h incident notification, and 14-day final report for actively exploited vulnerabilities + severe incidents (Art. 14)?",                                                          category: "reporting",         riskWeight: 1.0, clauseRefs: ["Art. 14"] },
    { questionRef: "EU-CRA-Q-008",  text: "Is the Annex IV technical documentation drawn up + maintained + retained for at least 10 years after the product is placed on the market?",                                                                                                category: "documentation",     riskWeight: 0.9, clauseRefs: ["Annex IV"] },
    { questionRef: "EU-CRA-Q-009",  text: "Has the EU declaration of conformity (Annex V) been drawn up + translated into Member-State languages where required (Art. 32)?",                                                                                                          category: "declaration",       riskWeight: 0.9, clauseRefs: ["Art. 32"] },
    { questionRef: "EU-CRA-Q-010",  text: "Has the CE marking been affixed only after successful conformity assessment (Art. 30)?",                                                                                                                                                    category: "ce-marking",        riskWeight: 0.8, clauseRefs: ["Art. 30"] },
    { questionRef: "EU-CRA-Q-011",  text: "Is the Annex II user-information + instructions pack provided with the product (manufacturer contact, identity, intended purpose, support period, vulnerability-reporting contact, etc.)?",                                                category: "user-information",  riskWeight: 0.8, clauseRefs: ["Annex II"] },
    { questionRef: "EU-CRA-Q-012",  text: "Where acting as importer: have you verified manufacturer compliance (conformity assessment, technical documentation, CE marking, Art. 14 reporting) before placing the product on the market (Art. 19)?",                                  category: "importer",         riskWeight: 0.9, clauseRefs: ["Art. 19"] },
    { questionRef: "EU-CRA-Q-013",  text: "Where acting as distributor: have you verified CE marking, documentation accessibility + upstream-actor compliance before making the product available (Art. 20)?",                                                                         category: "distributor",       riskWeight: 0.8, clauseRefs: ["Art. 20"] },
    { questionRef: "EU-CRA-Q-014",  text: "Have you determined whether your activity triggers manufacturer obligations under Art. 21 (placing under own name/trademark or substantial modification)?",                                                                                  category: "own-brand",         riskWeight: 0.7, clauseRefs: ["Art. 21"] },
    { questionRef: "EU-CRA-Q-015",  text: "Where harmonised standards exist in the OJ, are you claiming presumption of conformity under Art. 27, OR using a European cybersecurity certification scheme under Art. 28?",                                                              category: "presumption",       riskWeight: 0.6, clauseRefs: ["Art. 27","Art. 28"] },
    { questionRef: "EU-CRA-Q-016",  text: "Are the staggered applicability dates (Art. 14 reporting from 2026-09-11; general applicability from 2027-12-11) reflected in your release-readiness plan?",                                                                                category: "timeline",          riskWeight: 0.5, clauseRefs: ["Art. 1"] },
  ],
};
