import type { Framework } from "@regunav/types";

/**
 * GDPR — Regulation (EU) 2016/679 of the European Parliament and of the
 * Council of 27 April 2016 on the protection of natural persons with regard
 * to the processing of personal data and on the free movement of such data,
 * and repealing Directive 95/46/EC (General Data Protection Regulation).
 *
 * Source: https://eur-lex.europa.eu/eli/reg/2016/679/oj
 *
 * Key dates (encoded in the rule-pack manifest at
 * packages/frameworks/manifests/gdpr.manifest.json):
 *   2016-04-27 — adopted
 *   2016-05-24 — in force
 *   2018-05-25 — applicable
 *
 * Clauses, controls and questions below cite the published text. They are
 * structural references to the regulation, not legal advice. See
 * `packages/ontology/LEGAL_DISCLAIMER.md`.
 */
export const GDPR: Framework = {
  schemaVersion: 1,
  code: "GDPR",
  name: "GDPR",
  version: "(EU) 2016/679",
  description:
    "EU regulation governing the processing of personal data of natural persons in the Union and the cross-border movement of such data. Applies to controllers and processors established in the EU and, under Art. 3(2), to those outside the EU that offer goods/services to or monitor data subjects in the EU. Covers principles (Art. 5), lawful basis (Art. 6+9), data-subject rights (Ch. III), controller/processor duties (Ch. IV), security (Art. 32), breach notification (Art. 33-34), DPIA (Art. 35), DPO (Art. 37-39), international transfers (Ch. V) and supervisory authority cooperation.",
  jurisdiction: ["EU", "EEA"],
  referenceUrl: "https://eur-lex.europa.eu/eli/reg/2016/679/oj",

  // ─── Clauses (28 of the most-cited Articles) ─────────────────────────────
  clauses: [
    { clauseRef: "Art. 3",   title: "Territorial scope",                                       description: "Applies to processing in the context of activities of an establishment of a controller/processor in the Union, regardless of where processing takes place. Also applies extraterritorially to controllers/processors not established in the Union where processing relates to offering goods or services to data subjects in the Union, or to monitoring their behaviour as far as it takes place within the Union.", mandatory: true },
    { clauseRef: "Art. 4",   title: "Definitions",                                             description: "Defines 'personal data', 'processing', 'controller', 'processor', 'data subject', 'consent', 'pseudonymisation', 'profiling', 'personal data breach', 'cross-border processing', 'main establishment'.", mandatory: true },
    { clauseRef: "Art. 5",   title: "Principles relating to processing of personal data",      description: "Personal data shall be processed lawfully, fairly and transparently (Art. 5(1)(a)); collected for specified, explicit and legitimate purposes (purpose limitation); be adequate, relevant and limited to what is necessary (data minimisation); accurate and kept up to date; kept in a form which permits identification of data subjects for no longer than is necessary (storage limitation); and processed in a manner ensuring appropriate security. The controller is responsible for, and able to demonstrate, compliance — Art. 5(2) accountability.", mandatory: true },
    { clauseRef: "Art. 6",   title: "Lawfulness of processing",                                description: "Processing is lawful only if and to the extent that at least one of: (a) consent of the data subject; (b) performance of a contract; (c) legal obligation; (d) vital interests; (e) public interest or official authority; (f) legitimate interests pursued by the controller or a third party, except where overridden by interests or fundamental rights and freedoms of the data subject.", mandatory: true },
    { clauseRef: "Art. 7",   title: "Conditions for consent",                                  description: "Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented. The request for consent shall be presented in an intelligible and easily accessible form, using clear and plain language, distinguishable from other matters. The data subject shall have the right to withdraw consent at any time, and withdrawal shall be as easy as giving consent.", mandatory: true },
    { clauseRef: "Art. 9",   title: "Processing of special categories of personal data",       description: "Processing of personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, trade-union membership, genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation shall be prohibited, unless one of the conditions in Art. 9(2)(a-j) applies (explicit consent, employment law obligations, vital interests, public interest, etc.).", mandatory: true },
    { clauseRef: "Art. 12",  title: "Transparent information and modalities for the exercise of rights", description: "The controller shall take appropriate measures to provide any information referred to in Articles 13 and 14 and any communication under Articles 15 to 22 and 34 in a concise, transparent, intelligible and easily accessible form, using clear and plain language. Information shall be provided in writing, or by other means, including, where appropriate, by electronic means.", mandatory: true },
    { clauseRef: "Art. 13",  title: "Information to be provided where personal data are collected from the data subject", description: "At the time when personal data are obtained, the controller shall provide the data subject with: identity and contact details, purposes and legal basis, legitimate interests, recipients or categories of recipients, transfers to third countries, retention period, data-subject rights, right to lodge a complaint, whether provision is a statutory/contractual requirement, existence of automated decision-making.", mandatory: true },
    { clauseRef: "Art. 14",  title: "Information to be provided where personal data have not been obtained from the data subject", description: "Where personal data have not been obtained from the data subject, the controller shall provide the data subject with the same information set as Art. 13 plus the categories of personal data concerned and the source of the personal data, within a reasonable period after obtaining the personal data and at the latest within one month.", mandatory: true },
    { clauseRef: "Art. 15",  title: "Right of access by the data subject",                     description: "The data subject shall have the right to obtain from the controller confirmation as to whether or not personal data concerning him or her are being processed, and, where that is the case, access to the personal data and the information set out in Art. 15(1)(a-h).", mandatory: true },
    { clauseRef: "Art. 16",  title: "Right to rectification",                                  description: "The data subject shall have the right to obtain from the controller without undue delay the rectification of inaccurate personal data concerning him or her. Taking into account the purposes of the processing, the data subject shall have the right to have incomplete personal data completed, including by means of providing a supplementary statement.", mandatory: true },
    { clauseRef: "Art. 17",  title: "Right to erasure ('right to be forgotten')",              description: "The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay where one of the grounds in Art. 17(1)(a-f) applies. Subject to the exemptions in Art. 17(3) including freedom of expression, legal obligations, public-interest archiving and legal claims.", mandatory: true },
    { clauseRef: "Art. 18",  title: "Right to restriction of processing",                      description: "The data subject shall have the right to obtain from the controller restriction of processing where one of the grounds in Art. 18(1)(a-d) applies, including contesting accuracy, unlawful processing, the controller no longer needing the data but the data subject needing it for legal claims, or pending verification of a Art. 21(1) objection.", mandatory: true },
    { clauseRef: "Art. 20",  title: "Right to data portability",                               description: "The data subject shall have the right to receive the personal data concerning him or her, which he or she has provided to a controller, in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller, where the processing is based on consent or on a contract and is carried out by automated means.", mandatory: true },
    { clauseRef: "Art. 21",  title: "Right to object",                                         description: "The data subject shall have the right to object, on grounds relating to his or her particular situation, at any time to processing of personal data concerning him or her which is based on Art. 6(1)(e) or (f) including profiling based on those provisions.", mandatory: true },
    { clauseRef: "Art. 22",  title: "Automated individual decision-making, including profiling", description: "The data subject shall have the right not to be subject to a decision based solely on automated processing, including profiling, which produces legal effects concerning him or her or similarly significantly affects him or her, subject to the carve-outs in Art. 22(2).", mandatory: true },
    { clauseRef: "Art. 25",  title: "Data protection by design and by default",                description: "Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing, the controller shall, both at the time of the determination of the means for processing and at the time of the processing itself, implement appropriate technical and organisational measures designed to implement data-protection principles, such as data minimisation, in an effective manner.", mandatory: true },
    { clauseRef: "Art. 28",  title: "Processor",                                               description: "Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures. Processing by a processor shall be governed by a contract or other legal act binding the processor to the controller and stipulating the matters in Art. 28(3)(a-h).", mandatory: true },
    { clauseRef: "Art. 30",  title: "Records of processing activities",                        description: "Each controller and processor shall maintain a record of processing activities under its responsibility, with the content set out in Art. 30(1) (controllers) and Art. 30(2) (processors). The obligation does not apply to an enterprise or organisation employing fewer than 250 persons unless the processing is likely to result in a risk to data subjects, is not occasional, or includes special categories of data or criminal-conviction data.", mandatory: true },
    { clauseRef: "Art. 32",  title: "Security of processing",                                  description: "Taking into account the state of the art, the costs of implementation, the nature/scope/context/purposes of processing and the risks, the controller and processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including: (a) the pseudonymisation and encryption of personal data; (b) the ability to ensure ongoing confidentiality, integrity, availability and resilience; (c) restoration of availability and access in a timely manner; (d) regular testing/assessing/evaluating of effectiveness.", mandatory: true },
    { clauseRef: "Art. 33",  title: "Notification of a personal data breach to the supervisory authority", description: "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons.", mandatory: true },
    { clauseRef: "Art. 34",  title: "Communication of a personal data breach to the data subject", description: "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay.", mandatory: true },
    { clauseRef: "Art. 35",  title: "Data protection impact assessment (DPIA)",                description: "Where a type of processing in particular using new technologies, and taking into account the nature/scope/context/purposes, is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to the processing, carry out an assessment of the impact of the envisaged processing operations on the protection of personal data.", mandatory: true },
    { clauseRef: "Art. 37",  title: "Designation of the data protection officer (DPO)",        description: "The controller and the processor shall designate a DPO where: (a) the processing is carried out by a public authority or body; (b) the core activities consist of processing operations which require regular and systematic monitoring of data subjects on a large scale; or (c) the core activities consist of processing on a large scale of special categories of data referred to in Art. 9 or of personal data relating to criminal convictions and offences.", mandatory: true },
    { clauseRef: "Art. 44",  title: "General principle for transfers",                         description: "Any transfer of personal data which are undergoing processing or are intended for processing after transfer to a third country or to an international organisation shall take place only if, subject to the other provisions of this Regulation, the conditions laid down in Chapter V are complied with by the controller and processor.", mandatory: true },
    { clauseRef: "Art. 46",  title: "Transfers subject to appropriate safeguards",             description: "In the absence of an adequacy decision pursuant to Art. 45(3), a controller or processor may transfer personal data to a third country or an international organisation only if the controller or processor has provided appropriate safeguards, and on condition that enforceable data-subject rights and effective legal remedies for data subjects are available.", mandatory: true },
    { clauseRef: "Art. 82",  title: "Right to compensation and liability",                     description: "Any person who has suffered material or non-material damage as a result of an infringement of this Regulation shall have the right to receive compensation from the controller or processor for the damage suffered.", mandatory: true },
    { clauseRef: "Art. 83",  title: "General conditions for imposing administrative fines",    description: "Infringements of this Regulation shall, in accordance with paragraph 2, be subject to administrative fines up to 20 000 000 EUR, or in the case of an undertaking, up to 4% of the total worldwide annual turnover of the preceding financial year, whichever is higher.", mandatory: true },
  ],

  // ─── Controls (15 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "GDPR-PRIN-001",  title: "Article 5 principles implementation",         description: "Documented mapping of every processing purpose to the six Article 5(1) principles (lawfulness/fairness/transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity/confidentiality) plus the Art. 5(2) accountability evidence trail.", category: "data-protection",       evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["Art. 5"],                              riskLevel: "high"   },
    { controlRef: "GDPR-LB-001",    title: "Lawful basis register",                       description: "For every processing operation: declared Art. 6 lawful basis (and Art. 9 condition where special-category data is involved), legitimate-interest balancing test where applicable, and the published basis in privacy notices.", category: "data-protection",       evidenceTypes: ["report","configuration","attestation","procedure"], clauseRefs: ["Art. 6","Art. 9"],                     riskLevel: "high"   },
    { controlRef: "GDPR-CONS-001",  title: "Consent management",                          description: "Granular, freely-given, specific, informed and unambiguous consent capture, with timestamped evidence of consent + the matching purpose, an easy withdrawal mechanism, and re-consent on material purpose change.", category: "data-protection",       evidenceTypes: ["log","screenshot","procedure","configuration"],    clauseRefs: ["Art. 7"],                              riskLevel: "high"   },
    { controlRef: "GDPR-NOTICE-001",title: "Art. 13/14 privacy notices",                  description: "Layered privacy notices covering identity/contact, purposes/legal bases, recipients, transfers, retention, data-subject rights, right to complain, automated decision-making. Versioned with effective-date and change history.", category: "data-protection",       evidenceTypes: ["policy","screenshot","report"],                     clauseRefs: ["Art. 12","Art. 13","Art. 14"],         riskLevel: "high"   },
    { controlRef: "GDPR-DSR-001",   title: "Data-subject-rights handling (access/rectify/erase/restrict/portability/object)", description: "Documented intake → identity-verification → fulfilment workflow for every Art. 15-22 right, hitting the one-month statutory deadline (extendable to three months for complex requests) with full audit trail.", category: "data-protection",       evidenceTypes: ["procedure","log","attestation","report"],            clauseRefs: ["Art. 12","Art. 15","Art. 16","Art. 17","Art. 18","Art. 20","Art. 21"], riskLevel: "high"   },
    { controlRef: "GDPR-ADM-001",   title: "Automated decision-making oversight (Art. 22)", description: "Inventory of automated decisions with legal/significant effect, the Art. 22(2) carve-out claimed, human-intervention pathway, contestability mechanism, and DPIA where high-risk.", category: "ai-system-governance",  evidenceTypes: ["procedure","report","configuration","fria"],        clauseRefs: ["Art. 22"],                             riskLevel: "high"   },
    { controlRef: "GDPR-PBD-001",   title: "Data protection by design and by default",    description: "Engineering checklists at design time: data minimisation, pseudonymisation/encryption defaults, least-privilege access, retention defaults, threat-model coverage. Captured as a stage in the SDLC.", category: "data-protection",       evidenceTypes: ["policy","procedure","configuration","report"],      clauseRefs: ["Art. 25"],                             riskLevel: "high"   },
    { controlRef: "GDPR-PROC-001",  title: "Processor contracts (Art. 28 DPA)",           description: "Signed Article 28-compliant DPA with every processor, covering all eight mandatory matters in Art. 28(3)(a-h), sub-processor approval, audit rights, breach-notification window, and termination-data-handling.", category: "vendor-management",     evidenceTypes: ["contract","attestation","report"],                  clauseRefs: ["Art. 28"],                             riskLevel: "high"   },
    { controlRef: "GDPR-ROP-001",   title: "Records of processing (Art. 30)",             description: "Per-controller and per-processor records covering every processing activity with the Art. 30(1)/(2) mandatory content, reviewed at least annually and on material change.", category: "data-protection",       evidenceTypes: ["report","configuration","attestation"],             clauseRefs: ["Art. 30"],                             riskLevel: "high"   },
    { controlRef: "GDPR-SEC-001",   title: "Security of processing (Art. 32)",            description: "Appropriate technical and organisational measures: encryption at rest and in transit, pseudonymisation where feasible, access control, CIA assurance, restoration capability, regular testing. Tied to ISO 27001 A.5-A.8 controls.", category: "encryption",            evidenceTypes: ["configuration","log","report","attestation"],       clauseRefs: ["Art. 32"],                             riskLevel: "high"   },
    { controlRef: "GDPR-BREACH-001",title: "Breach detection + 72-hour notification",     description: "Detection capability tied to incident-response runbook, severity classification, controller-to-supervisory-authority notification within 72 hours (or justified delay), notification to affected data subjects when high-risk, and post-incident review.", category: "incident-response",     evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 33","Art. 34"],                   riskLevel: "high"   },
    { controlRef: "GDPR-DPIA-001",  title: "Data Protection Impact Assessment (Art. 35)", description: "DPIA performed before processing likely to result in high risk, covering: systematic description; necessity and proportionality assessment; assessment of risks to data subjects; measures to address risks. Consultation with DPO recorded; consultation with supervisory authority where residual risk remains high.", category: "data-protection",       evidenceTypes: ["dpia","report","attestation","procedure"],          clauseRefs: ["Art. 35"],                             riskLevel: "high"   },
    { controlRef: "GDPR-DPO-001",   title: "DPO designation + independence",              description: "DPO designated and contact details published where Art. 37 triggers apply. DPO independent, not penalised for performing tasks, reports to highest management level, has appropriate resources and access.", category: "ai-system-governance",  evidenceTypes: ["attestation","report","policy"],                    clauseRefs: ["Art. 37"],                             riskLevel: "high"   },
    { controlRef: "GDPR-XBORDER-001",title: "International-transfer safeguards",          description: "For every transfer outside the EEA without an adequacy decision: documented Art. 46 safeguard (SCCs, BCRs, certification), transfer-impact assessment for the third-country regime, supplementary measures where the importer cannot guarantee equivalent protection.", category: "data-protection",       evidenceTypes: ["contract","report","attestation","configuration"],  clauseRefs: ["Art. 44","Art. 46"],                   riskLevel: "high"   },
    { controlRef: "GDPR-ACC-001",   title: "Accountability evidence trail (Art. 5(2))",   description: "Centralised evidence inventory that demonstrates compliance with each principle, control and right: training records, policies, attestations, audit reports, DPIA outcomes. Refreshed on cadence and on material change.", category: "data-protection",       evidenceTypes: ["report","attestation","training_record","procedure"], clauseRefs: ["Art. 5"],                              riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "GDPR-Q-001", text: "Is the organisation established in the EU, or does it offer goods/services to or monitor behaviour of data subjects in the Union (Art. 3)?",                                                category: "applicability",      riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "GDPR-Q-002", text: "Have you mapped every processing activity to one of the Article 6 lawful bases (and Art. 9 condition where special-category data is involved)?",                                              category: "lawful-basis",       riskWeight: 1.0, clauseRefs: ["Art. 6","Art. 9"] },
    { questionRef: "GDPR-Q-003", text: "Where consent is the basis, is it freely-given, specific, informed and unambiguous, with a withdrawal mechanism as easy as giving consent (Art. 7)?",                                          category: "consent",            riskWeight: 0.9, clauseRefs: ["Art. 7"] },
    { questionRef: "GDPR-Q-004", text: "Do your privacy notices satisfy Art. 13 / 14 in concise, transparent, intelligible and easily accessible language?",                                                                          category: "transparency",       riskWeight: 0.8, clauseRefs: ["Art. 12","Art. 13","Art. 14"] },
    { questionRef: "GDPR-Q-005", text: "Can you action data-subject access (Art. 15), rectification (Art. 16), erasure (Art. 17), restriction (Art. 18), portability (Art. 20) and objection (Art. 21) within one month?",            category: "rights",             riskWeight: 1.0, clauseRefs: ["Art. 15","Art. 16","Art. 17","Art. 18","Art. 20","Art. 21"] },
    { questionRef: "GDPR-Q-006", text: "Do you use automated decisions producing legal or significant effects? If so, is the Art. 22(2) basis declared and human-intervention available?",                                            category: "automated-decisions", riskWeight: 0.9, clauseRefs: ["Art. 22"] },
    { questionRef: "GDPR-Q-007", text: "Are data-protection-by-design and by-default principles applied at design time (data minimisation, encryption defaults, retention defaults) per Art. 25?",                                    category: "by-design",          riskWeight: 0.8, clauseRefs: ["Art. 25"] },
    { questionRef: "GDPR-Q-008", text: "Do all processors have an Art. 28-compliant DPA covering all eight mandatory matters in Art. 28(3)?",                                                                                          category: "processor",          riskWeight: 0.9, clauseRefs: ["Art. 28"] },
    { questionRef: "GDPR-Q-009", text: "Are Records of Processing Activities (RoPA) maintained for every processing activity, refreshed on material change (Art. 30)?",                                                                category: "rop",                riskWeight: 0.8, clauseRefs: ["Art. 30"] },
    { questionRef: "GDPR-Q-010", text: "Are Art. 32 technical and organisational measures (encryption, pseudonymisation where feasible, CIA assurance, restoration capability, regular testing) in place and tested?",                category: "security",           riskWeight: 0.9, clauseRefs: ["Art. 32"] },
    { questionRef: "GDPR-Q-011", text: "Can a personal data breach be notified to the supervisory authority within 72 hours of becoming aware (Art. 33)?",                                                                            category: "breach",             riskWeight: 1.0, clauseRefs: ["Art. 33"] },
    { questionRef: "GDPR-Q-012", text: "Is there a mechanism to communicate breaches likely to result in high risk to the affected data subjects without undue delay (Art. 34)?",                                                     category: "breach",             riskWeight: 0.9, clauseRefs: ["Art. 34"] },
    { questionRef: "GDPR-Q-013", text: "Is a DPIA performed prior to any processing likely to result in high risk to data subjects (Art. 35)?",                                                                                        category: "dpia",               riskWeight: 0.9, clauseRefs: ["Art. 35"] },
    { questionRef: "GDPR-Q-014", text: "If your processing meets the Art. 37 triggers, is a DPO designated with the required independence, resources and access?",                                                                     category: "dpo",                riskWeight: 0.8, clauseRefs: ["Art. 37"] },
    { questionRef: "GDPR-Q-015", text: "For every transfer outside the EEA without an adequacy decision, is an Art. 46 safeguard in place with a transfer-impact assessment recorded?",                                                category: "transfers",          riskWeight: 0.9, clauseRefs: ["Art. 44","Art. 46"] },
    { questionRef: "GDPR-Q-016", text: "Is accountability evidence (policies, RoPA, DPIA outcomes, attestations) centrally inventoried so Art. 5(2) can be demonstrated on demand?",                                                  category: "accountability",     riskWeight: 0.8, clauseRefs: ["Art. 5"] },
    { questionRef: "GDPR-Q-017", text: "Is retention-period governance in place for every category of personal data, aligned with the purposes and statutory limits?",                                                                category: "retention",          riskWeight: 0.7, clauseRefs: ["Art. 5"] },
    { questionRef: "GDPR-Q-018", text: "Is staff training on GDPR responsibilities run at onboarding and at least annually, with completion records retained?",                                                                        category: "training",           riskWeight: 0.6, clauseRefs: ["Art. 5","Art. 32"] },
    { questionRef: "GDPR-Q-019", text: "Are sub-processor onboarding, change-control and audit-rights procedures defined and exercised (Art. 28)?",                                                                                    category: "processor",          riskWeight: 0.7, clauseRefs: ["Art. 28"] },
    { questionRef: "GDPR-Q-020", text: "Are the maximum fines under Art. 83 (up to €20m or 4% of global annual turnover) reflected in the risk register and reported to the executive risk committee?",                                category: "governance",         riskWeight: 0.5, clauseRefs: ["Art. 83"] },
  ],
};
