import type { Framework } from "@regunav/types";

/**
 * HIPAA — Health Insurance Portability and Accountability Act of 1996, as
 * implemented by 45 CFR Parts 160 and 164 (Privacy Rule, Security Rule,
 * Breach Notification Rule, Enforcement Rule). Includes the 2013 HITECH
 * Omnibus Final Rule amendments.
 *
 * Sources:
 *   - 45 CFR Part 160 (General Administrative Requirements + Enforcement)
 *   - 45 CFR Part 164 Subpart C (Security Rule §§ 164.302-164.318)
 *   - 45 CFR Part 164 Subpart D (Breach Notification §§ 164.400-164.414)
 *   - 45 CFR Part 164 Subpart E (Privacy Rule §§ 164.500-164.534)
 *   - HHS official guidance: https://www.hhs.gov/hipaa
 *
 * Clauses, controls and questions below cite the CFR by section number.
 * They are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const HIPAA: Framework = {
  schemaVersion: 1,
  code: "HIPAA",
  name: "HIPAA Security & Privacy",
  version: "2013 Omnibus",
  description:
    "US federal regulation governing the use and disclosure of Protected Health Information (PHI) by Covered Entities (health plans, health-care clearinghouses, providers transmitting health information electronically) and Business Associates. Privacy Rule (§§ 164.500-534) governs uses and disclosures of PHI; Security Rule (§§ 164.302-318) requires administrative, physical and technical safeguards for ePHI; Breach Notification Rule (§§ 164.400-414) requires notice to affected individuals, the HHS Secretary and (for breaches affecting ≥500 individuals) prominent media outlets.",
  jurisdiction: ["US"],
  referenceUrl: "https://www.hhs.gov/hipaa",

  // ─── Clauses (20 — Privacy + Security + Breach + Enforcement) ─────────────
  clauses: [
    { clauseRef: "§164.308",  title: "Administrative safeguards (Security Rule)",                                description: "Covered Entities and Business Associates shall implement administrative safeguards: security management process (including risk analysis and risk management), assigned security responsibility, workforce security (authorisation/clearance/termination), information access management, security awareness and training, security-incident procedures, contingency plan, evaluation, and Business Associate contracts and other arrangements.", mandatory: true },
    { clauseRef: "§164.310",  title: "Physical safeguards (Security Rule)",                                       description: "Implement physical safeguards: facility access controls (contingency operations, facility security plan, access control and validation procedures, maintenance records); workstation use; workstation security; device and media controls (disposal, media re-use, accountability, data backup and storage).", mandatory: true },
    { clauseRef: "§164.312",  title: "Technical safeguards (Security Rule)",                                      description: "Implement technical safeguards: access control (unique user identification, emergency access, automatic logoff, encryption and decryption); audit controls; integrity (mechanism to authenticate ePHI); person or entity authentication; transmission security (integrity controls, encryption).", mandatory: true },
    { clauseRef: "§164.314",  title: "Organizational requirements (BAA + group health plan)",                     description: "Business Associate contract requirements: written contract requiring the BA to comply with applicable Security Rule provisions, ensure subcontractors agree to the same restrictions, report security incidents, authorise termination if material breach is not cured. Group health plan documents must restrict plan-sponsor uses/disclosures.", mandatory: true },
    { clauseRef: "§164.316",  title: "Policies, procedures and documentation requirements",                       description: "Implement reasonable and appropriate policies and procedures; maintain written (electronic) documentation of policies/procedures/required actions/activities or assessments; retain documentation for 6 years from creation date or last effective date; periodically review and update.", mandatory: true },
    { clauseRef: "§164.402",  title: "Breach definitions (Breach Notification Rule)",                              description: "Defines 'breach' as the acquisition/access/use/disclosure of PHI in a manner not permitted under the Privacy Rule which compromises the security or privacy of the PHI. Includes the four-factor risk-assessment carve-out (nature/extent of PHI, recipient, whether actually acquired/viewed, mitigation).", mandatory: true },
    { clauseRef: "§164.404",  title: "Notification to individuals",                                                 description: "Covered Entities shall notify affected individuals without unreasonable delay and in no case later than 60 calendar days following discovery of a breach. Notification must contain description of breach, types of information involved, steps individuals should take, what the CE is doing to investigate/mitigate/protect, and contact details.", mandatory: true },
    { clauseRef: "§164.406",  title: "Notification to the media",                                                   description: "For breaches affecting more than 500 individuals in a State or jurisdiction, the Covered Entity shall notify prominent media outlets serving the State or jurisdiction without unreasonable delay and in no case later than 60 calendar days following discovery.", mandatory: true },
    { clauseRef: "§164.408",  title: "Notification to the Secretary (HHS)",                                        description: "Breaches affecting ≥500 individuals: notify the HHS Secretary without unreasonable delay and in no case later than 60 days after discovery. Breaches affecting <500 individuals: log and submit to HHS within 60 days after the end of the calendar year in which the breach was discovered.", mandatory: true },
    { clauseRef: "§164.410",  title: "Notification by a Business Associate",                                       description: "A Business Associate shall, following the discovery of a breach of unsecured PHI, notify the Covered Entity of such breach. Notice shall include the identification of each individual whose unsecured PHI has been (or is reasonably believed to have been) accessed/acquired/used/disclosed during the breach.", mandatory: true },
    { clauseRef: "§164.502",  title: "Uses and disclosures of PHI — general rules",                              description: "A Covered Entity or Business Associate may not use or disclose PHI except as permitted or required by Subpart E. The minimum-necessary standard applies when using or disclosing PHI for purposes other than treatment. Identified exceptions cover treatment/payment/health-care operations (TPO), disclosures to the individual, public-interest disclosures listed in §164.512.", mandatory: true },
    { clauseRef: "§164.506",  title: "Uses and disclosures to carry out treatment, payment or health care operations", description: "A Covered Entity may use or disclose PHI for its own treatment, payment or health-care operations without authorisation, subject to the minimum-necessary standard for payment + operations.", mandatory: true },
    { clauseRef: "§164.508",  title: "Uses and disclosures for which an authorization is required",              description: "Use or disclosure of psychotherapy notes, use of PHI for marketing, and sale of PHI require a written authorisation that satisfies the core elements and required statements of §164.508(c). The authorisation may be revoked at any time, except to the extent that the CE has taken action in reliance.", mandatory: true },
    { clauseRef: "§164.514",  title: "Other requirements — de-identification, minimum necessary, limited data sets", description: "De-identification: either expert determination per §164.514(b)(1) or safe-harbor removal of 18 identifiers per §164.514(b)(2). Minimum-necessary standard for routine and non-routine disclosures. Limited data sets and data-use agreements per §164.514(e).", mandatory: true },
    { clauseRef: "§164.520",  title: "Notice of privacy practices for PHI",                                       description: "Covered Entities shall provide a notice of privacy practices that adequately informs individuals of the uses and disclosures of PHI that may be made by the CE, individuals' rights and the CE's legal duties. The notice shall be made available on request, posted prominently on any website, and provided at first service delivery.", mandatory: true },
    { clauseRef: "§164.524",  title: "Access of individuals to PHI",                                              description: "Individuals shall have the right of access to inspect and obtain a copy of PHI about them maintained in a designated record set. Action on access request within 30 days (one 30-day extension allowed). Reasonable cost-based fee permitted; electronic copy if maintained electronically.", mandatory: true },
    { clauseRef: "§164.526",  title: "Amendment of PHI",                                                          description: "Individuals shall have the right to request amendment of PHI in a designated record set. Action on request within 60 days (one 30-day extension allowed). The CE may deny the request under specified conditions, and shall provide a denial procedure.", mandatory: true },
    { clauseRef: "§164.528",  title: "Accounting of disclosures of PHI",                                          description: "Individuals shall have the right to receive an accounting of disclosures of their PHI made by the CE in the six years prior to the request, excluding disclosures listed in §164.528(a)(1). Action on accounting request within 60 days (one 30-day extension allowed).", mandatory: true },
    { clauseRef: "§164.530",  title: "Administrative requirements (Privacy Rule)",                                 description: "Privacy-Rule administrative requirements: designate a privacy official and a contact person, training of workforce, safeguards (administrative/technical/physical) to protect privacy of PHI, complaints process, sanctions for workforce non-compliance, mitigation, refraining from intimidating or retaliatory acts, no waiver of rights, policies/procedures, documentation.", mandatory: true },
    { clauseRef: "§160.404",  title: "Civil money penalties (Enforcement Rule)",                                  description: "Civil money penalties for HIPAA violations are tiered by culpability: did not know (≤$100/violation); reasonable cause (≤$1,000); willful neglect, corrected (≤$10,000); willful neglect, not corrected (≤$50,000). Annual cap of $1.5M per violation type. Amounts subject to inflation adjustment.", mandatory: true },
  ],

  // ─── Controls (15 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "HIPAA-ADM-001",   title: "Security management process (Administrative safeguards)",      description: "Documented risk analysis covering all ePHI; risk-management plan with implementation timeline; sanction policy for workforce violations; information-system activity review. Maps §164.308(a)(1).",                                                                                                                                category: "ai-system-governance", evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["§164.308"],            riskLevel: "high"   },
    { controlRef: "HIPAA-ADM-002",   title: "Workforce + access management + training",                     description: "Authorisation, clearance and termination procedures for workforce members; least-privilege information access policy + periodic review; security-awareness training at hire + at least annually. Maps §164.308(a)(3)-(5).",                                                                                                category: "training",            evidenceTypes: ["policy","training_record","log","attestation"],     clauseRefs: ["§164.308"],            riskLevel: "high"   },
    { controlRef: "HIPAA-ADM-003",   title: "Security incident response + contingency planning",            description: "Security-incident response runbook; contingency plan including data-backup plan, disaster-recovery plan, emergency-mode operation, testing and revision. Maps §164.308(a)(6)-(7).",                                                                                                                                  category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["§164.308"],            riskLevel: "high"   },
    { controlRef: "HIPAA-PHY-001",   title: "Physical safeguards (facility, workstation, media)",            description: "Facility access controls; workstation use + security; device and media controls covering disposal, re-use, accountability, data backup and storage. Maps §164.310.",                                                                                                                                                  category: "physical-security",    evidenceTypes: ["policy","procedure","screenshot","report"],         clauseRefs: ["§164.310"],            riskLevel: "high"   },
    { controlRef: "HIPAA-TEC-001",   title: "Access control + audit + integrity + transmission security",   description: "Unique user IDs, automatic logoff, encryption of ePHI at rest where appropriate; audit-log capture and review; integrity controls to detect unauthorised modification; encryption-in-transit. Maps §164.312.",                                                                                                       category: "identity-access",     evidenceTypes: ["configuration","log","attestation","procedure"],     clauseRefs: ["§164.312"],            riskLevel: "high"   },
    { controlRef: "HIPAA-BAA-001",   title: "Business Associate Agreements",                                  description: "Written BAA in place with every Business Associate before the BA gains access to PHI; required clauses per §164.314(a); subcontractor flow-down; reporting of security incidents; termination right on material breach. Maps §164.314.",                                                                              category: "vendor-management",    evidenceTypes: ["contract","report","attestation"],                   clauseRefs: ["§164.314"],            riskLevel: "high"   },
    { controlRef: "HIPAA-DOC-001",   title: "Policies, procedures and 6-year documentation retention",        description: "Written policies + procedures implementing the Security Rule; documentation of actions, activities or assessments required to be documented; retained for 6 years from creation or last effective date; periodic review + update. Maps §164.316.",                                                                  category: "data-protection",      evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["§164.316"],            riskLevel: "high"   },
    { controlRef: "HIPAA-BREACH-001",title: "Breach assessment + tiered notification (60 days)",            description: "Breach detection + four-factor risk assessment per §164.402; individual notification ≤60 days post-discovery; media notification for breaches ≥500 individuals in a State/jurisdiction; HHS notification ≤60 days (≥500) or annual log (<500); BA-to-CE notification. Maps §164.402-410.",                              category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["§164.402","§164.404","§164.406","§164.408","§164.410"], riskLevel: "high"   },
    { controlRef: "HIPAA-USE-001",   title: "Permitted uses + disclosures + minimum necessary",              description: "Documented uses/disclosures aligned with Privacy Rule (TPO, individual access, public-interest exceptions); minimum-necessary standard applied to non-TPO uses; authorisation captured for marketing, psychotherapy notes, sale-of-PHI. Maps §164.502-508.",                                                            category: "data-protection",      evidenceTypes: ["policy","procedure","attestation","screenshot"],     clauseRefs: ["§164.502","§164.506","§164.508"], riskLevel: "high"   },
    { controlRef: "HIPAA-DEID-001",  title: "De-identification + limited data sets",                          description: "When de-identifying PHI, either expert determination per §164.514(b)(1) or safe-harbor removal of the 18 identifiers per §164.514(b)(2); limited data sets used only with a Data Use Agreement. Maps §164.514.",                                                                                                       category: "data-protection",      evidenceTypes: ["procedure","report","attestation","contract"],       clauseRefs: ["§164.514"],            riskLevel: "high"   },
    { controlRef: "HIPAA-NOTICE-001",title: "Notice of Privacy Practices",                                    description: "Current Notice of Privacy Practices satisfying §164.520, available on request, posted on website, provided at first service delivery, acknowledgement obtained where practicable. Maps §164.520.",                                                                                                                category: "ai-system-governance", evidenceTypes: ["policy","screenshot","report"],                      clauseRefs: ["§164.520"],            riskLevel: "high"   },
    { controlRef: "HIPAA-ACC-001",   title: "Individual rights — access, amendment, accounting (30/60-day SLAs)", description: "Right-of-access workflow with 30-day SLA (one 30-day extension); amendment workflow with 60-day SLA; accounting-of-disclosures (6-year lookback) with 60-day SLA. Reasonable cost-based fees; electronic format where ePHI maintained electronically. Maps §164.524-528.",                                       category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],            clauseRefs: ["§164.524","§164.526","§164.528"], riskLevel: "high"   },
    { controlRef: "HIPAA-PRIVADM-001",title: "Privacy Rule administrative requirements",                     description: "Designated privacy official + contact, workforce training within reasonable period of role start, complaints process, sanctions for workforce, mitigation procedures, refraining from intimidating/retaliatory acts, no-waiver clause, policies + 6-year documentation retention. Maps §164.530.",                              category: "ai-system-governance", evidenceTypes: ["policy","procedure","training_record","attestation"], clauseRefs: ["§164.530"],            riskLevel: "high"   },
    { controlRef: "HIPAA-ENC-001",   title: "ePHI encryption + key management",                              description: "Encryption of ePHI at rest in storage and in transit using NIST-recognised algorithms; documented key-management lifecycle (generation, storage, rotation, destruction); inventory of cryptographic controls. Treated as 'safe-harbor' under HHS Breach Notification guidance.",                                       category: "encryption",          evidenceTypes: ["configuration","policy","attestation"],              clauseRefs: ["§164.312"],            riskLevel: "high"   },
    { controlRef: "HIPAA-ENF-001",   title: "Enforcement-Rule awareness + penalty risk register",            description: "Awareness of OCR enforcement, tiered penalty schedule (≤$100 to ≤$50,000 per violation, $1.5M annual cap by tier, inflation-adjusted), corrective-action plan template, willful-neglect-prevention controls. Maps §160.404.",                                                                                            category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                     clauseRefs: ["§160.404"],            riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "HIPAA-Q-001", text: "Is the entity a HIPAA-covered Covered Entity (health plan, health-care clearinghouse, or provider transmitting health information electronically) or Business Associate?",                                  category: "applicability",   riskWeight: 1.0, clauseRefs: ["§164.502"] },
    { questionRef: "HIPAA-Q-002", text: "Has a documented risk analysis been performed covering all ePHI, with a risk-management plan in place (§164.308(a)(1))?",                                                                                  category: "risk",            riskWeight: 1.0, clauseRefs: ["§164.308"] },
    { questionRef: "HIPAA-Q-003", text: "Are workforce authorisation/clearance/termination procedures and least-privilege access management implemented (§164.308(a)(3)-(4))?",                                                                      category: "workforce",       riskWeight: 0.9, clauseRefs: ["§164.308"] },
    { questionRef: "HIPAA-Q-004", text: "Is security-awareness training delivered at hire and at least annually, with records retained (§164.308(a)(5))?",                                                                                            category: "training",        riskWeight: 0.7, clauseRefs: ["§164.308"] },
    { questionRef: "HIPAA-Q-005", text: "Is a security-incident response runbook + contingency plan (incl. backup + DR) in place and tested (§164.308(a)(6)-(7))?",                                                                                   category: "contingency",     riskWeight: 0.9, clauseRefs: ["§164.308"] },
    { questionRef: "HIPAA-Q-006", text: "Are physical safeguards — facility access controls, workstation security, device/media controls — implemented (§164.310)?",                                                                                  category: "physical",        riskWeight: 0.8, clauseRefs: ["§164.310"] },
    { questionRef: "HIPAA-Q-007", text: "Are technical safeguards — unique user ID, automatic logoff, encryption, audit controls, integrity, authentication, transmission security — implemented (§164.312)?",                                       category: "technical",       riskWeight: 1.0, clauseRefs: ["§164.312"] },
    { questionRef: "HIPAA-Q-008", text: "Is a BAA executed with every Business Associate before they receive PHI, with required clauses and subcontractor flow-down (§164.314)?",                                                                     category: "baa",             riskWeight: 1.0, clauseRefs: ["§164.314"] },
    { questionRef: "HIPAA-Q-009", text: "Are written policies + procedures maintained and documentation retained for 6 years from creation/last-effective date (§164.316)?",                                                                          category: "documentation",   riskWeight: 0.8, clauseRefs: ["§164.316"] },
    { questionRef: "HIPAA-Q-010", text: "Is a breach risk-assessment + tiered notification workflow operating, including the 60-day SLA for individuals + HHS + media (§164.402-408)?",                                                              category: "breach",          riskWeight: 1.0, clauseRefs: ["§164.402","§164.404","§164.406","§164.408"] },
    { questionRef: "HIPAA-Q-011", text: "Where the entity is a Business Associate, is a notification path to the Covered Entity for any breach of unsecured PHI defined (§164.410)?",                                                                category: "ba-breach",       riskWeight: 0.9, clauseRefs: ["§164.410"] },
    { questionRef: "HIPAA-Q-012", text: "Are uses and disclosures of PHI limited to TPO, individual access or §164.512 public-interest exceptions, with the minimum-necessary standard applied (§164.502-506)?",                                      category: "uses-disclosures", riskWeight: 1.0, clauseRefs: ["§164.502","§164.506"] },
    { questionRef: "HIPAA-Q-013", text: "Is a valid authorisation obtained for psychotherapy notes, marketing, and sale of PHI (§164.508)?",                                                                                                          category: "authorization",   riskWeight: 0.8, clauseRefs: ["§164.508"] },
    { questionRef: "HIPAA-Q-014", text: "Is PHI de-identified using either expert determination or safe-harbor (18 identifiers), and are limited data sets only used under a DUA (§164.514)?",                                                       category: "deidentification",riskWeight: 0.7, clauseRefs: ["§164.514"] },
    { questionRef: "HIPAA-Q-015", text: "Is a current Notice of Privacy Practices published, posted and provided at first service delivery (§164.520)?",                                                                                              category: "notice",          riskWeight: 0.7, clauseRefs: ["§164.520"] },
    { questionRef: "HIPAA-Q-016", text: "Can right-of-access (30-day), amendment (60-day) and accounting-of-disclosures (60-day) requests be actioned within the statutory SLAs (§164.524-528)?",                                                    category: "rights",          riskWeight: 0.9, clauseRefs: ["§164.524","§164.526","§164.528"] },
    { questionRef: "HIPAA-Q-017", text: "Is a privacy official designated, workforce training delivered, and a complaints process operating (§164.530)?",                                                                                             category: "privacy-admin",   riskWeight: 0.8, clauseRefs: ["§164.530"] },
    { questionRef: "HIPAA-Q-018", text: "Is ePHI encrypted at rest + in transit using NIST-recognised algorithms, with documented key management?",                                                                                                   category: "encryption",      riskWeight: 0.9, clauseRefs: ["§164.312"] },
    { questionRef: "HIPAA-Q-019", text: "Is OCR enforcement risk (tiered penalties up to $1.5M annual cap, plus willful-neglect-not-corrected tier) reflected in the risk register and escalated to leadership?",                                     category: "enforcement",     riskWeight: 0.5, clauseRefs: ["§160.404"] },
  ],
};
