import type { Framework } from "@regunav/types";

/**
 * ISO/IEC 42001:2023 — Information technology — Artificial intelligence —
 * Management system. Specifies requirements for establishing, implementing,
 * maintaining and continually improving an Artificial Intelligence
 * Management System (AIMS) within the context of the organisation.
 *
 * Source: https://www.iso.org/standard/81230.html
 *
 * ⚠ ISO/IEC standards are licensed by ISO and not freely redistributable.
 * The clauses below reference the standard by clause number and outline
 * only — they DO NOT reproduce the published text. Implementers must hold
 * their own ISO licence to consult the full text. See
 * `packages/ontology/LEGAL_DISCLAIMER.md` § "Notice for paywalled standards".
 */
export const ISO_42001: Framework = {
  schemaVersion: 1,
  code: "ISO_42001",
  name: "ISO/IEC 42001:2023",
  version: "2023",
  description:
    "International management-system standard for organisations providing or using products or services that use AI systems. Mirrors the High-Level Structure shared by ISO 9001, ISO 27001 and ISO 14001 (Clauses 4-10) and adds an Annex A of AI-specific controls covering AI policy, organisational roles, AI impact assessment, AI system lifecycle, data for AI systems, information for interested parties, third-party relationships and operational planning. Certifiable by accredited certification bodies.",
  jurisdiction: ["INTERNATIONAL"],
  referenceUrl: "https://www.iso.org/standard/81230.html",

  // ─── Clauses (15 — the High-Level Structure clauses 4-10 + Annex A pillars) ─
  clauses: [
    { clauseRef: "Cl. 4.1",  title: "Understanding the organisation and its context",                            description: "The organisation shall determine external and internal issues relevant to its purpose and that affect its ability to achieve the intended outcomes of the AIMS.", mandatory: true },
    { clauseRef: "Cl. 4.2",  title: "Understanding the needs and expectations of interested parties",            description: "The organisation shall determine interested parties relevant to the AIMS, the relevant requirements of those parties, and which of those requirements are addressed through the AIMS.", mandatory: true },
    { clauseRef: "Cl. 4.3",  title: "Determining the scope of the AI management system",                          description: "The organisation shall determine the boundaries and applicability of the AIMS to establish its scope, taking into account external/internal issues, interested-party requirements, and interactions with other management systems.", mandatory: true },
    { clauseRef: "Cl. 5.1",  title: "Leadership and commitment",                                                  description: "Top management shall demonstrate leadership and commitment with respect to the AIMS by establishing the AI policy and AI objectives, integrating AIMS requirements into business processes, ensuring resources, communicating importance, and supporting other relevant management roles.", mandatory: true },
    { clauseRef: "Cl. 5.2",  title: "AI policy",                                                                   description: "Top management shall establish an AI policy that is appropriate to the purpose of the organisation, provides a framework for setting AI objectives, includes a commitment to satisfy applicable requirements and to continual improvement.", mandatory: true },
    { clauseRef: "Cl. 5.3",  title: "Organisational roles, responsibilities and authorities",                     description: "Top management shall ensure that responsibilities and authorities for relevant roles within the AIMS are assigned, communicated and understood across the organisation.", mandatory: true },
    { clauseRef: "Cl. 6.1",  title: "Actions to address risks and opportunities",                                 description: "When planning the AIMS, the organisation shall consider 4.1 / 4.2 issues and determine the risks and opportunities that need to be addressed. AI risk assessment (Cl. 6.1.2) and AI risk treatment (Cl. 6.1.3) sub-clauses define the AI-specific approach.", mandatory: true },
    { clauseRef: "Cl. 6.2",  title: "AI objectives and planning to achieve them",                                 description: "The organisation shall establish AI objectives at relevant functions and levels that are consistent with the AI policy, measurable (where practicable), monitored, communicated and updated as appropriate.", mandatory: true },
    { clauseRef: "Cl. 7.2",  title: "Competence",                                                                  description: "The organisation shall determine the necessary competence of persons doing work under its control that affects AI performance, ensure those persons are competent on the basis of appropriate education/training/experience, take actions to acquire necessary competence, and retain documented evidence.", mandatory: true },
    { clauseRef: "Cl. 7.3",  title: "Awareness",                                                                   description: "Persons doing work under the organisation's control shall be aware of the AI policy, their contribution to the effectiveness of the AIMS, and the implications of not conforming with the AIMS requirements.", mandatory: true },
    { clauseRef: "Cl. 8.1",  title: "Operational planning and control",                                            description: "The organisation shall plan, implement and control the processes needed to meet AIMS requirements and to implement the actions determined in 6.1, by establishing criteria for the processes, implementing control of the processes in accordance with the criteria, and keeping documented information.", mandatory: true },
    { clauseRef: "Cl. 9.1",  title: "Monitoring, measurement, analysis and evaluation",                            description: "The organisation shall determine what needs to be monitored and measured, the methods, when, who is responsible, and when the results shall be analysed and evaluated. The organisation shall retain documented evidence of the results.", mandatory: true },
    { clauseRef: "Cl. 9.2",  title: "Internal audit",                                                              description: "The organisation shall conduct internal audits at planned intervals to provide information on whether the AIMS conforms to its own requirements and to ISO/IEC 42001 and is effectively implemented and maintained.", mandatory: true },
    { clauseRef: "Cl. 9.3",  title: "Management review",                                                           description: "Top management shall review the AIMS at planned intervals to ensure its continuing suitability, adequacy and effectiveness. Inputs include status of actions from previous reviews, changes in external/internal issues, AIMS performance and trends, audit results, feedback from interested parties, and opportunities for continual improvement.", mandatory: true },
    { clauseRef: "Cl. 10.1", title: "Continual improvement",                                                       description: "The organisation shall continually improve the suitability, adequacy and effectiveness of the AIMS. Cl. 10.2 sets out the response when a nonconformity occurs, including action to control, correct and deal with consequences.", mandatory: true },
    { clauseRef: "Annex A.2",title: "Policies related to AI",                                                      description: "Control objectives and controls covering the establishment, communication, review and updating of policies for the responsible development, provision and use of AI systems.", mandatory: true },
    { clauseRef: "Annex A.3",title: "Internal organisation",                                                       description: "Roles and responsibilities for AI accountability, reporting of concerns, and supplier-relationship governance.", mandatory: true },
    { clauseRef: "Annex A.4",title: "Resources for AI systems",                                                    description: "Controls covering data resources, tools, system and computing resources, and human resources for AI systems across their lifecycle.", mandatory: true },
    { clauseRef: "Annex A.5",title: "Assessing impacts of AI systems",                                             description: "Controls covering AI system impact assessment scope, methodology, the process across the AI system lifecycle, and documented impacts on individuals or groups of individuals, societies, the environment.", mandatory: true },
    { clauseRef: "Annex A.6",title: "AI system life cycle",                                                        description: "Controls covering objectives for responsible AI design, design and development processes, quality and performance verification, deployment, operation, monitoring, and decommissioning across the AI system lifecycle.", mandatory: true },
    { clauseRef: "Annex A.7",title: "Data for AI systems",                                                         description: "Controls covering data for development and operation of AI systems, including data acquisition, quality, provenance, preparation and the management of data privacy.", mandatory: true },
    { clauseRef: "Annex A.8",title: "Information for interested parties of AI systems",                            description: "Controls covering information provided to users and other interested parties, system documentation, communication of incidents and reporting of concerns.", mandatory: true },
    { clauseRef: "Annex A.9",title: "Use of AI systems",                                                           description: "Controls covering the responsible use of AI systems, processes for AI system use, and intended use definition for both providers and users.", mandatory: true },
    { clauseRef: "Annex A.10",title: "Third-party and customer relationships",                                     description: "Controls covering allocation of responsibilities between the organisation, suppliers, partners and customers across the AI value chain.", mandatory: true },
  ],

  // ─── Controls (14 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "ISO42001-CTX-001",   title: "AIMS context, scope and interested-party requirements",      description: "Documented analysis of internal/external issues affecting AI outcomes, identified interested parties and their requirements, and AIMS scope statement including boundaries and interactions with other management systems.",                                                category: "ai-system-governance", evidenceTypes: ["policy","report","attestation"],                       clauseRefs: ["Cl. 4.1","Cl. 4.2","Cl. 4.3"],   riskLevel: "high"   },
    { controlRef: "ISO42001-POL-001",   title: "AI policy + objectives",                                       description: "Top-management-approved AI policy and measurable AI objectives, communicated organisation-wide, reviewed at planned intervals. Maps Annex A.2.",                                                                                                                                category: "ai-system-governance", evidenceTypes: ["policy","attestation","report"],                       clauseRefs: ["Cl. 5.2","Cl. 6.2","Annex A.2"], riskLevel: "high"   },
    { controlRef: "ISO42001-LEAD-001",  title: "Leadership commitment + accountability roles",                description: "Demonstrated top-management commitment, defined AI-accountability owner, RACI matrix for AI roles, and documented authority assignments. Maps Annex A.3.",                                                                                                                       category: "ai-system-governance", evidenceTypes: ["attestation","report","policy"],                       clauseRefs: ["Cl. 5.1","Cl. 5.3","Annex A.3"], riskLevel: "high"   },
    { controlRef: "ISO42001-RISK-001",  title: "AI risk assessment + treatment",                              description: "AI risk-assessment process (Cl. 6.1.2) with documented criteria, treatment plan (Cl. 6.1.3), and residual-risk acceptance signed by AI governance owner. Iterates over the lifecycle.",                                                                                              category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                     clauseRefs: ["Cl. 6.1"],                       riskLevel: "high"   },
    { controlRef: "ISO42001-IMP-001",   title: "AI system impact assessment",                                 description: "Per-system impact assessment scoped to affected individuals, groups, societies and the environment. Re-run on material change and reviewed at planned intervals. Maps Annex A.5.",                                                                                                  category: "ai-system-governance", evidenceTypes: ["fria","report","attestation"],                          clauseRefs: ["Annex A.5"],                     riskLevel: "high"   },
    { controlRef: "ISO42001-COMP-001",  title: "Competence + awareness for AI roles",                         description: "Documented competence requirements, training records, awareness campaigns. Covers Cl. 7.2 + 7.3 obligations.",                                                                                                                                                                       category: "training",            evidenceTypes: ["training_record","report","procedure"],                clauseRefs: ["Cl. 7.2","Cl. 7.3"],             riskLevel: "limited" },
    { controlRef: "ISO42001-OP-001",    title: "Operational planning + control",                               description: "Process criteria, change-control, supplier-input/customer-output handoff, documented information retained for evidence. Anchors Cl. 8.1 obligations.",                                                                                                                              category: "ai-system-governance", evidenceTypes: ["procedure","report","configuration"],                  clauseRefs: ["Cl. 8.1"],                       riskLevel: "high"   },
    { controlRef: "ISO42001-LIFE-001",  title: "AI system lifecycle controls",                                description: "Lifecycle gates: responsible design, verification, deployment, operation/monitoring and decommissioning. Each gate has owner, criteria, evidence requirements. Maps Annex A.6.",                                                                                                category: "ai-system-governance", evidenceTypes: ["procedure","report","configuration","attestation"],     clauseRefs: ["Annex A.6"],                     riskLevel: "high"   },
    { controlRef: "ISO42001-DATA-001",  title: "Data resources for AI systems",                               description: "Data acquisition, quality, provenance and preparation controls. Privacy-of-data-used-for-AI mapping into the privacy regime. Maps Annex A.7.",                                                                                                                                       category: "data-protection",     evidenceTypes: ["report","configuration","procedure","attestation"],   clauseRefs: ["Annex A.4","Annex A.7"],         riskLevel: "high"   },
    { controlRef: "ISO42001-INFO-001",  title: "Information to interested parties",                           description: "User-facing documentation, communication of incidents, mechanism for reporting concerns. Maps Annex A.8.",                                                                                                                                                                              category: "ai-system-governance", evidenceTypes: ["procedure","report","screenshot"],                     clauseRefs: ["Annex A.8"],                     riskLevel: "limited" },
    { controlRef: "ISO42001-USE-001",   title: "Responsible-use processes",                                    description: "Defined intended use, deployer obligations, restrictions on use, monitoring of conformance. Maps Annex A.9.",                                                                                                                                                                       category: "ai-system-governance", evidenceTypes: ["procedure","policy","report"],                          clauseRefs: ["Annex A.9"],                     riskLevel: "high"   },
    { controlRef: "ISO42001-3P-001",    title: "Third-party + customer-relationship governance",              description: "Responsibility allocation across the AI value chain, supplier due diligence, customer-input handoff, contractual flow-down. Maps Annex A.10.",                                                                                                                                       category: "vendor-management",    evidenceTypes: ["contract","report","attestation","procedure"],         clauseRefs: ["Annex A.10"],                    riskLevel: "high"   },
    { controlRef: "ISO42001-MEAS-001",  title: "Monitoring, measurement, analysis and evaluation",            description: "Defined KPIs and KRIs for AI performance, monitoring cadence, owner, analytical method, documented results. Cl. 9.1 anchor.",                                                                                                                                                       category: "logging-monitoring",  evidenceTypes: ["report","log","configuration"],                         clauseRefs: ["Cl. 9.1"],                       riskLevel: "high"   },
    { controlRef: "ISO42001-IA-001",    title: "Internal audit + management review",                          description: "Internal-audit programme at planned intervals against AIMS requirements, management review minutes, action register from review outcomes. Cl. 9.2 + 9.3 anchor.",                                                                                                                    category: "ai-system-governance", evidenceTypes: ["report","attestation","procedure"],                     clauseRefs: ["Cl. 9.2","Cl. 9.3"],             riskLevel: "high"   },
    { controlRef: "ISO42001-CI-001",    title: "Continual improvement + nonconformity handling",              description: "Nonconformity register, root-cause analysis, corrective-action plan, continual-improvement objectives tracked against the AIMS. Cl. 10 anchor.",                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                     clauseRefs: ["Cl. 10.1"],                      riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "ISO42001-Q-001", text: "Has the organisation's context (internal/external issues affecting AI outcomes) been determined and documented (Cl. 4.1)?",                                                            category: "context",         riskWeight: 0.7, clauseRefs: ["Cl. 4.1"] },
    { questionRef: "ISO42001-Q-002", text: "Have interested parties and their AI-relevant requirements been identified and tracked (Cl. 4.2)?",                                                                                     category: "interested-parties", riskWeight: 0.7, clauseRefs: ["Cl. 4.2"] },
    { questionRef: "ISO42001-Q-003", text: "Is the AIMS scope (boundaries, applicability, interactions with other management systems) documented and approved (Cl. 4.3)?",                                                          category: "scope",           riskWeight: 0.7, clauseRefs: ["Cl. 4.3"] },
    { questionRef: "ISO42001-Q-004", text: "Is there a top-management-approved AI policy with measurable AI objectives, communicated organisation-wide (Cl. 5.2 + 6.2 + Annex A.2)?",                                                category: "policy",          riskWeight: 0.9, clauseRefs: ["Cl. 5.2","Cl. 6.2","Annex A.2"] },
    { questionRef: "ISO42001-Q-005", text: "Are AI roles, responsibilities and authorities documented and an AI-accountability owner appointed (Cl. 5.3 + Annex A.3)?",                                                              category: "roles",           riskWeight: 0.8, clauseRefs: ["Cl. 5.3","Annex A.3"] },
    { questionRef: "ISO42001-Q-006", text: "Is an AI risk-assessment + treatment process operating, with criteria, residual-risk acceptance and lifecycle iteration (Cl. 6.1)?",                                                     category: "risk",            riskWeight: 1.0, clauseRefs: ["Cl. 6.1"] },
    { questionRef: "ISO42001-Q-007", text: "Are per-system AI impact assessments performed and re-run on material change (Annex A.5)?",                                                                                              category: "impact",          riskWeight: 0.9, clauseRefs: ["Annex A.5"] },
    { questionRef: "ISO42001-Q-008", text: "Is competence for AI roles documented, with training records retained (Cl. 7.2)?",                                                                                                       category: "competence",      riskWeight: 0.6, clauseRefs: ["Cl. 7.2"] },
    { questionRef: "ISO42001-Q-009", text: "Are operational controls in place for the processes that implement the AIMS (Cl. 8.1)?",                                                                                                  category: "operations",      riskWeight: 0.8, clauseRefs: ["Cl. 8.1"] },
    { questionRef: "ISO42001-Q-010", text: "Are AI-system-lifecycle gates (design, verification, deployment, monitoring, decommissioning) implemented with owners and evidence (Annex A.6)?",                                       category: "lifecycle",       riskWeight: 0.9, clauseRefs: ["Annex A.6"] },
    { questionRef: "ISO42001-Q-011", text: "Are data-quality, provenance, preparation and privacy-for-AI controls applied to training/validation/test data (Annex A.4 + A.7)?",                                                      category: "data",            riskWeight: 0.9, clauseRefs: ["Annex A.4","Annex A.7"] },
    { questionRef: "ISO42001-Q-012", text: "Is required information provided to interested parties, with a mechanism to receive incident reports + concerns (Annex A.8)?",                                                            category: "transparency",    riskWeight: 0.7, clauseRefs: ["Annex A.8"] },
    { questionRef: "ISO42001-Q-013", text: "Are responsible-use processes (intended use, deployer obligations, monitoring) defined and enforced (Annex A.9)?",                                                                       category: "use",             riskWeight: 0.7, clauseRefs: ["Annex A.9"] },
    { questionRef: "ISO42001-Q-014", text: "Is responsibility allocation across the AI value chain (suppliers, partners, customers) governed contractually (Annex A.10)?",                                                            category: "third-party",     riskWeight: 0.8, clauseRefs: ["Annex A.10"] },
    { questionRef: "ISO42001-Q-015", text: "Are KPIs/KRIs for AI performance monitored at the defined cadence and evaluated against objectives (Cl. 9.1)?",                                                                          category: "monitoring",      riskWeight: 0.7, clauseRefs: ["Cl. 9.1"] },
    { questionRef: "ISO42001-Q-016", text: "Is an internal-audit programme operating against AIMS requirements (Cl. 9.2)?",                                                                                                          category: "audit",           riskWeight: 0.7, clauseRefs: ["Cl. 9.2"] },
    { questionRef: "ISO42001-Q-017", text: "Are management reviews of the AIMS held at planned intervals, with input + output records retained (Cl. 9.3)?",                                                                          category: "management-review",riskWeight: 0.6, clauseRefs: ["Cl. 9.3"] },
    { questionRef: "ISO42001-Q-018", text: "Is a nonconformity + corrective-action register operating, feeding continual-improvement objectives (Cl. 10)?",                                                                          category: "improvement",     riskWeight: 0.7, clauseRefs: ["Cl. 10.1"] },
  ],
};
