import type { Framework } from "@regunav/types";

/**
 * ISO/IEC 27001:2022 — Information security, cybersecurity and privacy
 * protection — Information security management systems — Requirements.
 *
 * Source: https://www.iso.org/standard/27001
 *
 * ⚠ ISO/IEC standards are licensed by ISO and not freely redistributable.
 * The clauses below reference the standard by clause number and outline
 * only — they DO NOT reproduce the published text. Implementers must hold
 * their own ISO licence. See packages/ontology/LEGAL_DISCLAIMER.md
 * § "Notice for paywalled standards".
 *
 * The 2022 revision introduced the new 93-control Annex A grouped into
 * four themes: A.5 Organisational (37 controls), A.6 People (8), A.7
 * Physical (14), A.8 Technological (34).
 */
export const ISO_27001: Framework = {
  schemaVersion: 1,
  code: "ISO_27001",
  name: "ISO/IEC 27001:2022",
  version: "2022",
  description:
    "International standard specifying the requirements for an Information Security Management System (ISMS). HLS clauses 4-10 cover establishment, leadership, planning, support, operation, performance evaluation and improvement. Annex A enumerates 93 information-security controls grouped into Organisational (A.5), People (A.6), Physical (A.7) and Technological (A.8) themes. Certifiable by accredited certification bodies.",
  jurisdiction: ["INTERNATIONAL"],
  referenceUrl: "https://www.iso.org/standard/27001",

  // ─── Clauses (16 — HLS 4-10 + Annex A 4 themes + 6 key control groups) ────
  clauses: [
    { clauseRef: "Cl. 4.1",  title: "Understanding the organisation and its context",                       description: "The organisation shall determine external and internal issues relevant to its purpose and that affect its ability to achieve the intended outcomes of the ISMS.", mandatory: true },
    { clauseRef: "Cl. 4.2",  title: "Understanding the needs and expectations of interested parties",       description: "The organisation shall determine interested parties relevant to the ISMS and their requirements, including legal, regulatory and contractual requirements.", mandatory: true },
    { clauseRef: "Cl. 4.3",  title: "Determining the scope of the ISMS",                                     description: "The organisation shall determine the boundaries and applicability of the ISMS to establish its scope, taking external/internal issues, interested-party requirements and interfaces/dependencies with other activities into account.", mandatory: true },
    { clauseRef: "Cl. 5.2",  title: "Information security policy",                                            description: "Top management shall establish an information security policy that is appropriate to the purpose of the organisation, provides a framework for setting information security objectives, includes commitment to satisfy applicable requirements and to continual improvement.", mandatory: true },
    { clauseRef: "Cl. 6.1.2",title: "Information security risk assessment",                                  description: "The organisation shall define and apply a risk assessment process that establishes and maintains risk criteria, identifies risks, analyses likelihood and consequences, evaluates risks against criteria, prioritises risks for treatment, and retains documented evidence.", mandatory: true },
    { clauseRef: "Cl. 6.1.3",title: "Information security risk treatment",                                   description: "The organisation shall define and apply a risk treatment process to select appropriate risk treatment options, determine controls necessary to implement the risk treatment options, compare against Annex A to verify no necessary controls have been omitted, produce a Statement of Applicability (SoA), formulate a risk treatment plan, and obtain risk-owners' approval of the plan and acceptance of residual risks.", mandatory: true },
    { clauseRef: "Cl. 6.2",  title: "Information security objectives",                                        description: "The organisation shall establish information security objectives at relevant functions and levels that are consistent with the policy, measurable (where practicable), monitored, communicated and updated as appropriate.", mandatory: true },
    { clauseRef: "Cl. 7.2",  title: "Competence",                                                              description: "The organisation shall determine the necessary competence of persons doing work under its control that affects information security performance, ensure those persons are competent on the basis of appropriate education/training/experience, take actions to acquire competence, and retain documented evidence.", mandatory: true },
    { clauseRef: "Cl. 8.1",  title: "Operational planning and control",                                        description: "The organisation shall plan, implement and control the processes needed to meet ISMS requirements, implement the actions determined in Clause 6, and keep documented information to the extent necessary to have confidence that the processes have been carried out as planned.", mandatory: true },
    { clauseRef: "Cl. 9.1",  title: "Monitoring, measurement, analysis and evaluation",                        description: "The organisation shall evaluate the information security performance and the effectiveness of the ISMS by determining what needs to be monitored, the methods, when, who, and analysing/evaluating the results. Documented evidence of the results shall be retained.", mandatory: true },
    { clauseRef: "Cl. 9.2",  title: "Internal audit",                                                          description: "The organisation shall conduct internal audits at planned intervals to provide information on whether the ISMS conforms to the organisation's own requirements and to ISO/IEC 27001 and is effectively implemented and maintained.", mandatory: true },
    { clauseRef: "Cl. 9.3",  title: "Management review",                                                       description: "Top management shall review the ISMS at planned intervals to ensure its continuing suitability, adequacy and effectiveness.", mandatory: true },
    { clauseRef: "Cl. 10",   title: "Improvement",                                                              description: "The organisation shall continually improve the suitability, adequacy and effectiveness of the ISMS. When a nonconformity occurs, the organisation shall react, evaluate the need for action to eliminate causes, implement action, review effectiveness, and make changes to the ISMS if necessary.", mandatory: true },
    { clauseRef: "Annex A.5",title: "Organisational controls (37 controls)",                                  description: "Controls covering information security policies, roles and responsibilities, segregation of duties, contact with authorities, contact with special-interest groups, threat intelligence, ISMS in project management, asset inventory, classification, labelling, transfer, access control, identity management, authentication, supplier relationships, supply-chain security, ICT in BCM, legal/regulatory/contractual compliance.", mandatory: true },
    { clauseRef: "Annex A.6",title: "People controls (8 controls)",                                            description: "Controls covering screening, terms and conditions of employment, awareness/education/training, disciplinary process, responsibilities after termination/change, confidentiality/NDAs, remote working, information-security event reporting.", mandatory: true },
    { clauseRef: "Annex A.7",title: "Physical controls (14 controls)",                                         description: "Controls covering physical security perimeters, physical entry, securing offices/rooms/facilities, physical security monitoring, protecting against environmental threats, working in secure areas, clear desk and screen, equipment siting, security of assets off-premises, storage media, supporting utilities, cabling, equipment maintenance, secure disposal/re-use.", mandatory: true },
    { clauseRef: "Annex A.8",title: "Technological controls (34 controls)",                                    description: "Controls covering user endpoint devices, privileged access rights, information access restriction, source code access, secure authentication, capacity management, malware protection, technical vulnerability management, configuration management, information deletion, data masking, data leakage prevention, backup, redundancy, logging, monitoring activities, clock synchronisation, use of privileged utility programs, installation of software, network security, network segregation, web filtering, cryptography, secure development lifecycle, application security, secure system architecture and engineering, outsourced development, separation of dev/test/prod, change management, test information, protection of information systems during audit testing.", mandatory: true },
  ],

  // ─── Controls (15 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "ISO27001-CTX-001",  title: "ISMS context, scope and interested-party requirements", description: "Documented analysis of internal/external issues, interested-party requirements, ISMS scope statement including boundaries and interfaces/dependencies with other activities.", category: "ai-system-governance", evidenceTypes: ["policy","report","attestation"],                       clauseRefs: ["Cl. 4.1","Cl. 4.2","Cl. 4.3"], riskLevel: "high"   },
    { controlRef: "ISO27001-POL-001",  title: "Information security policy + objectives",              description: "Top-management-approved information-security policy and measurable objectives, communicated, reviewed at planned intervals. Maps Annex A.5.1 + A.5.2.",                                  category: "ai-system-governance", evidenceTypes: ["policy","attestation","report"],                       clauseRefs: ["Cl. 5.2","Cl. 6.2"],          riskLevel: "high"   },
    { controlRef: "ISO27001-RISK-001", title: "Information security risk assessment + treatment + SoA", description: "Risk-assessment process (Cl. 6.1.2), risk-treatment process (Cl. 6.1.3), Statement of Applicability comparing selected controls against Annex A, treatment plan, residual-risk acceptance.", category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation","configuration"],     clauseRefs: ["Cl. 6.1.2","Cl. 6.1.3"],      riskLevel: "high"   },
    { controlRef: "ISO27001-ORG-001",  title: "Organisational controls (Annex A.5) implementation",     description: "Asset inventory, classification + labelling, segregation of duties, supplier-relationship management, supply-chain security, threat intelligence, contact with authorities + special-interest groups.",                                                                                                  category: "data-protection",      evidenceTypes: ["policy","procedure","report","contract"],              clauseRefs: ["Annex A.5"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-PEOPLE-001",title:"People controls (Annex A.6) implementation",            description: "Screening, terms of employment, awareness + training, disciplinary process, post-employment obligations, confidentiality + NDAs, remote-working policy, event-reporting channel.",                                                                                                                              category: "training",            evidenceTypes: ["policy","training_record","contract","procedure"],     clauseRefs: ["Annex A.6"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-PHYS-001", title: "Physical controls (Annex A.7) implementation",          description: "Perimeter security, entry controls, secure area policy, environmental-threat protection, clear-desk/screen, equipment siting + maintenance + secure disposal, off-premises asset security, media handling.",                                                                                              category: "physical-security",   evidenceTypes: ["policy","procedure","screenshot","report"],            clauseRefs: ["Annex A.7"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-IAM-001",  title: "Identity + access management (subset of A.8)",          description: "Access-control policy, identity management, authentication (incl. MFA), privileged-access governance, information access restriction, source-code access controls.",                                                                                                                                                  category: "identity-access",     evidenceTypes: ["policy","configuration","log","attestation"],          clauseRefs: ["Annex A.5","Annex A.8"],      riskLevel: "high"   },
    { controlRef: "ISO27001-CRYP-001", title: "Cryptography + key management (A.8.24)",                description: "Cryptography policy, algorithm + key-length standards, key management lifecycle (generation, storage, rotation, archival, destruction), cryptographic-control inventory.",                                                                                                                                          category: "encryption",          evidenceTypes: ["policy","configuration","attestation"],                clauseRefs: ["Annex A.8"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-LOG-001",  title: "Logging + monitoring (A.8.15-A.8.17)",                  description: "Logging policy, event collection, monitoring activities, clock synchronisation, log retention aligned with regulatory + investigation needs, integrity protection of logs.",                                                                                                                                       category: "logging-monitoring",  evidenceTypes: ["log","configuration","report","attestation"],          clauseRefs: ["Annex A.8"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-VULN-001", title: "Vulnerability + change management (A.8.8-A.8.9, A.8.32)", description: "Technical-vulnerability identification + remediation cadence, configuration management, change-management process with peer review + approval, segregation of dev/test/prod.",                                                                                                                                  category: "vulnerability-management", evidenceTypes: ["report","configuration","procedure","log"],         clauseRefs: ["Annex A.8"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-NET-001",  title: "Network security + segregation (A.8.20-A.8.23)",        description: "Network security controls including segregation, web filtering, secure protocols, perimeter and east-west controls.",                                                                                                                                                                                                                  category: "data-protection",     evidenceTypes: ["configuration","report","attestation"],                clauseRefs: ["Annex A.8"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-SDLC-001", title: "Secure software development lifecycle (A.8.25-A.8.31)", description: "Secure development policy, application security, secure system architecture and engineering, outsourced-development controls, secure coding practices, test data handling.",                                                                                                                                            category: "change-management",   evidenceTypes: ["policy","procedure","configuration","report"],         clauseRefs: ["Annex A.8"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-INC-001",  title: "Information security incident management (A.5.24-A.5.28)", description: "Incident-management policy, classification + escalation, response + recovery procedures, evidence collection, lessons-learned register, contact with authorities where required by law.",                                                                                                                          category: "incident-response",   evidenceTypes: ["procedure","incident_record","report","attestation"],   clauseRefs: ["Annex A.5"],                  riskLevel: "high"   },
    { controlRef: "ISO27001-BCM-001",  title: "ICT continuity + recovery (A.5.29-A.5.30 + A.8.13-A.8.14)", description: "Business-continuity + ICT-readiness controls, backup policy and tested restores, redundancy of information-processing facilities, supporting-utility resilience.",                                                                                                                                                  category: "business-continuity", evidenceTypes: ["procedure","report","configuration","attestation"],    clauseRefs: ["Annex A.5","Annex A.8"],     riskLevel: "high"   },
    { controlRef: "ISO27001-IA-001",   title: "Internal audit + management review + continual improvement", description: "Internal-audit programme against ISMS requirements, management-review minutes at planned intervals, nonconformity register, corrective-action plan, continual-improvement objectives.",                                                                                                                          category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Cl. 9.2","Cl. 9.3","Cl. 10"], riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "ISO27001-Q-001", text: "Are internal/external issues affecting the ISMS documented (Cl. 4.1)?",                                                                                category: "context",       riskWeight: 0.7, clauseRefs: ["Cl. 4.1"] },
    { questionRef: "ISO27001-Q-002", text: "Are interested parties and their requirements (legal, regulatory, contractual) identified and tracked (Cl. 4.2)?",                                     category: "interested-parties", riskWeight: 0.7, clauseRefs: ["Cl. 4.2"] },
    { questionRef: "ISO27001-Q-003", text: "Is the ISMS scope statement documented and approved by top management (Cl. 4.3)?",                                                                       category: "scope",         riskWeight: 0.7, clauseRefs: ["Cl. 4.3"] },
    { questionRef: "ISO27001-Q-004", text: "Is a top-management-approved information-security policy in place with measurable objectives (Cl. 5.2 + 6.2)?",                                          category: "policy",        riskWeight: 0.9, clauseRefs: ["Cl. 5.2","Cl. 6.2"] },
    { questionRef: "ISO27001-Q-005", text: "Is a risk-assessment + treatment process operating, with a Statement of Applicability and residual-risk acceptance (Cl. 6.1.2-6.1.3)?",                  category: "risk",          riskWeight: 1.0, clauseRefs: ["Cl. 6.1.2","Cl. 6.1.3"] },
    { questionRef: "ISO27001-Q-006", text: "Are Annex A.5 (Organisational) controls implemented to the extent applicable, with the SoA recording exclusions and justifications?",                    category: "annex-a-org",   riskWeight: 0.9, clauseRefs: ["Annex A.5"] },
    { questionRef: "ISO27001-Q-007", text: "Are Annex A.6 (People) controls — screening, training, disciplinary process, NDA, event-reporting channel — implemented?",                                category: "annex-a-people",riskWeight: 0.8, clauseRefs: ["Annex A.6"] },
    { questionRef: "ISO27001-Q-008", text: "Are Annex A.7 (Physical) controls — perimeter, entry, environmental, clear-desk, equipment maintenance + disposal — implemented?",                       category: "annex-a-physical",riskWeight: 0.7,clauseRefs: ["Annex A.7"] },
    { questionRef: "ISO27001-Q-009", text: "Are Annex A.8 (Technological) controls — IAM, cryptography, logging, vuln mgmt, network security, SDLC — implemented?",                                  category: "annex-a-tech",  riskWeight: 0.9, clauseRefs: ["Annex A.8"] },
    { questionRef: "ISO27001-Q-010", text: "Is competence for ISMS roles documented with training records retained (Cl. 7.2)?",                                                                       category: "competence",    riskWeight: 0.6, clauseRefs: ["Cl. 7.2"] },
    { questionRef: "ISO27001-Q-011", text: "Are operational controls in place for the processes that implement the ISMS (Cl. 8.1)?",                                                                  category: "operations",    riskWeight: 0.7, clauseRefs: ["Cl. 8.1"] },
    { questionRef: "ISO27001-Q-012", text: "Is ISMS performance monitored, analysed and evaluated at the defined cadence (Cl. 9.1)?",                                                                category: "monitoring",    riskWeight: 0.7, clauseRefs: ["Cl. 9.1"] },
    { questionRef: "ISO27001-Q-013", text: "Is an internal-audit programme operating against ISMS requirements (Cl. 9.2)?",                                                                          category: "audit",         riskWeight: 0.7, clauseRefs: ["Cl. 9.2"] },
    { questionRef: "ISO27001-Q-014", text: "Are management reviews held at planned intervals, with inputs and outputs documented (Cl. 9.3)?",                                                         category: "management-review", riskWeight: 0.6, clauseRefs: ["Cl. 9.3"] },
    { questionRef: "ISO27001-Q-015", text: "Is a nonconformity + corrective-action register operating, feeding continual-improvement objectives (Cl. 10)?",                                          category: "improvement",   riskWeight: 0.7, clauseRefs: ["Cl. 10"] },
    { questionRef: "ISO27001-Q-016", text: "Is logging + monitoring (Annex A.8.15-A.8.17) operating with appropriate retention, integrity protection and clock synchronisation?",                    category: "logging",       riskWeight: 0.8, clauseRefs: ["Annex A.8"] },
    { questionRef: "ISO27001-Q-017", text: "Is an incident-management process operating with classification, escalation, evidence collection and lessons-learned (Annex A.5.24-A.5.28)?",            category: "incident",      riskWeight: 0.8, clauseRefs: ["Annex A.5"] },
    { questionRef: "ISO27001-Q-018", text: "Are ICT continuity + recovery controls — backup, redundancy, tested restores — in place (Annex A.5.29-A.5.30 + A.8.13-A.8.14)?",                          category: "continuity",    riskWeight: 0.7, clauseRefs: ["Annex A.5","Annex A.8"] },
  ],
};
