import type { Framework } from "@regunav/types";

/**
 * ISO/IEC 27701:2019 — Security techniques — Extension to ISO/IEC 27001
 * and ISO/IEC 27002 for privacy information management — Requirements
 * and guidelines.
 *
 * Source: https://www.iso.org/standard/71670.html
 *
 * ⚠ ISO/IEC standards are licensed by ISO and not freely redistributable.
 * Clauses below reference the standard by clause number and outline only —
 * they DO NOT reproduce the published text. Implementers must hold their
 * own ISO licence. See packages/ontology/LEGAL_DISCLAIMER.md §
 * "Notice for paywalled standards".
 *
 * ISO 27701 is built on ISO 27001 / 27002: an organisation with an
 * established ISMS adds the privacy-specific extensions in this standard
 * to create a Privacy Information Management System (PIMS). Certifiable
 * by accredited certification bodies in conjunction with ISO 27001.
 */
export const ISO_27701: Framework = {
  schemaVersion: 1,
  code: "ISO_27701",
  name: "ISO/IEC 27701:2019",
  version: "2019",
  description:
    "International standard extending ISO/IEC 27001 (ISMS) and ISO/IEC 27002 (controls) for privacy information management. Establishes a Privacy Information Management System (PIMS) that covers both PII controllers and PII processors. Clause 5 contains PIMS-specific requirements; Clause 6 contains PIMS-specific guidance for ISO 27002 controls; Clause 7 contains additional guidance for PII controllers (Annex A controls); Clause 8 contains additional guidance for PII processors (Annex B controls). Annex D maps the standard to the GDPR.",
  jurisdiction: ["INTERNATIONAL"],
  referenceUrl: "https://www.iso.org/standard/71670.html",

  // ─── Clauses (15 — PIMS-specific requirements + control annexes + mapping) ─
  clauses: [
    { clauseRef: "Cl. 5.2",  title: "Understanding the organisation and its context (PIMS extension)",      description: "Augments ISO 27001 Cl. 4 with PIMS-specific context determination: identify the role of the organisation as a PII controller, a PII processor, or both, in the context of the processing activities; identify external and internal issues that are relevant to the determination of the PIMS objectives.", mandatory: true },
    { clauseRef: "Cl. 5.3",  title: "Leadership (PIMS extension)",                                            description: "Augments ISO 27001 Cl. 5 — top-management commitment, PIMS policy and assignment of organisational roles for privacy in addition to the information-security roles already established under ISO 27001.", mandatory: true },
    { clauseRef: "Cl. 5.4",  title: "Planning (PIMS extension — privacy risk assessment + treatment)",       description: "Augments ISO 27001 Cl. 6 with privacy-risk assessment + treatment. The risk assessment shall identify risks associated with the processing of PII, considering the impact on data subjects (PII principals), and shall use the additional Annex A / Annex B controls in the Statement of Applicability.", mandatory: true },
    { clauseRef: "Cl. 5.5",  title: "Support (PIMS extension)",                                                description: "Augments ISO 27001 Cl. 7 — resources, competence, awareness, communication, documented information — extended to cover the PIMS-specific obligations.", mandatory: true },
    { clauseRef: "Cl. 5.6",  title: "Operation (PIMS extension)",                                              description: "Augments ISO 27001 Cl. 8 — operational planning, control of changes, processes addressing PII processing risks across the lifecycle.", mandatory: true },
    { clauseRef: "Cl. 5.7",  title: "Performance evaluation (PIMS extension)",                                description: "Augments ISO 27001 Cl. 9 — monitoring/measurement/analysis/evaluation, internal audit and management review extended to cover the PIMS.", mandatory: true },
    { clauseRef: "Cl. 5.8",  title: "Improvement (PIMS extension)",                                            description: "Augments ISO 27001 Cl. 10 — nonconformity/corrective action and continual improvement applied to the PIMS.", mandatory: true },
    { clauseRef: "Cl. 6",    title: "PIMS-specific guidance related to ISO/IEC 27002 controls",               description: "For each of the ISO/IEC 27002 control areas, additional implementation guidance to address the protection of PII. Reuses the 27002 control taxonomy + adds PIMS-specific implementation guidance for each.", mandatory: true },
    { clauseRef: "Cl. 7",    title: "Additional ISO/IEC 27002 guidance for PII controllers",                  description: "Implementation guidance applicable to PII controllers across 27002 control areas, complementing Clause 6.", mandatory: true },
    { clauseRef: "Cl. 8",    title: "Additional ISO/IEC 27002 guidance for PII processors",                   description: "Implementation guidance applicable to PII processors across 27002 control areas, complementing Clause 6.", mandatory: true },
    { clauseRef: "Annex A",  title: "PIMS-specific reference control objectives + controls (PII controllers)", description: "Annex A — 31 controls grouped into: A.7.2 Conditions for collection and processing; A.7.3 Obligations to PII principals (notice, choice, access, correction, erasure, objection); A.7.4 Privacy by design + by default; A.7.5 PII sharing/transfer/disclosure.", mandatory: true },
    { clauseRef: "Annex B",  title: "PIMS-specific reference control objectives + controls (PII processors)", description: "Annex B — 18 controls grouped into: B.8.2 Conditions for collection and processing; B.8.3 Obligations to PII principals; B.8.4 Privacy by design + by default; B.8.5 PII sharing/transfer/disclosure.", mandatory: true },
    { clauseRef: "Annex C",  title: "Mapping to ISO/IEC 29100 (Privacy framework)",                           description: "Informative mapping of the controls in this document to the privacy principles of ISO/IEC 29100. Useful for organisations whose privacy programme is referenced against the 29100 principles.", mandatory: false },
    { clauseRef: "Annex D",  title: "Mapping to the GDPR",                                                     description: "Informative mapping of GDPR (Regulation (EU) 2016/679) Articles to clauses in this document. Helpful for organisations seeking to demonstrate GDPR compliance via ISO 27701 certification.", mandatory: false },
    { clauseRef: "Annex F",  title: "How to apply ISO 27701 to ISO 27001 + ISO 27002",                        description: "Informative guidance on the relationship between ISO 27701 and ISO 27001 / ISO 27002 — how to extend an existing ISMS to a PIMS, and how to interpret 27002 controls in light of privacy obligations.", mandatory: false },
  ],

  // ─── Controls (12 covering PIMS-specific requirements + Annex A + Annex B) ─
  controls: [
    { controlRef: "ISO27701-CTX-001",   title: "PIMS context, scope + controller/processor role determination", description: "Documented determination of the organisation's role (PII controller / PII processor / both) per processing activity, external/internal issues affecting PIMS objectives, PIMS scope statement. Maps Cl. 5.2.",                                                                                       category: "data-protection", evidenceTypes: ["policy","report","attestation"],                       clauseRefs: ["Cl. 5.2"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-LEAD-001",  title: "PIMS policy + privacy roles + responsibilities",                description: "Top-management-approved PIMS policy, DPO / privacy-officer designation, RACI for privacy roles, integration of privacy into the existing ISO 27001 roles framework. Maps Cl. 5.3.",                                                                                                              category: "data-protection", evidenceTypes: ["policy","attestation","report"],                       clauseRefs: ["Cl. 5.3"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-RISK-001",  title: "Privacy risk assessment + treatment + SoA augmentation",       description: "Privacy-risk assessment considering impact on PII principals, treatment plan including Annex A (controller) / Annex B (processor) controls, Statement of Applicability augmented with privacy-specific exclusions + justifications. Maps Cl. 5.4.",                                                category: "data-protection", evidenceTypes: ["report","procedure","attestation","configuration"],   clauseRefs: ["Cl. 5.4"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-COMP-001",  title: "PIMS competence + awareness + training",                       description: "Competence requirements for PIMS roles, awareness programme for privacy obligations, role-specific privacy training, retained training records. Maps Cl. 5.5.",                                                                                                                                      category: "training",        evidenceTypes: ["training_record","report","procedure","attestation"],  clauseRefs: ["Cl. 5.5"],                              riskLevel: "limited" },
    { controlRef: "ISO27701-OP-001",    title: "PIMS operational planning + control",                          description: "Operational planning + control of privacy-related processes; change-management gates that consider impact on PII; documented information retained for PIMS operations. Maps Cl. 5.6.",                                                                                                              category: "data-protection", evidenceTypes: ["procedure","configuration","report","attestation"],   clauseRefs: ["Cl. 5.6"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-EVAL-001",  title: "PIMS performance evaluation + internal audit + mgmt review",   description: "Monitoring/measurement of privacy controls effectiveness, internal-audit programme covering PIMS scope, management review including privacy-specific inputs (incidents, complaints, regulator interactions). Maps Cl. 5.7.",                                                                          category: "data-protection", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Cl. 5.7"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-CI-001",    title: "PIMS continual improvement + nonconformity handling",          description: "Nonconformity register including privacy nonconformities (regulator findings, complaints, data-subject-rights failures), corrective-action plan, continual-improvement objectives. Maps Cl. 5.8.",                                                                                                category: "data-protection", evidenceTypes: ["report","procedure","incident_record","attestation"], clauseRefs: ["Cl. 5.8"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-CTRL-001",  title: "PIMS-specific guidance on ISO 27002 controls",                description: "Implementation of each applicable ISO 27002 control with the PIMS-specific guidance in Cl. 6 applied (e.g. PII-aware access control, privacy-respecting logging, secure disposal of PII media). Maps Cl. 6.",                                                                                       category: "data-protection", evidenceTypes: ["policy","configuration","procedure","attestation"],    clauseRefs: ["Cl. 6"],                                riskLevel: "high"   },
    { controlRef: "ISO27701-CONTROLLER-001",title: "PII controller obligations (Annex A)",                     description: "Implementation of Annex A controls — lawful basis + purpose limitation + minimisation (A.7.2), notice + consent + rights (A.7.3 — access, correction, erasure, objection), privacy by design + by default (A.7.4), PII sharing + transfer + disclosure (A.7.5). Maps Cl. 7 + Annex A.",              category: "data-protection", evidenceTypes: ["policy","procedure","report","attestation"],            clauseRefs: ["Cl. 7","Annex A"],                      riskLevel: "high"   },
    { controlRef: "ISO27701-PROCESSOR-001",title: "PII processor obligations (Annex B)",                       description: "Implementation of Annex B controls — controller-authorisation + customer-agreement (B.8.2), supporting controllers' obligations to PII principals (B.8.3), privacy by design (B.8.4), subcontracted-processing + cross-border-transfer governance (B.8.5). Maps Cl. 8 + Annex B.",                  category: "vendor-management", evidenceTypes: ["contract","procedure","report","attestation"],        clauseRefs: ["Cl. 8","Annex B"],                      riskLevel: "high"   },
    { controlRef: "ISO27701-GDPR-001",  title: "GDPR alignment via Annex D mapping",                            description: "Use of the Annex D mapping to demonstrate how the PIMS satisfies specific GDPR Articles; gap analysis to identify GDPR obligations not directly addressed by Annex A/B; supplementary controls captured in the SoA. Maps Annex D.",                                                                category: "data-protection", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Annex D"],                              riskLevel: "high"   },
    { controlRef: "ISO27701-INTEG-001", title: "Integrated ISMS+PIMS operation (Annex F)",                     description: "Single, integrated ISMS+PIMS where the ISO 27001 ISMS scope extends to cover the PIMS scope; combined risk register, single SoA covering both 27001 Annex A + 27701 Annex A/B, joint internal-audit programme. Maps Annex F.",                                                                  category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation","configuration"], clauseRefs: ["Annex F"],                              riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "ISO27701-Q-001", text: "Is an ISO 27001 ISMS already established? (ISO 27701 is an extension; without an underlying ISMS, the PIMS path requires building both simultaneously.)",                category: "prerequisite",   riskWeight: 1.0, clauseRefs: ["Annex F"] },
    { questionRef: "ISO27701-Q-002", text: "Has the organisation's role been determined for each processing activity — PII controller, PII processor, or both (Cl. 5.2)?",                                          category: "role",           riskWeight: 1.0, clauseRefs: ["Cl. 5.2"] },
    { questionRef: "ISO27701-Q-003", text: "Is a PIMS policy approved by top management, with privacy roles + responsibilities documented (Cl. 5.3)?",                                                              category: "leadership",     riskWeight: 0.9, clauseRefs: ["Cl. 5.3"] },
    { questionRef: "ISO27701-Q-004", text: "Is a privacy-risk assessment + treatment process operating, considering impact on PII principals, with the SoA augmented for Annex A/B controls (Cl. 5.4)?",            category: "risk",           riskWeight: 1.0, clauseRefs: ["Cl. 5.4"] },
    { questionRef: "ISO27701-Q-005", text: "Is competence + awareness + training for PIMS roles in place (Cl. 5.5)?",                                                                                                category: "competence",     riskWeight: 0.6, clauseRefs: ["Cl. 5.5"] },
    { questionRef: "ISO27701-Q-006", text: "Are operational controls in place for PIMS processes with change-management gates considering PII impact (Cl. 5.6)?",                                                    category: "operations",     riskWeight: 0.7, clauseRefs: ["Cl. 5.6"] },
    { questionRef: "ISO27701-Q-007", text: "Is PIMS performance monitored + audited + reviewed by management (Cl. 5.7)?",                                                                                            category: "evaluation",     riskWeight: 0.7, clauseRefs: ["Cl. 5.7"] },
    { questionRef: "ISO27701-Q-008", text: "Is a privacy-aware nonconformity + corrective-action process operating (Cl. 5.8)?",                                                                                       category: "improvement",    riskWeight: 0.7, clauseRefs: ["Cl. 5.8"] },
    { questionRef: "ISO27701-Q-009", text: "Are ISO 27002 controls implemented with the PIMS-specific guidance in Cl. 6 applied (PII-aware access, logging, disposal etc.)?",                                       category: "iso27002-pims",  riskWeight: 0.8, clauseRefs: ["Cl. 6"] },
    { questionRef: "ISO27701-Q-010", text: "Where acting as a PII controller, are Annex A controls (A.7.2-A.7.5) implemented covering lawful basis, rights, by-design and sharing?",                                  category: "controller",     riskWeight: 1.0, clauseRefs: ["Cl. 7","Annex A"] },
    { questionRef: "ISO27701-Q-011", text: "Where acting as a PII processor, are Annex B controls (B.8.2-B.8.5) implemented covering controller-authorisation, supporting rights, by-design and subcontracted/cross-border processing?", category: "processor",      riskWeight: 1.0, clauseRefs: ["Cl. 8","Annex B"] },
    { questionRef: "ISO27701-Q-012", text: "If GDPR compliance is in scope, is the Annex D mapping used to identify GDPR Articles satisfied + the gap analysis tracked for unaddressed obligations?",                category: "gdpr-mapping",   riskWeight: 0.9, clauseRefs: ["Annex D"] },
    { questionRef: "ISO27701-Q-013", text: "Is the ISMS+PIMS operated as a single integrated programme (combined SoA, joint risk register, joint audit), per Annex F?",                                              category: "integration",    riskWeight: 0.7, clauseRefs: ["Annex F"] },
    { questionRef: "ISO27701-Q-014", text: "Is an accredited certification body engaged for the joint ISO 27001 + 27701 certification?",                                                                            category: "certification",  riskWeight: 0.6, clauseRefs: ["Annex F"] },
  ],
};
