import type { Framework } from "@regunav/types";

/**
 * LGPD — Lei Geral de Proteção de Dados Pessoais (Brazil's General Data
 * Protection Law). Lei nº 13.709, de 14 de agosto de 2018, in force from
 * 18 September 2020. Administrative sanctions provisions in force from
 * 1 August 2021. Enforced by the Autoridade Nacional de Proteção de
 * Dados (ANPD).
 *
 * Sources:
 *   - Lei nº 13.709/2018:
 *     https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm
 *   - ANPD: https://www.gov.br/anpd/en
 *
 * Clauses, controls and questions below cite the published text. They
 * are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const LGPD_BRAZIL: Framework = {
  schemaVersion: 1,
  code: "LGPD_BRAZIL",
  name: "Brazil LGPD",
  version: "13.709/2018",
  description:
    "Brazil's General Data Protection Law (LGPD). Applies to any processing of personal data carried out by a natural person or a legal entity, public or private, regardless of the means or country in which the data subject is located, provided that (i) processing is carried out in the national territory; (ii) the processing activity has the objective of offering or supplying goods or services to or processing data of individuals located in the national territory; or (iii) the personal data subject of the processing was collected in the national territory. Establishes 10 principles, 10 legal bases, the rights of the data subject, the obligations of controllers and processors, ANPD oversight, and administrative sanctions up to 2% of revenues (capped at BRL 50m per infraction).",
  jurisdiction: ["BR"],
  referenceUrl: "https://www.gov.br/anpd/en",

  // ─── Clauses (18 of the most-cited Articles) ─────────────────────────────
  clauses: [
    { clauseRef: "Art. 1",    title: "Object",                                                                description: "This Law provides for the processing of personal data, including by digital means, by a natural person or by a public or private legal entity, with the objective of protecting the fundamental rights of freedom and privacy and the free development of the personality of the natural person.", mandatory: true },
    { clauseRef: "Art. 3",    title: "Territorial application",                                                description: "The provisions of this Law apply to any processing of personal data: (I) carried out in the national territory; (II) where the activity of processing has the objective of the offer or supply of goods or services or the processing of data of individuals located in the national territory; or (III) the personal data subject of the processing was collected in the national territory.", mandatory: true },
    { clauseRef: "Art. 5",    title: "Definitions",                                                            description: "Defines 'personal data', 'sensitive personal data', 'anonymised data', 'database', 'controller', 'operator', 'data protection officer (encarregado)', 'processing agents', 'processing', 'anonymisation', 'consent', 'blocking', 'elimination', 'international transfer', 'shared use of data', 'health-related data', 'regulatory body', 'research body', 'data subject'.", mandatory: true },
    { clauseRef: "Art. 6",    title: "Principles",                                                              description: "The activities of processing personal data shall observe good faith and the principles of: (I) purpose; (II) adequacy; (III) necessity; (IV) free access; (V) data quality; (VI) transparency; (VII) security; (VIII) prevention; (IX) non-discrimination; (X) accountability + demonstration. Controller shall be able to demonstrate compliance with each principle.", mandatory: true },
    { clauseRef: "Art. 7",    title: "Legal bases for processing personal data",                                description: "Processing shall be carried out only in one of the following hypotheses: (I) consent of the data subject; (II) compliance with a legal or regulatory obligation; (III) execution of public policies by public administration; (IV) studies by a research body; (V) execution of a contract with the data subject; (VI) regular exercise of rights in judicial proceedings; (VII) protection of life or physical safety; (VIII) protection of health; (IX) legitimate interests of the controller or third party; (X) credit protection.", mandatory: true },
    { clauseRef: "Art. 8",    title: "Consent",                                                                  description: "Consent under Art. 7(I) shall be provided in writing or by other means that demonstrate the manifestation of the will of the data subject. It shall refer to specific purposes; generic authorisations are void. The data subject may revoke consent at any time by express manifestation and through a free and facilitated procedure.", mandatory: true },
    { clauseRef: "Art. 9",    title: "Information to data subjects",                                            description: "The data subject has the right to facilitated access to information on the processing of his or her data, which shall be made available in a clear, adequate and ostensive manner, including: (I) specific purpose; (II) form and duration; (III) identification of the controller; (IV) contact information of the controller; (V) information about the shared use of data; (VI) responsibilities of the agents; (VII) rights of the data subject.", mandatory: true },
    { clauseRef: "Art. 11",   title: "Processing of sensitive personal data",                                   description: "Processing of sensitive personal data shall occur only with the consent of the data subject or his or her legal representative, in a specific and detached manner, for specific purposes; or, without consent, for the hypotheses listed (legal obligation, public administration, research, regular exercise of rights, protection of life, protection of health, fraud-and-security guarantee).", mandatory: true },
    { clauseRef: "Art. 14",   title: "Processing of personal data of children and adolescents",                description: "The processing of personal data of children and adolescents shall be carried out in their best interest. The processing of personal data of children shall be carried out with the specific and prominent consent given by at least one of the parents or the legal representative.", mandatory: true },
    { clauseRef: "Art. 18",   title: "Rights of the data subject",                                              description: "The data subject has the right to obtain from the controller, in relation to the personal data being processed by it, at any time and on request: (I) confirmation of the existence of processing; (II) access to the data; (III) correction of incomplete/inaccurate/outdated data; (IV) anonymisation, blocking or elimination of unnecessary/excessive/non-compliant data; (V) data portability; (VI) elimination of data processed with consent; (VII) information about public/private entities with which the data is shared; (VIII) information about the possibility of not providing consent and consequences; (IX) revocation of consent.", mandatory: true },
    { clauseRef: "Art. 33",   title: "International transfer — hypotheses",                                     description: "International transfer of personal data is permitted only in the following cases: (I) countries that provide an adequate level of protection; (II) suitable guarantees provided by the controller (specific contractual clauses, standard contractual clauses, global corporate norms, regularly issued seals/certificates/codes of conduct); (III) international cooperation with foreign intelligence/investigation/prosecution; (IV) protection of life; (V) ANPD authorisation; (VI) commitment via international agreements; (VII) execution of public policy; (VIII) specific and informed consent of the data subject; (IX) legal/regulatory compliance, contract performance, or regular exercise of rights.", mandatory: true },
    { clauseRef: "Art. 37",   title: "Records of processing activities",                                         description: "The controller and operator shall keep a record of personal data processing operations carried out by them, especially when based on legitimate interest. The ANPD may determine which controllers + operators are obliged + may set requirements for the record's content.", mandatory: true },
    { clauseRef: "Art. 38",   title: "Data protection impact report",                                            description: "The ANPD may determine that the controller shall prepare an impact report on the protection of personal data, including data of a sensitive nature, referring to its data processing operations, in accordance with regulations. The report shall contain a description of the types of data collected, the methodology used for collection and security, the analysis of the controller regarding measures + safeguards + mechanisms for risk mitigation.", mandatory: true },
    { clauseRef: "Art. 41",   title: "Data protection officer (encarregado)",                                    description: "The controller shall appoint a person in charge of the processing of personal data (the 'encarregado'). The identity and contact information of the encarregado shall be publicly disclosed in a clear and objective manner, preferably on the controller's website. Activities: accept complaints and communications from data subjects, receive communications from the ANPD, guide entities + employees, perform other duties.", mandatory: true },
    { clauseRef: "Art. 46-49",title: "Security and good practices",                                              description: "Processing agents shall adopt security, technical and administrative measures capable of protecting personal data from unauthorised accesses and accidental or unlawful situations of destruction/loss/alteration/communication/dissemination. The ANPD may set minimum technical standards. Communication of an incident must be made to the ANPD and the affected data subjects in a reasonable timeframe (currently typically 2 business days in ANPD guidance).", mandatory: true },
    { clauseRef: "Art. 48",   title: "Notification of security incident",                                        description: "The controller shall communicate to the ANPD and to the data subjects the occurrence of a security incident that may pose risk or relevant damage to the data subjects. The communication shall be made within a reasonable time, as defined by the ANPD, and shall include the description, data affected, technical/security measures, risks, reasons for delay (if applicable) and mitigation measures.", mandatory: true },
    { clauseRef: "Art. 52",   title: "Administrative sanctions",                                                description: "Violations of the LGPD shall subject the processing agents to the following administrative sanctions, applicable by the ANPD: (I) warning; (II) simple fine of up to 2% of the revenues of the private legal entity (or its group/conglomerate) in Brazil, in the last financial year (excluding taxes), limited to BRL 50,000,000 per infraction; (III) daily fine; (IV) publicising of the violation; (V) blocking/elimination of the relevant personal data; (VI) partial suspension of the database for up to 6 months; (VII) suspension of the processing activity for up to 6 months; (VIII) partial or total prohibition of the processing activity.", mandatory: true },
    { clauseRef: "Art. 55-A-55-L", title: "Autoridade Nacional de Proteção de Dados (ANPD)",                    description: "ANPD established by Lei nº 13.853/2019 as an indirect public administration body of a special nature. Five-member directing council, deliberative body. Powers: rulemaking, enforcement, investigation, education, cooperation, sanctions, mediation. ANPD became autarchy of special nature by Lei nº 14.460/2022.", mandatory: true },
  ],

  // ─── Controls (12 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "LGPD-PRIN-001",     title: "Article 6 principles implementation",                          description: "Documented mapping of every processing activity to the 10 Art. 6 principles (purpose, adequacy, necessity, free access, data quality, transparency, security, prevention, non-discrimination, accountability + demonstration). Accountability evidence trail demonstrates compliance.",                                                                                                                                category: "data-protection",      evidenceTypes: ["policy","procedure","report","attestation"],         clauseRefs: ["Art. 6"],                            riskLevel: "high"   },
    { controlRef: "LGPD-LB-001",       title: "Legal-basis register (Art. 7 + Art. 11)",                       description: "For every processing operation: declared Art. 7 legal basis (and Art. 11 condition where sensitive data is processed), legitimate-interest balancing test where applicable, retention period + decommissioning trigger.",                                                                                                                                                                                              category: "data-protection",      evidenceTypes: ["report","procedure","attestation","configuration"], clauseRefs: ["Art. 7","Art. 11"],                  riskLevel: "high"   },
    { controlRef: "LGPD-CONS-001",     title: "Consent management (Art. 8)",                                    description: "Specific + detached + free-and-facilitated consent capture in writing or other demonstrable form; revocation as easy as granting; no generic authorisations; for sensitive data a separate consent flow; for children + adolescents specific + prominent parental consent.",                                                                                                                                          category: "data-protection",      evidenceTypes: ["log","screenshot","procedure","configuration"],     clauseRefs: ["Art. 8","Art. 11","Art. 14"],        riskLevel: "high"   },
    { controlRef: "LGPD-NOTICE-001",   title: "Information to data subjects (Art. 9)",                          description: "Clear + adequate + ostensive privacy notice covering specific purpose, form + duration, controller identity + contact, shared-use information, responsibilities of agents, data-subject rights. Updated on material change.",                                                                                                                                                                                            category: "data-protection",      evidenceTypes: ["policy","screenshot","report"],                       clauseRefs: ["Art. 9"],                            riskLevel: "high"   },
    { controlRef: "LGPD-DSR-001",      title: "Data-subject rights workflow (Art. 18)",                         description: "Documented intake + identity-verification + fulfilment workflow for the nine Art. 18 rights (confirmation, access, correction, anonymisation/blocking/elimination, portability, deletion of consent-based data, sharing transparency, consent-consequence info, consent revocation). Default 15-day SLA per ANPD guidance.",                                                                                       category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],            clauseRefs: ["Art. 18"],                           riskLevel: "high"   },
    { controlRef: "LGPD-XBORDER-001",  title: "International transfers (Art. 33)",                              description: "For every international transfer: documented hypothesis under Art. 33 (adequacy / suitable guarantees including SCC + BCR / ANPD authorisation / consent / contract / public policy / etc.); transfer-impact assessment for the destination regime; supplementary measures where the importer cannot guarantee equivalent protection.",                                                                              category: "data-protection",      evidenceTypes: ["contract","report","attestation","configuration"],  clauseRefs: ["Art. 33"],                           riskLevel: "high"   },
    { controlRef: "LGPD-ROP-001",      title: "Records of processing activities (Art. 37)",                     description: "Per-controller + per-operator records covering every processing activity, with attention to legitimate-interest-based processing; reviewed annually + on material change; tracked against ANPD-mandated content where applicable.",                                                                                                                                                                                    category: "data-protection",      evidenceTypes: ["report","configuration","attestation"],              clauseRefs: ["Art. 37"],                           riskLevel: "high"   },
    { controlRef: "LGPD-DPIA-001",     title: "Data-protection impact report (RIPD — Art. 38)",                 description: "RIPD performed where ANPD requires (and proactively for high-risk processing), covering types of data + collection methodology + security + measures + safeguards + risk-mitigation mechanisms; signed off by the encarregado.",                                                                                                                                                                              category: "data-protection",      evidenceTypes: ["dpia","report","attestation","procedure"],          clauseRefs: ["Art. 38"],                           riskLevel: "high"   },
    { controlRef: "LGPD-DPO-001",      title: "Encarregado (Art. 41)",                                          description: "Encarregado designated, identity + contact publicly disclosed (preferably on the website), with documented duties: complaints + ANPD communications + employee guidance.",                                                                                                                                                                                                                                            category: "ai-system-governance", evidenceTypes: ["attestation","report","policy","screenshot"],        clauseRefs: ["Art. 41"],                           riskLevel: "high"   },
    { controlRef: "LGPD-SEC-001",      title: "Security, technical and administrative measures (Art. 46-49)",   description: "Security baseline aligned with ANPD guidance: encryption at rest + in transit, access control, monitoring, incident response, vendor due diligence. Reviewed and refreshed regularly.",                                                                                                                                                                                                                              category: "encryption",          evidenceTypes: ["configuration","log","report","attestation"],        clauseRefs: ["Art. 46-49"],                        riskLevel: "high"   },
    { controlRef: "LGPD-BREACH-001",   title: "ANPD + data-subject breach notification (Art. 48)",              description: "Incident classification + risk assessment per Art. 48; ANPD notification + data-subject communication within a reasonable timeframe (ANPD guidance commonly two business days for high-risk incidents); contents per ANPD template (description, data affected, technical measures, risks, mitigation, delay justification).",                                                                                  category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 48"],                           riskLevel: "high"   },
    { controlRef: "LGPD-ENF-001",      title: "Administrative-sanction risk + ANPD relationship",                description: "Risk register reflects ANPD sanction exposure (warning → fine up to 2% of Brazilian revenue capped at BRL 50m → daily fine → publicising → blocking → suspension → prohibition). ANPD relationship register tracks open investigations, consent decrees, signed conduct-adjustment terms (TAC).",                                                                                                              category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                     clauseRefs: ["Art. 52","Art. 55-A-55-L"],         riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "LGPD-Q-001", text: "Does the processing fall within LGPD territorial scope (carried out in Brazil, offering goods/services to or processing data of individuals in Brazil, or data collected in Brazil) — Art. 3?",                                            category: "applicability",   riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "LGPD-Q-002", text: "Has each processing activity been mapped to the 10 Art. 6 principles (purpose, adequacy, necessity, free access, data quality, transparency, security, prevention, non-discrimination, accountability + demonstration)?",                  category: "principles",      riskWeight: 1.0, clauseRefs: ["Art. 6"] },
    { questionRef: "LGPD-Q-003", text: "Is the Art. 7 legal basis declared for each processing activity (and Art. 11 condition where sensitive data is involved)?",                                                                                                                category: "legal-basis",     riskWeight: 1.0, clauseRefs: ["Art. 7","Art. 11"] },
    { questionRef: "LGPD-Q-004", text: "Where consent is the basis, is it specific, detached, demonstrable, with free + facilitated revocation (Art. 8)?",                                                                                                                          category: "consent",         riskWeight: 0.9, clauseRefs: ["Art. 8"] },
    { questionRef: "LGPD-Q-005", text: "Where children's data is processed, is specific + prominent parental consent captured (Art. 14)?",                                                                                                                                          category: "children",        riskWeight: 0.9, clauseRefs: ["Art. 14"] },
    { questionRef: "LGPD-Q-006", text: "Does the privacy notice cover the Art. 9 information items (purpose, form + duration, controller identity + contact, shared use, responsibilities, data-subject rights)?",                                                                  category: "transparency",    riskWeight: 0.8, clauseRefs: ["Art. 9"] },
    { questionRef: "LGPD-Q-007", text: "Can the nine Art. 18 data-subject rights be fulfilled per ANPD timeframes (typically 15 days)?",                                                                                                                                            category: "rights",          riskWeight: 1.0, clauseRefs: ["Art. 18"] },
    { questionRef: "LGPD-Q-008", text: "For every international transfer, is the Art. 33 hypothesis documented and supplementary measures applied where necessary?",                                                                                                                category: "transfers",       riskWeight: 0.9, clauseRefs: ["Art. 33"] },
    { questionRef: "LGPD-Q-009", text: "Are RoPA (Art. 37) maintained for controllers + operators, reviewed at least annually and on material change?",                                                                                                                            category: "rop",             riskWeight: 0.8, clauseRefs: ["Art. 37"] },
    { questionRef: "LGPD-Q-010", text: "Where ANPD requires (or proactively for high-risk processing) is a RIPD (data-protection impact report) performed and signed off by the encarregado (Art. 38)?",                                                                            category: "ripd",            riskWeight: 0.8, clauseRefs: ["Art. 38"] },
    { questionRef: "LGPD-Q-011", text: "Has an encarregado been designated, with identity + contact publicly disclosed and documented duties (Art. 41)?",                                                                                                                          category: "encarregado",     riskWeight: 0.9, clauseRefs: ["Art. 41"] },
    { questionRef: "LGPD-Q-012", text: "Are security, technical and administrative measures (Art. 46-49) implemented and aligned with ANPD guidance?",                                                                                                                              category: "security",        riskWeight: 0.9, clauseRefs: ["Art. 46-49"] },
    { questionRef: "LGPD-Q-013", text: "Can a security incident be notified to the ANPD and affected data subjects within the ANPD's required timeframe (Art. 48)?",                                                                                                                category: "breach",          riskWeight: 1.0, clauseRefs: ["Art. 48"] },
    { questionRef: "LGPD-Q-014", text: "Is ANPD administrative-sanction exposure (up to 2% of Brazilian revenue, capped at BRL 50m per infraction, plus blocking/suspension/prohibition) reflected in the risk register (Art. 52)?",                                              category: "sanctions",       riskWeight: 0.6, clauseRefs: ["Art. 52"] },
    { questionRef: "LGPD-Q-015", text: "Is the ANPD relationship register tracking open investigations + consent decrees + conduct-adjustment terms (TAC) up to date?",                                                                                                            category: "anpd",            riskWeight: 0.7, clauseRefs: ["Art. 55-A-55-L"] },
  ],
};
