import type { Framework } from "@regunav/types";

/**
 * NIS2 — Directive (EU) 2022/2555 of the European Parliament and of the
 * Council of 14 December 2022 on measures for a high common level of
 * cybersecurity across the Union, repealing the original NIS Directive
 * (Directive (EU) 2016/1148).
 *
 * Source: https://eur-lex.europa.eu/eli/dir/2022/2555/oj
 *
 * Key dates (encoded in the rule-pack manifest at
 * packages/frameworks/manifests/nis2.manifest.json):
 *   2022-12-14 — adopted
 *   2023-01-16 — in force
 *   2024-10-17 — Member-State transposition deadline (national rules
 *                applicable from 2024-10-18)
 *
 * Clauses, controls and questions below cite the published text. They are
 * structural references to the Directive, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const NIS2: Framework = {
  schemaVersion: 1,
  code: "NIS2",
  name: "NIS2 Directive",
  version: "2022/2555",
  description:
    "EU Directive on measures for a high common level of cybersecurity. Applies to medium and large essential and important entities operating in critical sectors (Annexes I + II): energy, transport, banking, financial market infrastructure, health, drinking water, waste water, digital infrastructure, ICT service management, public administration, space, postal services, waste management, manufacturing of critical products, food, digital providers, and research. Requires cybersecurity risk-management measures (Art. 21), incident reporting on a 24h early warning + 72h notification + 1-month final report cadence (Art. 23), supply-chain security and management-body accountability for non-compliance (Art. 20).",
  jurisdiction: ["EU", "EEA"],
  referenceUrl: "https://eur-lex.europa.eu/eli/dir/2022/2555/oj",

  // ─── Clauses (18 of the most-cited Articles + 2 Annexes) ─────────────────
  clauses: [
    { clauseRef: "Art. 1",   title: "Subject matter",                                                description: "This Directive lays down measures that aim to achieve a high common level of cybersecurity across the Union, with a view to improving the functioning of the internal market, including obligations on Member States and cybersecurity risk-management measures and reporting obligations for entities of the kind referred to in Article 2.", mandatory: true },
    { clauseRef: "Art. 2",   title: "Scope",                                                          description: "Applies to public or private entities of a type referred to in Annex I or II which qualify as medium-sized enterprises under Art. 2 of the Annex to Recommendation 2003/361/EC, or which exceed the ceilings for medium-sized enterprises (large entities). Some categories apply regardless of size (e.g. providers of public electronic communications networks, qualified trust service providers, top-level-domain name registries).", mandatory: true },
    { clauseRef: "Art. 3",   title: "Essential and important entities",                              description: "Essential entities: large entities in Annex I sectors plus specific categories regardless of size. Important entities: medium-sized entities in Annex I sectors and all entities in Annex II sectors. Different supervisory regimes apply (Art. 32 vs Art. 33).", mandatory: true },
    { clauseRef: "Art. 7",   title: "National cybersecurity strategy",                                description: "Each Member State shall adopt a national cybersecurity strategy that provides for the strategic objectives, the resources required to achieve those objectives, and appropriate policy and regulatory measures, with a view to achieving and maintaining a high level of cybersecurity.", mandatory: true },
    { clauseRef: "Art. 20",  title: "Governance",                                                      description: "Member States shall ensure that the management bodies of essential and important entities approve the cybersecurity risk-management measures, oversee their implementation, and can be held liable for infringements. Management bodies shall follow training and ensure that employees follow training on a regular basis to gain sufficient knowledge and skills.", mandatory: true },
    { clauseRef: "Art. 21",  title: "Cybersecurity risk-management measures",                         description: "Essential and important entities shall take appropriate and proportionate technical, operational and organisational measures to manage the risks posed to the security of network and information systems. Minimum measures: risk-analysis + security-policy; incident handling; business continuity (backup management + DR); supply-chain security; security in acquisition/development/maintenance; cybersecurity policy effectiveness assessment; basic cyber hygiene + training; cryptography + encryption; HR security + access-control policies + asset management; MFA + secured communications.", mandatory: true },
    { clauseRef: "Art. 22",  title: "Union-level coordinated security risk assessments of critical supply chains", description: "The Cooperation Group, in cooperation with the Commission and ENISA, may carry out coordinated security risk assessments of specific critical ICT services, ICT systems or ICT products supply chains.", mandatory: true },
    { clauseRef: "Art. 23",  title: "Reporting obligations",                                          description: "Significant incident reporting cadence: (a) early warning to the CSIRT or competent authority within 24 hours of becoming aware of the significant incident — indicating if caused by unlawful or malicious acts and if it could have a cross-border impact; (b) incident notification within 72 hours updating the early warning with initial assessment, severity, indicators of compromise; (c) final report not later than one month after the incident notification with detailed description, type of threat or root cause, applied/ongoing mitigation, cross-border impact.", mandatory: true },
    { clauseRef: "Art. 24",  title: "Use of European cybersecurity certification schemes",            description: "In order to demonstrate compliance with particular requirements of Article 21, Member States may require essential and important entities to use particular ICT products, ICT services and ICT processes that are certified under a European cybersecurity certification scheme adopted pursuant to the Cybersecurity Act.", mandatory: true },
    { clauseRef: "Art. 27",  title: "Registry of entities",                                            description: "Entities of the kind referred to in Article 27(1) (DNS service providers, TLD registries, providers of cloud computing services, providers of data centre services, providers of content delivery networks, managed service providers, managed security service providers, providers of online marketplaces / online search engines / social networking services platforms, trust service providers) shall submit a list of specified information to ENISA.", mandatory: true },
    { clauseRef: "Art. 28",  title: "Database of domain name registration data",                       description: "Member States shall require TLD name registries and entities providing domain name registration services to collect and maintain accurate and complete domain name registration data in a dedicated database with due diligence.", mandatory: true },
    { clauseRef: "Art. 30",  title: "Cybersecurity information-sharing arrangements",                  description: "Member States shall ensure that essential and important entities and, where relevant, other entities not falling within the scope of this Directive can exchange amongst themselves, on a voluntary basis, relevant cybersecurity information including information relating to cyber threats, near misses, vulnerabilities, techniques and procedures.", mandatory: true },
    { clauseRef: "Art. 32",  title: "Supervisory and enforcement measures for essential entities",     description: "Competent authorities shall have at least the following powers in respect of essential entities: on-site inspections, off-site supervision, regular and targeted security audits, ad-hoc audits, security scans, requests for information, requests for access to data, information and documentation. Penalties up to €10m or 2% global annual turnover, whichever is higher.", mandatory: true },
    { clauseRef: "Art. 33",  title: "Supervisory and enforcement measures for important entities",     description: "Member States shall provide that the competent authorities, when taking supervisory and enforcement actions in respect of important entities, may use ex-post supervisory measures when provided with evidence, indication or information that an important entity is allegedly not in compliance. Penalties up to €7m or 1.4% global annual turnover, whichever is higher.", mandatory: true },
    { clauseRef: "Art. 34",  title: "General conditions for imposing administrative fines on essential and important entities", description: "Each Member State shall lay down the rules on administrative fines applicable to infringements of Articles 21 and 23. Administrative fines shall be effective, proportionate and dissuasive. Maximum amounts: at least €10m or 2% global annual turnover for essential entities; at least €7m or 1.4% global annual turnover for important entities, whichever is higher.", mandatory: true },
    { clauseRef: "Annex I",  title: "Sectors of high criticality (essential entities)",               description: "Energy (electricity, district heating + cooling, oil, gas, hydrogen); transport (air, rail, water, road); banking; financial market infrastructure; health; drinking water; waste water; digital infrastructure (IXPs, DNS service providers, TLD name registries, cloud computing, data centres, content delivery networks, trust service providers, providers of public electronic communications networks/services); ICT service management (B2B managed service providers + managed security service providers); public administration (central + regional); space.", mandatory: true },
    { clauseRef: "Annex II", title: "Other critical sectors (important entities)",                    description: "Postal and courier services; waste management; manufacture, production and distribution of chemicals; production, processing and distribution of food; manufacturing (medical devices + in-vitro diagnostic medical devices, computer/electronic/optical products, electrical equipment, machinery and equipment n.e.c., motor vehicles/trailers/semi-trailers, other transport equipment); digital providers (online marketplaces, online search engines, social networking services platforms); research.", mandatory: true },
  ],

  // ─── Controls (14 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "NIS2-GOV-001",    title: "Management-body governance + accountability",         description: "Documented management-body approval of the cybersecurity risk-management measures, oversight cadence, training records for board members, defined personal-liability exposure consistent with Member-State transposition of Art. 20.",                                                                                                                                          category: "ai-system-governance", evidenceTypes: ["policy","attestation","training_record","report"],     clauseRefs: ["Art. 20"],                          riskLevel: "high"   },
    { controlRef: "NIS2-RM-001",     title: "Risk analysis + cybersecurity policy",                description: "Documented risk-analysis methodology, current risk register, top-management-approved cybersecurity policy reviewed at least annually and on material change. Maps Art. 21(2)(a).",                                                                                                                                                                                category: "ai-system-governance", evidenceTypes: ["policy","report","procedure","attestation"],            clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-INC-001",    title: "Incident handling capability",                        description: "Incident-handling policy + runbook, classification + escalation procedures, evidence-preservation requirements, post-incident review register. Tied to Art. 23 reporting workflow. Maps Art. 21(2)(b).",                                                                                                                                                          category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 21","Art. 23"],                riskLevel: "high"   },
    { controlRef: "NIS2-BCM-001",    title: "Business continuity + backup + crisis management",   description: "BC/DR plans, backup policy with tested restores, crisis-management organisation, defined RTO/RPO for critical services. Maps Art. 21(2)(c).",                                                                                                                                                                                                                        category: "business-continuity",  evidenceTypes: ["procedure","report","configuration","attestation"],    clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-SC-001",     title: "Supply-chain security",                                description: "Supplier-onboarding due diligence, contractual flow-down of cybersecurity requirements, supplier-risk monitoring, response to supplier-side incidents. Considers Union-coordinated supply-chain risk assessments under Art. 22. Maps Art. 21(2)(d).",                                                                                                                  category: "vendor-management",    evidenceTypes: ["contract","report","attestation","procedure"],         clauseRefs: ["Art. 21","Art. 22"],                riskLevel: "high"   },
    { controlRef: "NIS2-SDLC-001",   title: "Security in acquisition, development + maintenance", description: "Secure-SDLC policy, security in procurement criteria, vulnerability disclosure programme, security maintenance + patch management. Maps Art. 21(2)(e).",                                                                                                                                                                                                                category: "change-management",    evidenceTypes: ["policy","procedure","configuration","report"],         clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-EVAL-001",   title: "Effectiveness assessment of cybersecurity measures",  description: "Defined effectiveness KPIs, internal-audit programme, third-party assurance (penetration tests, red-team exercises), management-review cadence. Maps Art. 21(2)(f).",                                                                                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-HYG-001",    title: "Cyber hygiene + training",                            description: "Mandatory cyber-hygiene practices (patching baseline, asset hygiene, removable-media controls, awareness campaigns) and role-specific cybersecurity training for all employees. Maps Art. 21(2)(g).",                                                                                                                                                                category: "training",            evidenceTypes: ["policy","training_record","report"],                   clauseRefs: ["Art. 21"],                          riskLevel: "limited" },
    { controlRef: "NIS2-CRYP-001",   title: "Cryptography + encryption",                            description: "Cryptography policy with approved algorithms + key lengths, encryption-at-rest + in-transit defaults, lifecycle key management, periodic crypto-agility review. Maps Art. 21(2)(h).",                                                                                                                                                                                  category: "encryption",          evidenceTypes: ["policy","configuration","attestation"],                clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-HR-IAM-001", title: "HR security + access control + asset management",     description: "Workforce screening, role-based access control, asset inventory + classification, joiner-mover-leaver lifecycle. Maps Art. 21(2)(i).",                                                                                                                                                                                                                              category: "identity-access",     evidenceTypes: ["policy","procedure","training_record","configuration"],clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-MFA-001",    title: "MFA + secured communications",                         description: "Multi-factor authentication for privileged access + remote access; secured voice/video/text comms where appropriate; emergency-comms channel for crisis-management use. Maps Art. 21(2)(j).",                                                                                                                                                                          category: "identity-access",     evidenceTypes: ["configuration","procedure","attestation"],             clauseRefs: ["Art. 21"],                          riskLevel: "high"   },
    { controlRef: "NIS2-REP-001",    title: "Significant-incident reporting workflow (24h/72h/1m)", description: "Workflow that delivers an early warning to CSIRT/competent authority within 24 hours, an incident notification within 72 hours, and a final report within one month, per Art. 23. Tracks cross-border impact assessment and unlawful-acts determination.",                                                                                                              category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"],  clauseRefs: ["Art. 23"],                          riskLevel: "high"   },
    { controlRef: "NIS2-CERT-001",   title: "Use of EU cybersecurity certification (Art. 24)",      description: "Inventory of ICT products/services/processes that the Member State has required to be certified under an EU cybersecurity certification scheme; certificates kept current; gap-analysis where certification not yet available.",                                                                                                                                            category: "ai-system-governance", evidenceTypes: ["report","attestation","configuration"],                clauseRefs: ["Art. 24"],                          riskLevel: "limited" },
    { controlRef: "NIS2-REG-001",    title: "ENISA registry + DNS database obligations",            description: "Where Art. 27 applies: submission to ENISA of the specified entity information; where Art. 28 applies: accurate domain-name registration data maintained with due diligence.",                                                                                                                                                                                       category: "ai-system-governance", evidenceTypes: ["report","attestation","configuration"],                clauseRefs: ["Art. 27","Art. 28"],                riskLevel: "limited" },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "NIS2-Q-001",  text: "Does the entity operate in a sector listed in Annex I (essential) or Annex II (important) AND meet the size threshold (Art. 2-3)?",                                                                          category: "applicability", riskWeight: 1.0, clauseRefs: ["Art. 2","Art. 3","Annex I","Annex II"] },
    { questionRef: "NIS2-Q-002",  text: "Has the entity been classified by national competent authorities as essential or important, with the implication for supervision (Art. 32 vs Art. 33)?",                                                    category: "classification", riskWeight: 0.9, clauseRefs: ["Art. 3","Art. 32","Art. 33"] },
    { questionRef: "NIS2-Q-003",  text: "Has the management body approved the cybersecurity risk-management measures and is its training on a regular cadence (Art. 20)?",                                                                          category: "governance",    riskWeight: 1.0, clauseRefs: ["Art. 20"] },
    { questionRef: "NIS2-Q-004",  text: "Are the ten Art. 21(2) minimum measures implemented and reviewed for proportionality + appropriateness?",                                                                                                    category: "rm-measures",   riskWeight: 1.0, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-005",  text: "Is an incident-handling capability with classification, escalation and evidence preservation operating (Art. 21(2)(b))?",                                                                                    category: "incident",      riskWeight: 0.9, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-006",  text: "Are BC/DR plans with tested backup + RTO/RPO per critical service in place (Art. 21(2)(c))?",                                                                                                                category: "bcm",           riskWeight: 0.9, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-007",  text: "Is supply-chain security governed with supplier due-diligence + contractual flow-down + monitoring (Art. 21(2)(d) + Art. 22)?",                                                                              category: "supply-chain",  riskWeight: 0.9, clauseRefs: ["Art. 21","Art. 22"] },
    { questionRef: "NIS2-Q-008",  text: "Is security embedded in acquisition, development and maintenance with vulnerability-disclosure + patch management (Art. 21(2)(e))?",                                                                          category: "sdlc",          riskWeight: 0.7, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-009",  text: "Is effectiveness of cybersecurity measures assessed via KPIs + audits + management review (Art. 21(2)(f))?",                                                                                                  category: "effectiveness", riskWeight: 0.7, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-010",  text: "Are cyber-hygiene practices + role-based cybersecurity training delivered (Art. 21(2)(g))?",                                                                                                                  category: "training",      riskWeight: 0.7, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-011",  text: "Are cryptography + encryption policies + lifecycle key management implemented (Art. 21(2)(h))?",                                                                                                              category: "crypto",        riskWeight: 0.8, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-012",  text: "Are HR security + access control + asset management implemented across joiner-mover-leaver (Art. 21(2)(i))?",                                                                                                category: "hr-iam",        riskWeight: 0.8, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-013",  text: "Is MFA enforced for privileged + remote access, with secured communications channels for crisis use (Art. 21(2)(j))?",                                                                                       category: "mfa",           riskWeight: 0.8, clauseRefs: ["Art. 21"] },
    { questionRef: "NIS2-Q-014",  text: "Can a significant incident be reported via the 24-hour early warning, 72-hour notification, and 1-month final report cadence (Art. 23)?",                                                                    category: "reporting",     riskWeight: 1.0, clauseRefs: ["Art. 23"] },
    { questionRef: "NIS2-Q-015",  text: "Where Member-State law requires use of EU-certified ICT products/services/processes, are required certifications obtained and kept current (Art. 24)?",                                                       category: "certification", riskWeight: 0.5, clauseRefs: ["Art. 24"] },
    { questionRef: "NIS2-Q-016",  text: "Where Art. 27 applies, has the entity submitted the required information to ENISA?",                                                                                                                          category: "registry",      riskWeight: 0.5, clauseRefs: ["Art. 27"] },
    { questionRef: "NIS2-Q-017",  text: "Where Art. 28 applies (TLD registries, domain-name registration services), is accurate domain-name registration data maintained?",                                                                            category: "registry",      riskWeight: 0.5, clauseRefs: ["Art. 28"] },
    { questionRef: "NIS2-Q-018",  text: "Are penalty exposures (≥€10m or 2% turnover for essential; ≥€7m or 1.4% for important — Art. 34) reflected in the risk register and reported to the management body?",                                       category: "penalties",     riskWeight: 0.5, clauseRefs: ["Art. 34"] },
  ],
};
