import type { Framework } from "@regunav/types";

/**
 * NIST Cybersecurity Framework 2.0 (CSF 2.0) — published 2024-02-26 by
 * the US National Institute of Standards and Technology. Voluntary
 * framework providing a taxonomy and outcome-based catalogue of
 * cybersecurity activities applicable to organisations of any size or
 * sector. Major change vs CSF 1.1: addition of the GOVERN function and
 * a deeper Cybersecurity Supply Chain Risk Management (GV.SC) category.
 *
 * Source: https://www.nist.gov/cyberframework
 *
 * Publication is under US government open terms. The clauses below cite
 * each function + category by its CSF 2.0 code and outline.
 */
export const NIST_CSF: Framework = {
  schemaVersion: 1,
  code: "NIST_CSF",
  name: "NIST CSF 2.0",
  version: "2.0",
  description:
    "Voluntary US framework organising cybersecurity activities into six functions — GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER. Each function decomposes into categories with outcome-statement subcategories. Implementation Tiers (Partial, Risk-Informed, Repeatable, Adaptive) and Profiles (Current + Target) provide an organisational-maturity overlay. Suitable for use across critical infrastructure, government and the private sector at any size.",
  jurisdiction: ["US", "INTERNATIONAL"],
  referenceUrl: "https://www.nist.gov/cyberframework",

  // ─── Clauses (22 — every CSF 2.0 category) ──────────────────────────────
  clauses: [
    { clauseRef: "GV.OC",  title: "Organisational Context",                                              description: "The circumstances — mission, stakeholder expectations, dependencies and legal/regulatory/contractual requirements — surrounding the organisation's cybersecurity risk management decisions are understood.", mandatory: true },
    { clauseRef: "GV.RM",  title: "Risk Management Strategy",                                            description: "The organisation's priorities, constraints, risk tolerance and appetite statements, and assumptions are established, communicated, and used to support operational risk decisions.", mandatory: true },
    { clauseRef: "GV.RR",  title: "Roles, Responsibilities and Authorities",                              description: "Cybersecurity roles, responsibilities and authorities to foster accountability, performance assessment and continuous improvement are established and communicated.", mandatory: true },
    { clauseRef: "GV.PO",  title: "Policy",                                                                description: "Organisational cybersecurity policy is established, communicated and enforced.", mandatory: true },
    { clauseRef: "GV.OV",  title: "Oversight",                                                              description: "Results of organisation-wide cybersecurity risk management activities and performance are used to inform, improve and adjust the risk-management strategy.", mandatory: true },
    { clauseRef: "GV.SC",  title: "Cybersecurity Supply Chain Risk Management",                            description: "Cyber supply chain risk management processes are identified, established, managed, monitored and improved by organisational stakeholders.", mandatory: true },

    { clauseRef: "ID.AM",  title: "Asset Management",                                                      description: "Assets (e.g. data, hardware, software, systems, facilities, services, people) that enable the organisation to achieve business purposes are identified and managed consistent with their relative importance to organisational objectives and the organisation's risk strategy.", mandatory: true },
    { clauseRef: "ID.RA",  title: "Risk Assessment",                                                      description: "The cybersecurity risk to the organisation, assets and individuals is understood by the organisation.", mandatory: true },
    { clauseRef: "ID.IM",  title: "Improvement",                                                            description: "Improvements to organisational cybersecurity risk management processes, procedures and activities are identified across all CSF functions.", mandatory: true },

    { clauseRef: "PR.AA",  title: "Identity Management, Authentication and Access Control",                description: "Access to physical and logical assets and associated facilities is limited to authorised users, processes and devices, and is managed consistent with the assessed risk of unauthorised access.", mandatory: true },
    { clauseRef: "PR.AT",  title: "Awareness and Training",                                                description: "The organisation's personnel and partners are provided cybersecurity awareness education and are trained to perform their cybersecurity-related duties and responsibilities consistent with related policies, procedures and agreements.", mandatory: true },
    { clauseRef: "PR.DS",  title: "Data Security",                                                          description: "Data is managed consistent with the organisation's risk strategy to protect the confidentiality, integrity and availability of information.", mandatory: true },
    { clauseRef: "PR.PS",  title: "Platform Security",                                                      description: "The hardware, software (e.g. firmware, operating systems, applications) and services of physical and virtual platforms are managed consistent with the organisation's risk strategy.", mandatory: true },
    { clauseRef: "PR.IR",  title: "Technology Infrastructure Resilience",                                   description: "Security architectures are managed with the organisation's risk strategy to protect asset confidentiality, integrity and availability, and organisational resilience.", mandatory: true },

    { clauseRef: "DE.CM",  title: "Continuous Monitoring",                                                  description: "Assets are monitored to find anomalies, indicators of compromise and other potentially adverse events.", mandatory: true },
    { clauseRef: "DE.AE",  title: "Adverse Event Analysis",                                                 description: "Anomalies, indicators of compromise and other potentially adverse events are analysed to characterise the events and detect cybersecurity incidents.", mandatory: true },

    { clauseRef: "RS.MA",  title: "Incident Management",                                                    description: "Responses to detected cybersecurity incidents are managed.", mandatory: true },
    { clauseRef: "RS.AN",  title: "Incident Analysis",                                                       description: "Investigations are conducted to ensure effective response and support forensics and recovery activities.", mandatory: true },
    { clauseRef: "RS.CO",  title: "Incident Response Reporting and Communication",                          description: "Response activities are coordinated with internal and external stakeholders as required by laws, regulations, or policies.", mandatory: true },
    { clauseRef: "RS.MI",  title: "Incident Mitigation",                                                     description: "Activities are performed to prevent expansion of an event and to mitigate its effects.", mandatory: true },

    { clauseRef: "RC.RP",  title: "Incident Recovery Plan Execution",                                       description: "Restoration activities are performed to ensure operational availability of systems and services affected by cybersecurity incidents.", mandatory: true },
    { clauseRef: "RC.CO",  title: "Incident Recovery Communication",                                        description: "Restoration activities are coordinated with internal and external parties.", mandatory: true },
  ],

  // ─── Controls (15 covering each function's categories) ────────────────────
  controls: [
    { controlRef: "NIST-CSF-GV-001",  title: "Cybersecurity governance — context + strategy + RR + policy + oversight", description: "Documented organisational context (mission, stakeholders, dependencies, legal reqs); risk-management strategy with appetite/tolerance; cybersecurity roles + responsibilities; organisational cybersecurity policy; oversight cadence that feeds back into strategy. Maps GV.OC/GV.RM/GV.RR/GV.PO/GV.OV.", category: "ai-system-governance", evidenceTypes: ["policy","attestation","report","procedure"],            clauseRefs: ["GV.OC","GV.RM","GV.RR","GV.PO","GV.OV"], riskLevel: "high"   },
    { controlRef: "NIST-CSF-GV-002",  title: "Cybersecurity supply chain risk management",                              description: "Cyber-SCRM processes: supplier risk assessment, contractual cybersecurity provisions, incident-reporting expectations, ongoing monitoring + exit-strategy. New in CSF 2.0. Maps GV.SC.",                                                                                                                                                                              category: "vendor-management",   evidenceTypes: ["contract","report","procedure","attestation"],         clauseRefs: ["GV.SC"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-ID-001",  title: "Asset management",                                                          description: "Inventory of data, hardware, software, systems, facilities, services + people; classification by importance to mission; lifecycle management. Maps ID.AM.",                                                                                                                                                                                                  category: "ai-system-governance", evidenceTypes: ["configuration","report","attestation"],                clauseRefs: ["ID.AM"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-ID-002",  title: "Risk assessment + improvement",                                              description: "Periodic + change-triggered cybersecurity risk assessment; identified improvements registered + tracked across all functions. Maps ID.RA + ID.IM.",                                                                                                                                                                                                          category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["ID.RA","ID.IM"],                          riskLevel: "high"   },
    { controlRef: "NIST-CSF-PR-001",  title: "Identity + authentication + access control (PR.AA)",                       description: "IAM lifecycle, authentication with MFA on privileged + remote access, least-privilege + periodic reviews of physical + logical access. Maps PR.AA.",                                                                                                                                                                                                       category: "identity-access",     evidenceTypes: ["configuration","log","procedure","attestation"],       clauseRefs: ["PR.AA"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-PR-002",  title: "Awareness + training (PR.AT)",                                              description: "Role-based cybersecurity training, phishing exercises, awareness campaigns, training records retained. Maps PR.AT.",                                                                                                                                                                                                                                              category: "training",            evidenceTypes: ["training_record","report","procedure"],                clauseRefs: ["PR.AT"],                                  riskLevel: "limited" },
    { controlRef: "NIST-CSF-PR-003",  title: "Data security (PR.DS)",                                                      description: "Encryption at rest + in transit, integrity controls, data-classification policy, data-handling procedures aligned with risk strategy. Maps PR.DS.",                                                                                                                                                                                                       category: "encryption",          evidenceTypes: ["configuration","policy","procedure","attestation"],    clauseRefs: ["PR.DS"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-PR-004",  title: "Platform security + infrastructure resilience (PR.PS + PR.IR)",            description: "Configuration management, patch + vulnerability mgmt, secure baselines, network segmentation, redundancy + resilience patterns. Maps PR.PS + PR.IR.",                                                                                                                                                                                                          category: "vulnerability-management", evidenceTypes: ["configuration","report","procedure"],              clauseRefs: ["PR.PS","PR.IR"],                          riskLevel: "high"   },
    { controlRef: "NIST-CSF-DE-001",  title: "Continuous monitoring (DE.CM)",                                              description: "Centralised log collection + SIEM, threshold-based alerting, asset-coverage SLO, periodic review of detection coverage. Maps DE.CM.",                                                                                                                                                                                                                       category: "logging-monitoring",  evidenceTypes: ["configuration","log","report","attestation"],         clauseRefs: ["DE.CM"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-DE-002",  title: "Adverse event analysis (DE.AE)",                                             description: "Triage + correlation of anomalies + IOCs, threshold-based incident-declaration playbook. Maps DE.AE.",                                                                                                                                                                                                                                                              category: "incident-response",   evidenceTypes: ["procedure","log","report"],                            clauseRefs: ["DE.AE"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-RS-001",  title: "Incident management + analysis (RS.MA + RS.AN)",                            description: "Incident-response runbook, on-call rotation, evidence preservation + forensic analysis, severity classification. Maps RS.MA + RS.AN.",                                                                                                                                                                                                                        category: "incident-response",   evidenceTypes: ["procedure","incident_record","report","attestation"],  clauseRefs: ["RS.MA","RS.AN"],                          riskLevel: "high"   },
    { controlRef: "NIST-CSF-RS-002",  title: "Incident reporting + communication (RS.CO)",                                 description: "Communication plan to internal + external stakeholders incl. regulators per legal/contractual obligations, customer notification templates, status-page workflow. Maps RS.CO.",                                                                                                                                                                                category: "incident-response",   evidenceTypes: ["procedure","report","screenshot","attestation"],       clauseRefs: ["RS.CO"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-RS-003",  title: "Incident mitigation (RS.MI)",                                                 description: "Containment + eradication procedures, blast-radius limitation, change-control during incident response. Maps RS.MI.",                                                                                                                                                                                                                                            category: "incident-response",   evidenceTypes: ["procedure","log","incident_record"],                  clauseRefs: ["RS.MI"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-RC-001",  title: "Incident recovery plan execution (RC.RP)",                                  description: "Recovery procedures with tested restores; RTO/RPO per system; post-incident review feeding ID.IM. Maps RC.RP.",                                                                                                                                                                                                                                                  category: "business-continuity", evidenceTypes: ["procedure","report","configuration","attestation"],   clauseRefs: ["RC.RP"],                                  riskLevel: "high"   },
    { controlRef: "NIST-CSF-RC-002",  title: "Recovery communication (RC.CO)",                                              description: "Internal + external recovery communications, customer-facing recovery updates, regulator reporting where required. Maps RC.CO.",                                                                                                                                                                                                                              category: "incident-response",   evidenceTypes: ["procedure","report","screenshot"],                     clauseRefs: ["RC.CO"],                                  riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "NIST-CSF-Q-001", text: "Is organisational context (mission, stakeholders, dependencies, legal requirements) documented (GV.OC)?",                                                                          category: "govern",   riskWeight: 0.7, clauseRefs: ["GV.OC"] },
    { questionRef: "NIST-CSF-Q-002", text: "Is a cybersecurity risk-management strategy with appetite/tolerance established (GV.RM)?",                                                                                          category: "govern",   riskWeight: 0.9, clauseRefs: ["GV.RM"] },
    { questionRef: "NIST-CSF-Q-003", text: "Are cybersecurity roles, responsibilities and authorities documented and communicated (GV.RR)?",                                                                                    category: "govern",   riskWeight: 0.8, clauseRefs: ["GV.RR"] },
    { questionRef: "NIST-CSF-Q-004", text: "Is an organisational cybersecurity policy established, communicated and enforced (GV.PO)?",                                                                                          category: "govern",   riskWeight: 0.8, clauseRefs: ["GV.PO"] },
    { questionRef: "NIST-CSF-Q-005", text: "Are results of cybersecurity risk-management activities used to inform + adjust the strategy (GV.OV)?",                                                                              category: "govern",   riskWeight: 0.7, clauseRefs: ["GV.OV"] },
    { questionRef: "NIST-CSF-Q-006", text: "Is a Cybersecurity Supply Chain Risk Management programme established (GV.SC)? (NEW IN 2.0)",                                                                                       category: "govern",   riskWeight: 1.0, clauseRefs: ["GV.SC"] },
    { questionRef: "NIST-CSF-Q-007", text: "Is an asset inventory (data, hardware, software, systems, facilities, services, people) maintained + classified (ID.AM)?",                                                          category: "identify", riskWeight: 0.9, clauseRefs: ["ID.AM"] },
    { questionRef: "NIST-CSF-Q-008", text: "Is cybersecurity risk to the organisation, assets and individuals assessed at planned intervals + on material change (ID.RA)?",                                                     category: "identify", riskWeight: 0.9, clauseRefs: ["ID.RA"] },
    { questionRef: "NIST-CSF-Q-009", text: "Is an improvement programme operating across all functions (ID.IM)?",                                                                                                                category: "identify", riskWeight: 0.6, clauseRefs: ["ID.IM"] },
    { questionRef: "NIST-CSF-Q-010", text: "Are IAM + authentication + access control implemented across logical + physical assets (PR.AA)?",                                                                                   category: "protect",  riskWeight: 0.9, clauseRefs: ["PR.AA"] },
    { questionRef: "NIST-CSF-Q-011", text: "Is cybersecurity awareness + role-based training delivered (PR.AT)?",                                                                                                                category: "protect",  riskWeight: 0.6, clauseRefs: ["PR.AT"] },
    { questionRef: "NIST-CSF-Q-012", text: "Are data-security controls (encryption, integrity, classification) implemented (PR.DS)?",                                                                                            category: "protect",  riskWeight: 0.9, clauseRefs: ["PR.DS"] },
    { questionRef: "NIST-CSF-Q-013", text: "Are platform-security + infrastructure-resilience controls (config mgmt, patch mgmt, segmentation, redundancy) in place (PR.PS + PR.IR)?",                                          category: "protect",  riskWeight: 0.8, clauseRefs: ["PR.PS","PR.IR"] },
    { questionRef: "NIST-CSF-Q-014", text: "Is continuous monitoring of assets implemented to find anomalies + IOCs (DE.CM)?",                                                                                                  category: "detect",   riskWeight: 0.9, clauseRefs: ["DE.CM"] },
    { questionRef: "NIST-CSF-Q-015", text: "Is adverse-event analysis (triage, correlation, incident-declaration) operating (DE.AE)?",                                                                                          category: "detect",   riskWeight: 0.9, clauseRefs: ["DE.AE"] },
    { questionRef: "NIST-CSF-Q-016", text: "Is an incident-management + analysis capability operating (RS.MA + RS.AN)?",                                                                                                        category: "respond",  riskWeight: 0.9, clauseRefs: ["RS.MA","RS.AN"] },
    { questionRef: "NIST-CSF-Q-017", text: "Is incident-response reporting + stakeholder communication established per legal + contractual obligations (RS.CO)?",                                                                category: "respond",  riskWeight: 0.9, clauseRefs: ["RS.CO"] },
    { questionRef: "NIST-CSF-Q-018", text: "Are incident-mitigation procedures (containment + eradication) operating (RS.MI)?",                                                                                                  category: "respond",  riskWeight: 0.8, clauseRefs: ["RS.MI"] },
    { questionRef: "NIST-CSF-Q-019", text: "Is an incident-recovery plan operating with tested restores + per-system RTO/RPO (RC.RP)?",                                                                                          category: "recover",  riskWeight: 0.9, clauseRefs: ["RC.RP"] },
    { questionRef: "NIST-CSF-Q-020", text: "Is recovery communication coordinated with internal + external stakeholders (RC.CO)?",                                                                                              category: "recover",  riskWeight: 0.7, clauseRefs: ["RC.CO"] },
  ],
};
