import type { Framework } from "@regunav/types";

/**
 * NIST AI Risk Management Framework 1.0 (AI RMF 1.0) — NIST AI 100-1.
 * Voluntary US framework providing a process for incorporating
 * trustworthiness considerations into the design, development, use and
 * evaluation of AI products, services and systems.
 *
 * Source: https://www.nist.gov/itl/ai-risk-management-framework
 * Published 2023-01-26 (and accompanied by the NIST AI RMF Playbook and
 * Generative AI Profile NIST AI 600-1).
 *
 * Publication is under US government open terms; references below cite
 * each function + category by code and outline. NIST encourages
 * implementers to publish their own profiles aligned with the RMF.
 */
export const NIST_AI_RMF: Framework = {
  schemaVersion: 1,
  code: "NIST_AI_RMF",
  name: "NIST AI Risk Management Framework",
  version: "1.0",
  description:
    "Voluntary US framework for managing risks posed by AI systems. Organises trustworthy-AI work into four core functions — GOVERN (organisational culture, policies, accountability), MAP (context, AI capabilities + use, impact identification), MEASURE (analysis, testing, tracking), MANAGE (prioritised risk response across the lifecycle). Each function decomposes into categories with subcategories. Outcomes — validity + reliability, safety, security + resilience, accountability + transparency, explainability + interpretability, privacy enhancement, fairness with managed bias — characterise trustworthy AI.",
  jurisdiction: ["US", "INTERNATIONAL"],
  referenceUrl: "https://www.nist.gov/itl/ai-risk-management-framework",

  // ─── Clauses (function categories — 19 covering GOVERN/MAP/MEASURE/MANAGE) ─
  clauses: [
    { clauseRef: "GOVERN-1.1", title: "Legal + regulatory requirements involving AI are understood, managed and documented", description: "The organisation understands and documents the legal and regulatory requirements involving AI; processes are in place to maintain awareness and address compliance.", mandatory: true },
    { clauseRef: "GOVERN-1.2", title: "Characteristics of trustworthy AI integrated into organisational policies, processes, procedures and practices", description: "Policies and procedures embed the trustworthy-AI characteristics (validity + reliability, safety, security + resilience, accountability + transparency, explainability + interpretability, privacy enhancement, fairness with managed bias).", mandatory: true },
    { clauseRef: "GOVERN-2",   title: "Accountability structures for AI risk decisions",                                       description: "Roles, responsibilities and lines of communication for AI risk-management decisions are defined, with delegations of authority documented. Boards and executives understand their accountability for AI outcomes.", mandatory: true },
    { clauseRef: "GOVERN-3",   title: "Workforce diversity, equity, inclusion and accessibility processes",                    description: "Workforce diversity, equity, inclusion and accessibility considerations are prioritised in the AI lifecycle to support trustworthy-AI characteristics and to address potential disparate impacts.", mandatory: true },
    { clauseRef: "GOVERN-4",   title: "Organisational teams committed to a safety-first culture",                              description: "Organisational teams are committed to a culture that considers and communicates AI risk. Documentation, training and incentives reinforce safety-first decision-making across the lifecycle.", mandatory: true },
    { clauseRef: "GOVERN-5",   title: "Processes for stakeholder engagement",                                                    description: "Processes are in place for robust stakeholder engagement — including third parties, impacted communities and affected individuals — across the AI lifecycle.", mandatory: true },
    { clauseRef: "GOVERN-6",   title: "Address AI risks and benefits from third-party software, data and services",            description: "Policies and procedures address AI risks and benefits arising from third-party AI software, data and services across the supply chain.", mandatory: true },

    { clauseRef: "MAP-1",      title: "Context established and understood",                                                      description: "Context is established and understood — intended purposes, settings of deployment, anticipated mission/business uses, expected benefits, foreseeable misuse and stakeholders.", mandatory: true },
    { clauseRef: "MAP-2",      title: "Categorisation of the AI system",                                                          description: "The AI system is categorised — task category, AI capabilities (perception, learning, generation etc.), data dependencies, intended scope of use, organisational role of the system.", mandatory: true },
    { clauseRef: "MAP-3",      title: "AI capabilities, targeted usage, goals and expected benefits + costs",                    description: "AI capabilities, targeted usage, goals and expected benefits and costs (against alternatives + against the no-AI baseline) are characterised + documented.", mandatory: true },
    { clauseRef: "MAP-4",      title: "Risks and benefits mapped for all components of the AI system, including third-party software and data", description: "Risks and benefits are mapped for all components of the AI system — including third-party software and data — across the lifecycle.", mandatory: true },
    { clauseRef: "MAP-5",      title: "Impacts to individuals, groups, communities, organisations and society are characterised", description: "Impacts to individuals, groups, communities, organisations and society are characterised, including likelihood, magnitude and reversibility of harms.", mandatory: true },

    { clauseRef: "MEASURE-1",  title: "Appropriate methods + metrics identified and applied",                                    description: "Appropriate methods and metrics are identified and applied to assess the trustworthy-AI characteristics — including measurement uncertainty and limitations of the chosen approach.", mandatory: true },
    { clauseRef: "MEASURE-2",  title: "AI systems are evaluated for trustworthy characteristics",                                description: "AI systems are evaluated for trustworthy-AI characteristics — including validity, reliability, safety, security, fairness, privacy, explainability — pre-deployment and on ongoing basis.", mandatory: true },
    { clauseRef: "MEASURE-3",  title: "Mechanisms for tracking identified AI risks over time",                                   description: "Mechanisms for tracking identified AI risks over time are in place — including risks that emerge through deployment and from changes in data, threats, regulation or stakeholders.", mandatory: true },
    { clauseRef: "MEASURE-4",  title: "Feedback about efficacy of measurement",                                                   description: "Feedback about efficacy of measurement is gathered and assessed — including feedback from operators, end users, affected communities, and from regulators or external auditors.", mandatory: true },

    { clauseRef: "MANAGE-1",   title: "AI risks identified by MAP + MEASURE are prioritised, responded to and managed",          description: "AI risks identified by the MAP + MEASURE functions are prioritised based on impact, likelihood and resources required; responses are selected, planned and executed.", mandatory: true },
    { clauseRef: "MANAGE-2",   title: "Strategies to maximise AI benefits + minimise negative impacts are planned, implemented and documented", description: "Strategies to maximise AI benefits and minimise negative impacts are planned, implemented and documented across the lifecycle — including model selection, training-data curation, deployment safeguards.", mandatory: true },
    { clauseRef: "MANAGE-3",   title: "AI risks + benefits from third-party entities are managed",                                description: "AI risks and benefits arising from third-party entities (suppliers, partners, customers) are managed through contractual + operational controls.", mandatory: true },
    { clauseRef: "MANAGE-4",   title: "Risk treatments are documented and monitored for effectiveness; incident response activities are in place", description: "Risk treatments are documented; their effectiveness is monitored; incident-response activities — including escalation, mitigation, communication and learning — are in place and exercised.", mandatory: true },
  ],

  // ─── Controls (13 covering each function's categories) ────────────────────
  controls: [
    { controlRef: "NIST-AI-RMF-GOV-001",   title: "AI legal + regulatory awareness register",                              description: "Centralised inventory of AI legal/regulatory requirements applicable to the organisation's AI systems, with assigned owners and update cadence. Maps GOVERN-1.1.",                                                                                          category: "ai-system-governance", evidenceTypes: ["policy","report","attestation"],                       clauseRefs: ["GOVERN-1.1"],                            riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-GOV-002",   title: "Trustworthy-AI characteristics embedded in policies + processes",       description: "Documentation that each of the seven trustworthy-AI characteristics has been embedded into AI policies, processes, procedures and practices. Maps GOVERN-1.2.",                                                                                          category: "ai-system-governance", evidenceTypes: ["policy","procedure","report"],                         clauseRefs: ["GOVERN-1.2"],                            riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-GOV-003",   title: "Accountability structure + RACI for AI decisions",                       description: "Documented roles, responsibilities and authorities for AI decisions; RACI matrix; board + executive accountability statements. Maps GOVERN-2.",                                                                                                              category: "ai-system-governance", evidenceTypes: ["policy","attestation","report"],                       clauseRefs: ["GOVERN-2"],                              riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-GOV-004",   title: "Workforce diversity + equity + inclusion + safety-culture programme",   description: "Diversity/equity/inclusion/accessibility integrated into AI hiring + design + review; safety-first culture artefacts (training, incentives, escalation channels). Maps GOVERN-3 + GOVERN-4.",                                                              category: "training",            evidenceTypes: ["policy","training_record","report"],                   clauseRefs: ["GOVERN-3","GOVERN-4"],                  riskLevel: "limited" },
    { controlRef: "NIST-AI-RMF-GOV-005",   title: "Stakeholder engagement + third-party AI governance",                     description: "Stakeholder-engagement processes (impacted communities, end users, regulators) operating across the lifecycle; third-party-AI risk + benefit policy with contractual + operational controls. Maps GOVERN-5 + GOVERN-6.",                                  category: "vendor-management",   evidenceTypes: ["procedure","contract","report","attestation"],         clauseRefs: ["GOVERN-5","GOVERN-6"],                  riskLevel: "high"   },

    { controlRef: "NIST-AI-RMF-MAP-001",   title: "AI system context + categorisation",                                     description: "Per-system documented context (intended purposes, deployment setting, stakeholders), categorisation (task, AI capabilities, data dependencies), characterised capabilities + benefits + costs against alternatives. Maps MAP-1 + MAP-2 + MAP-3.",        category: "ai-system-governance", evidenceTypes: ["report","attestation","configuration"],                clauseRefs: ["MAP-1","MAP-2","MAP-3"],                riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MAP-002",   title: "Risk + benefit mapping including third-party components",                description: "Per-system risk + benefit map covering own and third-party components (software, data, services). Maps MAP-4.",                                                                                                                                              category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation","contract"],          clauseRefs: ["MAP-4"],                                riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MAP-003",   title: "Impact characterisation",                                                  description: "Pre-deployment + ongoing impact characterisation — likelihood, magnitude, reversibility — covering individuals, groups, communities, organisations and society. Maps MAP-5.",                                                                                  category: "ai-system-governance", evidenceTypes: ["fria","report","attestation"],                          clauseRefs: ["MAP-5"],                                riskLevel: "high"   },

    { controlRef: "NIST-AI-RMF-MEAS-001",  title: "Measurement methods + metrics framework",                                description: "Documented methods + metrics framework for the trustworthy-AI characteristics, including measurement uncertainty + limitations of chosen approaches. Maps MEASURE-1.",                                                                                  category: "ai-system-governance", evidenceTypes: ["report","procedure","configuration"],                  clauseRefs: ["MEASURE-1"],                            riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MEAS-002",  title: "Evaluation + ongoing monitoring of trustworthy characteristics",         description: "Pre-deployment evaluation and ongoing monitoring for each trustworthy-AI characteristic; drift + concept-shift detection; periodic re-evaluation cadence. Maps MEASURE-2 + MEASURE-3.",                                                                  category: "logging-monitoring",  evidenceTypes: ["report","log","configuration","attestation"],          clauseRefs: ["MEASURE-2","MEASURE-3"],                riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MEAS-003",  title: "Measurement-efficacy feedback loop",                                       description: "Feedback channels from operators, end users, affected communities, regulators + external auditors on the efficacy of measurement; periodic review + updates. Maps MEASURE-4.",                                                                              category: "ai-system-governance", evidenceTypes: ["procedure","report","attestation"],                    clauseRefs: ["MEASURE-4"],                            riskLevel: "limited" },

    { controlRef: "NIST-AI-RMF-MGE-001",   title: "Risk prioritisation + response",                                            description: "Prioritisation of MAP+MEASURE-identified risks (impact × likelihood × resource), selected response (accept / mitigate / transfer / avoid), planned + executed. Maps MANAGE-1 + MANAGE-2.",                                                                category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["MANAGE-1","MANAGE-2"],                  riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MGE-002",   title: "Third-party + supply-chain AI risk management",                            description: "Operational + contractual controls for third-party AI risk including supplier due diligence, performance monitoring, exit + replacement strategy. Maps MANAGE-3.",                                                                                          category: "vendor-management",   evidenceTypes: ["contract","report","attestation","procedure"],         clauseRefs: ["MANAGE-3"],                             riskLevel: "high"   },
    { controlRef: "NIST-AI-RMF-MGE-003",   title: "Risk-treatment monitoring + AI incident response",                         description: "Documented treatment-effectiveness monitoring, AI incident-response runbook covering escalation, mitigation, communication + learning, exercised at planned intervals. Maps MANAGE-4.",                                                                   category: "incident-response",   evidenceTypes: ["procedure","incident_record","report","attestation"],  clauseRefs: ["MANAGE-4"],                             riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "NIST-AI-RMF-Q-001", text: "Is a centralised inventory of AI legal + regulatory requirements maintained with assigned owners (GOVERN-1.1)?",                                                                  category: "govern",  riskWeight: 0.8, clauseRefs: ["GOVERN-1.1"] },
    { questionRef: "NIST-AI-RMF-Q-002", text: "Are the seven trustworthy-AI characteristics embedded into policies, processes, procedures and practices (GOVERN-1.2)?",                                                          category: "govern",  riskWeight: 0.8, clauseRefs: ["GOVERN-1.2"] },
    { questionRef: "NIST-AI-RMF-Q-003", text: "Are accountability structures + RACI for AI risk decisions documented, with board/executive accountability statements (GOVERN-2)?",                                              category: "govern",  riskWeight: 0.9, clauseRefs: ["GOVERN-2"] },
    { questionRef: "NIST-AI-RMF-Q-004", text: "Are workforce diversity + equity + inclusion + accessibility considerations and a safety-first culture programme operating (GOVERN-3 + GOVERN-4)?",                              category: "govern",  riskWeight: 0.6, clauseRefs: ["GOVERN-3","GOVERN-4"] },
    { questionRef: "NIST-AI-RMF-Q-005", text: "Are stakeholder-engagement + third-party-AI governance processes in place (GOVERN-5 + GOVERN-6)?",                                                                                 category: "govern",  riskWeight: 0.8, clauseRefs: ["GOVERN-5","GOVERN-6"] },
    { questionRef: "NIST-AI-RMF-Q-006", text: "Is per-system context (intended purposes, setting, stakeholders) documented (MAP-1)?",                                                                                            category: "map",     riskWeight: 0.8, clauseRefs: ["MAP-1"] },
    { questionRef: "NIST-AI-RMF-Q-007", text: "Is the AI system categorised (task, capabilities, data dependencies, intended scope) — MAP-2?",                                                                                   category: "map",     riskWeight: 0.7, clauseRefs: ["MAP-2"] },
    { questionRef: "NIST-AI-RMF-Q-008", text: "Are capabilities, targeted usage, expected benefits + costs (incl. against no-AI baseline) characterised (MAP-3)?",                                                                category: "map",     riskWeight: 0.7, clauseRefs: ["MAP-3"] },
    { questionRef: "NIST-AI-RMF-Q-009", text: "Are risks + benefits mapped for all components including third-party software + data (MAP-4)?",                                                                                    category: "map",     riskWeight: 0.9, clauseRefs: ["MAP-4"] },
    { questionRef: "NIST-AI-RMF-Q-010", text: "Are impacts to individuals/groups/communities/organisations/society characterised with likelihood + magnitude + reversibility (MAP-5)?",                                          category: "map",     riskWeight: 1.0, clauseRefs: ["MAP-5"] },
    { questionRef: "NIST-AI-RMF-Q-011", text: "Are methods + metrics for trustworthy-AI characteristics documented (incl. uncertainty + limitations) — MEASURE-1?",                                                              category: "measure", riskWeight: 0.8, clauseRefs: ["MEASURE-1"] },
    { questionRef: "NIST-AI-RMF-Q-012", text: "Are AI systems evaluated for trustworthy characteristics pre-deployment and on an ongoing basis (MEASURE-2)?",                                                                    category: "measure", riskWeight: 1.0, clauseRefs: ["MEASURE-2"] },
    { questionRef: "NIST-AI-RMF-Q-013", text: "Are mechanisms in place to track identified AI risks over time, including drift + emerging threats (MEASURE-3)?",                                                                  category: "measure", riskWeight: 0.9, clauseRefs: ["MEASURE-3"] },
    { questionRef: "NIST-AI-RMF-Q-014", text: "Is feedback on measurement efficacy gathered + assessed (operators, users, affected communities, regulators, auditors) — MEASURE-4?",                                            category: "measure", riskWeight: 0.6, clauseRefs: ["MEASURE-4"] },
    { questionRef: "NIST-AI-RMF-Q-015", text: "Are MAP+MEASURE-identified AI risks prioritised + responded to + managed (MANAGE-1 + MANAGE-2)?",                                                                                  category: "manage",  riskWeight: 1.0, clauseRefs: ["MANAGE-1","MANAGE-2"] },
    { questionRef: "NIST-AI-RMF-Q-016", text: "Are third-party AI risks + benefits managed via contractual + operational controls (MANAGE-3)?",                                                                                   category: "manage",  riskWeight: 0.8, clauseRefs: ["MANAGE-3"] },
    { questionRef: "NIST-AI-RMF-Q-017", text: "Is treatment-effectiveness monitoring + AI incident-response (escalation, mitigation, communication, learning) operating and exercised (MANAGE-4)?",                              category: "manage",  riskWeight: 0.9, clauseRefs: ["MANAGE-4"] },
  ],
};
