import type { Framework } from "@regunav/types";

/**
 * PCI DSS v4.0.1 — Payment Card Industry Data Security Standard.
 * Published by the PCI Security Standards Council. Mandatory for any
 * entity that stores, processes or transmits cardholder data (CHD) or
 * sensitive authentication data (SAD), as a contractual obligation to
 * the participating payment brands.
 *
 * Source: https://www.pcisecuritystandards.org/document_library/
 *
 * Twelve high-level requirements grouped into six control objectives:
 *   Build + Maintain a Secure Network and Systems (Req 1, 2)
 *   Protect Account Data (Req 3, 4)
 *   Maintain a Vulnerability Management Programme (Req 5, 6)
 *   Implement Strong Access Control Measures (Req 7, 8, 9)
 *   Regularly Monitor and Test Networks (Req 10, 11)
 *   Maintain an Information Security Policy (Req 12)
 *
 * ⚠ The PCI SSC standards document is licensed; references below cite
 * each requirement by number + outline only. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const PCI_DSS: Framework = {
  schemaVersion: 1,
  code: "PCI_DSS",
  name: "PCI DSS 4.0.1",
  version: "4.0.1",
  description:
    "Industry contractual standard for protecting cardholder data. Applies to any entity that stores, processes or transmits cardholder data (PAN, cardholder name, service code, expiration date) or sensitive authentication data (full track, CAV2/CVC2/CVV2/CID, PIN/PIN block). Twelve requirements cover network security, secure configurations, data protection, transmission cryptography, anti-malware, secure SDLC, role-based access, authentication, physical access, logging + monitoring, regular testing, and the information-security programme. Assessor regimes: Qualified Security Assessor (QSA) for Report on Compliance (ROC); Self-Assessment Questionnaire (SAQ) for smaller merchants; Quarterly Approved Scanning Vendor (ASV) scans for external network.",
  jurisdiction: ["INTERNATIONAL"],
  referenceUrl: "https://www.pcisecuritystandards.org/document_library/",

  // ─── Clauses (12 PCI DSS requirements) ───────────────────────────────────
  clauses: [
    { clauseRef: "Req. 1",  title: "Install and maintain network security controls",                                       description: "Network security controls (NSCs) shall be installed, maintained, configured, monitored. Define + document configuration standards for NSCs, restrict inbound + outbound traffic to that which is necessary, manage configuration files securely, review NSC rules at least every six months.", mandatory: true },
    { clauseRef: "Req. 2",  title: "Apply secure configurations to all system components",                                  description: "Establish + apply secure configuration standards to system components (servers, network devices, applications, cloud) covering vendor defaults, system hardening, change-management, wireless environments, primary account number (PAN) and shared-services. Standards shall be consistent with industry-accepted hardening standards.", mandatory: true },
    { clauseRef: "Req. 3",  title: "Protect stored account data",                                                            description: "Account data shall be protected wherever stored. Cardholder data (PAN, cardholder name, expiration date, service code) MUST be rendered unreadable (e.g. via strong cryptography) wherever it is stored. Sensitive authentication data MUST NOT be stored after authorisation, even if encrypted. Retention + disposal policies in place.", mandatory: true },
    { clauseRef: "Req. 4",  title: "Protect cardholder data with strong cryptography during transmission over open public networks", description: "When PANs are transmitted over open public networks, transmission shall use strong cryptography and security protocols (e.g. TLS 1.2+) with a documented inventory of trusted keys + certificates. Only trusted keys and certificates are accepted; certificates not expired or revoked.", mandatory: true },
    { clauseRef: "Req. 5",  title: "Protect all systems and networks from malicious software",                              description: "Deploy and maintain anti-malware mechanisms or processes appropriate for each system component. Mechanisms shall actively run, generate audit logs, and detect known + unknown malware. Periodic evaluations identify components not commonly affected by malware and confirm they remain so.", mandatory: true },
    { clauseRef: "Req. 6",  title: "Develop and maintain secure systems and software",                                      description: "Bespoke + custom software shall be developed securely (training, threat modelling, secure coding, code review). Public-facing web applications shall be protected against web-based attacks (e.g. via automated technical solution detecting + preventing attacks). Vulnerabilities shall be identified + ranked + addressed with a documented timeframe.", mandatory: true },
    { clauseRef: "Req. 7",  title: "Restrict access to system components and cardholder data by business need to know",     description: "Access shall be restricted to system components and cardholder data on a need-to-know basis. Access rights shall be assigned to roles, with documented approval, regular review (at least every six months), removal upon role change or termination. All user accounts shall have access rights consistent with assigned role.", mandatory: true },
    { clauseRef: "Req. 8",  title: "Identify users and authenticate access to system components",                            description: "Unique user IDs for users + administrators (no shared accounts). Strong authentication for all non-console administrative access and remote access — including MFA — and for all user access into the cardholder data environment (CDE) by 2025-03-31. Authentication factors meet defined complexity + lifecycle requirements.", mandatory: true },
    { clauseRef: "Req. 9",  title: "Restrict physical access to cardholder data",                                            description: "Physical access to systems in the cardholder data environment shall be restricted. Visitor management procedures, badge management, media inventory, secure-destruction procedures for media containing cardholder data, controls over point-of-interaction (POI) devices.", mandatory: true },
    { clauseRef: "Req. 10", title: "Log and monitor all access to system components and cardholder data",                   description: "Audit logs capture all individual user access to system components + cardholder data, all actions taken by individuals with administrative privileges, access to audit logs, invalid logical access attempts, changes to identification + authentication credentials, initialisation/stopping/pausing of audit logs. Audit trails secured + reviewed daily + retained at least 12 months (with at least 3 months immediately available). Time synchronisation.", mandatory: true },
    { clauseRef: "Req. 11", title: "Test security of systems and networks regularly",                                        description: "Wireless access points + rogue devices identified at least every three months; internal + external vulnerability scans at least every three months (external by an Approved Scanning Vendor / ASV); internal + external penetration testing at least annually + after any significant change; intrusion-detection / intrusion-prevention mechanisms; change-detection mechanisms.", mandatory: true },
    { clauseRef: "Req. 12", title: "Support information security with organisational policies and programs",                description: "An overall information security policy shall be established, published, maintained + disseminated to all relevant personnel. Security-awareness training; service-provider management; incident-response plan; targeted risk analysis. Customised approach: an entity may meet a requirement by an alternative approach if it adequately addresses the security objective + is documented in a Controls Matrix + Targeted Risk Analysis.", mandatory: true },
  ],

  // ─── Controls (14 mapped to the 12 requirements) ─────────────────────────
  controls: [
    { controlRef: "PCI-R1-001",   title: "Network security controls (NSCs) + segmentation",                description: "NSC inventory + configuration standards; documented network diagrams showing all CDE connections + segmentation boundaries; six-monthly rule review; segmentation testing if the entity uses segmentation to reduce scope. Maps Req 1.",                                                                                                                                                                                category: "data-protection",       evidenceTypes: ["configuration","report","procedure","attestation"],    clauseRefs: ["Req. 1"],   riskLevel: "high"   },
    { controlRef: "PCI-R2-001",   title: "Secure configuration + hardening",                                 description: "System-hardening baselines aligned with industry standards (e.g. CIS Benchmarks), removal of vendor defaults (including passwords + SNMP community strings), unnecessary services disabled, primary account number isolation. Maps Req 2.",                                                                                                                                                                              category: "data-protection",       evidenceTypes: ["configuration","report","attestation"],                clauseRefs: ["Req. 2"],   riskLevel: "high"   },
    { controlRef: "PCI-R3-001",   title: "Protect stored account data (encryption + SAD prohibition)",      description: "PAN rendered unreadable wherever stored (strong cryptography, truncation, tokenisation, one-way hash with salt where appropriate); sensitive authentication data NOT stored post-authorisation; documented retention + secure-destruction policy. Maps Req 3.",                                                                                                                                                          category: "encryption",            evidenceTypes: ["configuration","policy","attestation","report"],       clauseRefs: ["Req. 3"],   riskLevel: "high"   },
    { controlRef: "PCI-R4-001",   title: "Strong cryptography over open public networks",                    description: "PANs transmitted over open public networks protected with strong cryptography (TLS 1.2+ with trusted certificates); inventory of trusted keys + certificates; no expired or revoked certificates accepted. Maps Req 4.",                                                                                                                                                                                                 category: "encryption",            evidenceTypes: ["configuration","report","attestation"],                clauseRefs: ["Req. 4"],   riskLevel: "high"   },
    { controlRef: "PCI-R5-001",   title: "Anti-malware coverage + monitoring",                                description: "Anti-malware mechanisms or alternative processes appropriate for each system component; mechanisms actively running, generating audit logs, detecting known + unknown malware; periodic evaluation of low-risk-component assumption. Maps Req 5.",                                                                                                                                                                category: "vulnerability-management", evidenceTypes: ["configuration","log","report"],                     clauseRefs: ["Req. 5"],   riskLevel: "high"   },
    { controlRef: "PCI-R6-001",   title: "Secure SDLC + web-app protection + vulnerability mgmt",            description: "Secure-coding practices, peer review, threat modelling, training; automated web-application protection (WAF or equivalent technical solution); vulnerability ranking + remediation timeframes per criticality. Maps Req 6.",                                                                                                                                                                                            category: "change-management",     evidenceTypes: ["policy","procedure","configuration","report"],         clauseRefs: ["Req. 6"],   riskLevel: "high"   },
    { controlRef: "PCI-R7-001",   title: "Role-based access on need-to-know",                                 description: "Documented access-roles inventory; documented approval for role assignments; six-monthly review of access rights; immediate removal on role change/termination. Maps Req 7.",                                                                                                                                                                                                                                            category: "identity-access",       evidenceTypes: ["policy","procedure","configuration","log"],            clauseRefs: ["Req. 7"],   riskLevel: "high"   },
    { controlRef: "PCI-R8-001",   title: "Unique IDs + MFA + strong authentication",                          description: "Unique user IDs (no shared accounts); MFA on all non-console administrative + remote access; MFA on all access into the CDE (by 2025-03-31); password + authentication-factor complexity + lifecycle requirements. Maps Req 8.",                                                                                                                                                                                       category: "identity-access",       evidenceTypes: ["configuration","procedure","attestation","log"],       clauseRefs: ["Req. 8"],   riskLevel: "high"   },
    { controlRef: "PCI-R9-001",   title: "Physical access + media + POI device controls",                    description: "Physical access to CDE restricted; visitor management; badge management; media inventory + secure-destruction procedures; POI device inspection programme. Maps Req 9.",                                                                                                                                                                                                                                                  category: "physical-security",     evidenceTypes: ["policy","procedure","screenshot","report"],            clauseRefs: ["Req. 9"],   riskLevel: "high"   },
    { controlRef: "PCI-R10-001",  title: "Audit logging + 12-month retention + time sync",                   description: "Audit logs capture user activity, admin actions, log access, invalid logical access, credential changes, log lifecycle events; logs secured + reviewed at least daily; retained ≥12 months with at least 3 months immediately available; time-synchronisation across all components. Maps Req 10.",                                                                                                                       category: "logging-monitoring",    evidenceTypes: ["log","configuration","report","attestation"],          clauseRefs: ["Req. 10"],  riskLevel: "high"   },
    { controlRef: "PCI-R11-001",  title: "Quarterly vulnerability scans (incl. ASV) + annual penetration testing", description: "Wireless + rogue-device detection at least every 3 months; internal + external vulnerability scans every 3 months (external by an ASV); internal + external penetration testing at least annually + after significant change; IDS/IPS; file-integrity monitoring. Maps Req 11.",                                                                                                                                  category: "vulnerability-management", evidenceTypes: ["report","configuration","log","attestation"],         clauseRefs: ["Req. 11"],  riskLevel: "high"   },
    { controlRef: "PCI-R12-001",  title: "Information security policy + programme + training",                description: "Top-management-approved information-security policy, disseminated to all relevant personnel, reviewed at least annually + on material change; role-based + annual security-awareness training; documented organisational responsibilities. Maps Req 12 (12.1-12.6).",                                                                                                                                                  category: "ai-system-governance",  evidenceTypes: ["policy","training_record","procedure","attestation"],  clauseRefs: ["Req. 12"],  riskLevel: "high"   },
    { controlRef: "PCI-R12-002",  title: "Service-provider management + targeted risk analysis",              description: "Inventory of service providers with which cardholder data is shared; written agreement acknowledging responsibility for cardholder data; service-provider compliance monitoring; periodic targeted risk analysis (TRA) for customised-approach + flexible-frequency requirements. Maps Req 12 (12.8, 12.3).",                                                                                                              category: "vendor-management",     evidenceTypes: ["contract","report","attestation","procedure"],         clauseRefs: ["Req. 12"],  riskLevel: "high"   },
    { controlRef: "PCI-R12-003",  title: "Incident response plan (Req 12.10)",                                  description: "Documented incident-response plan; designated incident-response team; periodic testing of the plan; defined regulatory + payment-brand notification timelines; lessons-learned process. Maps Req 12.10.",                                                                                                                                                                                                                    category: "incident-response",     evidenceTypes: ["procedure","incident_record","report","attestation"],   clauseRefs: ["Req. 12"],  riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "PCI-DSS-Q-001",  text: "Does the entity store, process or transmit cardholder data (PAN, cardholder name, service code, expiration date) or sensitive authentication data (full track, CAV2/CVC2/CVV2/CID, PIN/PIN block)?",                                                category: "applicability",   riskWeight: 1.0, clauseRefs: ["Req. 3"] },
    { questionRef: "PCI-DSS-Q-002",  text: "Are network security controls (NSCs) installed with documented configuration standards + segmentation diagrams + six-monthly rule review (Req 1)?",                                                                                                  category: "network",         riskWeight: 0.9, clauseRefs: ["Req. 1"] },
    { questionRef: "PCI-DSS-Q-003",  text: "Are secure configuration standards applied to all system components, with vendor defaults removed + hardening baselines established (Req 2)?",                                                                                                       category: "configuration",   riskWeight: 0.9, clauseRefs: ["Req. 2"] },
    { questionRef: "PCI-DSS-Q-004",  text: "Is stored PAN rendered unreadable (strong cryptography, truncation, tokenisation), with sensitive authentication data NOT stored post-authorisation (Req 3)?",                                                                                       category: "data-at-rest",    riskWeight: 1.0, clauseRefs: ["Req. 3"] },
    { questionRef: "PCI-DSS-Q-005",  text: "Are PANs transmitted over open public networks protected with strong cryptography (TLS 1.2+) using trusted, non-expired certificates (Req 4)?",                                                                                                       category: "data-in-transit", riskWeight: 1.0, clauseRefs: ["Req. 4"] },
    { questionRef: "PCI-DSS-Q-006",  text: "Are anti-malware mechanisms deployed + active across the environment, with periodic evaluation of low-risk-component assumption (Req 5)?",                                                                                                            category: "anti-malware",    riskWeight: 0.8, clauseRefs: ["Req. 5"] },
    { questionRef: "PCI-DSS-Q-007",  text: "Are secure-coding + threat-modelling + WAF + vulnerability-ranking practices in place for bespoke + custom software (Req 6)?",                                                                                                                       category: "sdlc",            riskWeight: 0.9, clauseRefs: ["Req. 6"] },
    { questionRef: "PCI-DSS-Q-008",  text: "Is access restricted on need-to-know with documented role inventory, approval, six-monthly review, and immediate removal on termination (Req 7)?",                                                                                                  category: "access",          riskWeight: 0.9, clauseRefs: ["Req. 7"] },
    { questionRef: "PCI-DSS-Q-009",  text: "Do all users have unique IDs, with MFA on all non-console admin + remote access AND on all access into the CDE (Req 8 — full MFA on CDE access by 2025-03-31)?",                                                                                    category: "authentication",  riskWeight: 1.0, clauseRefs: ["Req. 8"] },
    { questionRef: "PCI-DSS-Q-010",  text: "Is physical access to the CDE restricted with visitor management, media controls + POI device inspection (Req 9)?",                                                                                                                                  category: "physical",        riskWeight: 0.8, clauseRefs: ["Req. 9"] },
    { questionRef: "PCI-DSS-Q-011",  text: "Are audit logs comprehensive, time-synchronised, retained ≥12 months (3 months immediately available), and reviewed at least daily (Req 10)?",                                                                                                       category: "logging",         riskWeight: 0.9, clauseRefs: ["Req. 10"] },
    { questionRef: "PCI-DSS-Q-012",  text: "Are quarterly internal + external (ASV) vulnerability scans and annual + post-change penetration testing performed, with IDS/IPS + file-integrity monitoring (Req 11)?",                                                                              category: "testing",         riskWeight: 0.9, clauseRefs: ["Req. 11"] },
    { questionRef: "PCI-DSS-Q-013",  text: "Is an information-security policy approved by top management, reviewed annually + on material change, with role-based + annual training (Req 12.1-12.6)?",                                                                                            category: "policy",          riskWeight: 0.8, clauseRefs: ["Req. 12"] },
    { questionRef: "PCI-DSS-Q-014",  text: "Is service-provider management (inventory, written agreement, compliance monitoring, targeted risk analysis) operating (Req 12.3 + 12.8)?",                                                                                                            category: "vendor",          riskWeight: 0.8, clauseRefs: ["Req. 12"] },
    { questionRef: "PCI-DSS-Q-015",  text: "Is an incident-response plan documented, with designated IR team + periodic testing + defined regulator/brand notification timelines (Req 12.10)?",                                                                                                  category: "incident",        riskWeight: 0.8, clauseRefs: ["Req. 12"] },
    { questionRef: "PCI-DSS-Q-016",  text: "Is the assessment regime appropriate to the entity (ROC by a QSA for Level 1; SAQ for smaller merchants; ASV for external vulnerability scans)?",                                                                                                     category: "assessment",      riskWeight: 0.7, clauseRefs: ["Req. 12"] },
  ],
};
