import type { Framework } from "@regunav/types";

/**
 * PIPL — Personal Information Protection Law of the People's Republic
 * of China. Adopted at the 30th meeting of the Standing Committee of
 * the 13th National People's Congress on 20 August 2021, in force from
 * 1 November 2021. The first general comprehensive personal-information
 * statute in China; sits alongside the Cybersecurity Law (CSL, 2017)
 * and the Data Security Law (DSL, 2021).
 *
 * Sources:
 *   - NPC English text:
 *     http://en.npc.gov.cn.cdurl.cn/2021-12/29/c_694559.htm
 *   - Cyberspace Administration of China (CAC):
 *     http://www.cac.gov.cn (regulator)
 *
 * Clauses, controls and questions below cite the published Law by
 * Article. They are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const PIPL_CHINA: Framework = {
  schemaVersion: 1,
  code: "PIPL_CHINA",
  name: "China PIPL",
  version: "2021",
  description:
    "China's comprehensive personal-information protection statute. Applies to processing of personal information of natural persons within China, and extraterritorially where processing outside China is (i) for the purpose of offering goods or services to natural persons within China, or (ii) for analysing or assessing the activities of natural persons within China. Establishes seven processing principles, six legal bases including separate-consent requirements for sensitive personal information + cross-border transfer + automated decision-making, the rights of individuals, the obligations of Personal Information Handlers (PI Handlers) including localisation + CAC security assessment for Critical Information Infrastructure Operators (CIIOs) and large-volume processors, and penalties up to 5% of preceding-year turnover or RMB 50 million.",
  jurisdiction: ["CN"],
  referenceUrl: "http://en.npc.gov.cn.cdurl.cn/2021-12/29/c_694559.htm",

  // ─── Clauses (18 of the most-cited Articles) ─────────────────────────────
  clauses: [
    { clauseRef: "Art. 3",   title: "Territorial application",                                                description: "This Law applies to the processing of personal information of natural persons within the territory of the PRC. It also applies to processing of personal information of natural persons within the territory of the PRC outside the PRC where the processing is (i) for the purpose of providing products or services to natural persons within the territory, (ii) to analyse or evaluate the activities of natural persons within the territory, or (iii) in other circumstances provided by law or administrative regulations.", mandatory: true },
    { clauseRef: "Art. 5",   title: "Principles — lawfulness, legitimacy, necessity, good faith",            description: "Processing of personal information shall comply with the principles of lawfulness, legitimacy and necessity, and in good faith. The processing shall not be carried out by misleading, fraud, coercion or other means.", mandatory: true },
    { clauseRef: "Art. 6",   title: "Principle — purpose limitation + minimisation",                          description: "The processing of personal information shall have a clear and reasonable purpose and shall be limited to the minimum scope necessary to achieve the purpose of processing. Excessive collection of personal information is prohibited.", mandatory: true },
    { clauseRef: "Art. 7",   title: "Principles — openness, accuracy, security, accountability",              description: "Articles 7-9 require openness and transparency, accuracy of personal information, and the adoption of security measures including encryption + de-identification + access control. The PI Handler is accountable and shall take responsibility for the processing.", mandatory: true },
    { clauseRef: "Art. 13",  title: "Legal bases for processing personal information",                        description: "Personal information may be processed only where one of the following applies: (1) the individual's consent has been obtained; (2) necessary for the conclusion or performance of a contract with the individual; (3) necessary to perform statutory duties or obligations; (4) necessary to respond to a public-health emergency or to protect the life/health or property of a natural person in an emergency; (5) for news reporting or public-interest supervision, within a reasonable scope; (6) processing of personal information disclosed by the individual or by other lawful means, within a reasonable scope; (7) other circumstances provided by laws or administrative regulations.", mandatory: true },
    { clauseRef: "Art. 14",  title: "Consent",                                                                  description: "Where personal information is processed based on the consent of an individual, such consent shall be given by the individual under the precondition of full knowledge, on a voluntary and explicit basis. Where laws or administrative regulations provide that separate consent or written consent shall be obtained, such provisions shall be observed. Consent may be withdrawn at any time.", mandatory: true },
    { clauseRef: "Art. 17",  title: "Notice obligations — transparency to individuals",                       description: "Before processing personal information, the PI Handler shall truthfully, accurately and completely inform the individual of: (i) the name and contact information of the PI Handler; (ii) the purpose and methods of processing, and the categories and retention period of personal information; (iii) the methods and procedures for the individual to exercise their rights; (iv) other matters required by law. Updates required where matters change.", mandatory: true },
    { clauseRef: "Art. 24",  title: "Automated decision-making + transparency + opt-out",                     description: "Where personal information is used for automated decision-making, the PI Handler shall ensure the transparency of the decision-making and the fairness and impartiality of the results. The individual shall have the right to request explanation and the right to refuse decisions made solely by automated means that have a significant impact on the individual's rights and interests. Push-notifications + commercial-marketing through automated decision-making shall offer options not targeting personal characteristics or convenient ways to refuse.", mandatory: true },
    { clauseRef: "Art. 28-32", title: "Sensitive personal information",                                        description: "Sensitive PI: information whose leak or unlawful use could easily lead to the infringement of human dignity, or to harm to personal or property safety — including biometrics, religious beliefs, specific identity, medical/health, financial accounts, location tracking, and personal information of minors under 14. Processing requires: specific purpose + sufficient necessity, strict protection measures, separate consent (or written consent if so provided by law), notice of necessity + impact on rights. Processing of minors under 14 requires consent of the parent or other guardian and a special processing rule.", mandatory: true },
    { clauseRef: "Art. 38-43", title: "Cross-border transfer of personal information",                        description: "A PI Handler that needs to provide personal information outside the PRC for business purposes shall satisfy one of: (i) passing a security assessment organised by the CAC; (ii) being certified under personal-information-protection certification by an institution per CAC rules; (iii) entering into a Standard Contract issued by the CAC with the overseas recipient; or (iv) other conditions stipulated by law / regulation / CAC. Critical Information Infrastructure Operators and PI Handlers processing personal information that reaches the volume specified by the CAC shall localise PI in the PRC and pass the CAC security assessment if export is required.", mandatory: true },
    { clauseRef: "Art. 44-50", title: "Rights of individuals",                                                 description: "Individuals have the following rights with respect to their personal information: (Art. 44) right to be informed, right to decide, right to restrict or refuse processing; (Art. 45) right to consult or obtain a copy of personal information; (Art. 46) right to request correction or completion; (Art. 47) right to request deletion in defined circumstances; (Art. 48) right to request explanation of processing rules; (Art. 49) rights inherited by close relatives upon death of the individual; (Art. 50) PI Handler shall establish a convenient channel for accepting + handling individual rights requests; rejection requires reasons; individual may bring legal action.", mandatory: true },
    { clauseRef: "Art. 51",  title: "General obligations of Personal Information Handlers",                    description: "The PI Handler shall, based on the purpose + method of processing, the categories of personal information processed, the impact on individual's rights and the security risks, take the following measures to ensure compliance: formulate internal management systems; classify the personal information; adopt technical security measures (encryption, de-identification, etc.); reasonably determine operational authorisations and provide training; develop and organise the implementation of contingency response plans; and other measures provided by law/regulation.", mandatory: true },
    { clauseRef: "Art. 52",  title: "Designation of a person responsible for personal information protection", description: "A PI Handler that processes personal information meeting the volume threshold prescribed by the CAC shall designate a 'Personal Information Protection Officer' (PIPO) responsible for supervising the processing activities and the protection measures taken. The name + contact information of the PIPO shall be reported to the CAC.", mandatory: true },
    { clauseRef: "Art. 53",  title: "Local representative for overseas PI Handlers",                            description: "Where an overseas PI Handler is subject to Art. 3(2) (extraterritorial application), it shall establish a dedicated entity or designate a representative within the territory of the PRC responsible for matters related to the personal information it processes, and shall submit the name + contact information of the entity or the representative to the relevant department performing personal-information-protection duties.", mandatory: true },
    { clauseRef: "Art. 54-56", title: "Audit + Personal Information Protection Impact Assessment (PIPIA)",     description: "PI Handlers shall regularly audit their processing activities for compliance. A Personal Information Protection Impact Assessment is required prior to: processing of sensitive personal information; use of personal information for automated decision-making; entrusting processing to a third party, providing personal information to another PI Handler, or making personal information public; providing personal information outside the PRC; or other processing activities with a major impact on individuals. PIPIA records retained for at least 3 years.", mandatory: true },
    { clauseRef: "Art. 57",  title: "Breach notification",                                                      description: "In the event of (or possibility of) leakage, tampering, or loss of personal information, the PI Handler shall immediately take remedial measures and notify the relevant department performing personal-information-protection duties + the individuals concerned. If the measures taken can effectively avoid harm caused by the information-security incident, the PI Handler may be exempted from notifying the individuals — however, if the department of personal-information-protection duties believes that harm may have been caused, it may require the PI Handler to notify the individuals.", mandatory: true },
    { clauseRef: "Art. 66-67",title: "Penalties + administrative liability",                                    description: "Violations may be punished by a warning, confiscation of unlawful income, an order to suspend or terminate services, an administrative fine of up to RMB 1 million (or up to RMB 100,000 on the responsible person). For grave violations: an administrative fine of up to RMB 50 million OR up to 5% of the preceding-year turnover, suspension of relevant business activities, suspension of business for rectification, revocation of business permits or licences, etc. Direct liability of the responsible individual + person in charge: fine of up to RMB 1 million + prohibition from being a director / supervisor / senior officer of a relevant enterprise for a period of time.", mandatory: true },
    { clauseRef: "Art. 70",  title: "Public-interest litigation",                                              description: "Where a PI Handler violates this Law and infringes the rights and interests of many individuals, the People's Procuratorate, consumer-organisation specified by law, and the organisation determined by the CAC may bring legal action against the violator according to law.", mandatory: false },
  ],

  // ─── Controls (12 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "PIPL-LB-001",       title: "Legal-basis register (Art. 13)",                              description: "For every processing activity, document the Art. 13 legal basis (consent / contract / statutory duty / emergency / news + public-interest / publicly disclosed / other-law). Retain supporting evidence.",                                                                                                                                                                                                                category: "data-protection",      evidenceTypes: ["report","procedure","attestation","configuration"],   clauseRefs: ["Art. 13"],                          riskLevel: "high"   },
    { controlRef: "PIPL-CONS-001",     title: "Voluntary + explicit consent + withdrawal (Art. 14)",          description: "Voluntary + explicit + fully-informed consent capture; separate-consent flows where required by law (sensitive PI / cross-border / automated decision-making / providing to other PI Handlers); written-consent flows where required; withdrawal-as-easy-as-granting.",                                                                                                                                                  category: "data-protection",      evidenceTypes: ["log","screenshot","procedure","configuration"],        clauseRefs: ["Art. 14"],                          riskLevel: "high"   },
    { controlRef: "PIPL-NOTICE-001",   title: "Art. 17 notice obligations",                                    description: "Truthful + accurate + complete notice to individuals covering PI Handler identity + contact, purpose + methods + categories + retention, methods + procedures for exercising rights, and other matters required by law. Updated when matters change.",                                                                                                                                                              category: "data-protection",      evidenceTypes: ["policy","screenshot","report"],                       clauseRefs: ["Art. 17"],                          riskLevel: "high"   },
    { controlRef: "PIPL-ADM-001",      title: "Automated decision-making transparency + opt-out (Art. 24)",   description: "Documented inventory of automated decisions; transparency about the rules; fairness + impartiality of results; explanation-on-request mechanism; right-to-refuse mechanism for automated decisions with significant impact; option not targeting personal characteristics for commercial marketing / push notifications.",                                                                                            category: "ai-system-governance", evidenceTypes: ["procedure","report","configuration","screenshot"],     clauseRefs: ["Art. 24"],                          riskLevel: "high"   },
    { controlRef: "PIPL-SPI-001",      title: "Sensitive personal information processing (Art. 28-32)",       description: "Processing of sensitive PI (biometrics, religious beliefs, specific identity, medical/health, financial accounts, location tracking, minors-under-14): specific purpose + sufficient necessity + strict protection + separate consent (or written consent where required) + notice of necessity + impact. Minors-under-14 require guardian consent + a dedicated processing rule.",                                category: "data-protection",      evidenceTypes: ["policy","procedure","configuration","attestation"],   clauseRefs: ["Art. 28-32"],                       riskLevel: "high"   },
    { controlRef: "PIPL-XBORDER-001",  title: "Cross-border transfer (Art. 38-43)",                            description: "For every cross-border transfer: satisfy one of the four routes (CAC security assessment, CAC PI protection certification, CAC Standard Contract, other CAC-stipulated condition); document the choice + evidence. Critical Information Infrastructure Operators + volume-threshold PI Handlers MUST localise + pass CAC security assessment for export.",                                                          category: "data-protection",      evidenceTypes: ["contract","report","attestation","configuration"],    clauseRefs: ["Art. 38-43"],                       riskLevel: "high"   },
    { controlRef: "PIPL-RIGHTS-001",   title: "Individual-rights workflow (Art. 44-50)",                       description: "Documented intake + identity-verification + fulfilment workflow for the rights to be informed, decide, restrict / refuse, access / copy, correct / complete, delete, request explanation, and the deceased-relative inheritance rule. Convenient channel; reasons given on refusal; individual's right to litigate.",                                                                                              category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],              clauseRefs: ["Art. 44-50"],                       riskLevel: "high"   },
    { controlRef: "PIPL-OBL-001",      title: "General obligations of PI Handler (Art. 51)",                  description: "Internal management systems documented; PI classification; technical security measures (encryption + de-identification + access control); operational authorisations + training; contingency response plans; periodic refresh.",                                                                                                                                                                                  category: "data-protection",      evidenceTypes: ["policy","procedure","configuration","attestation"],   clauseRefs: ["Art. 51"],                          riskLevel: "high"   },
    { controlRef: "PIPL-PIPO-001",     title: "PIPO designation + overseas-representative (Art. 52 + 53)",    description: "Where processing meets the CAC-defined volume threshold, a PIPO is designated; name + contact information reported to the CAC. Where an overseas PI Handler is subject to Art. 3(2), a PRC-based dedicated entity or designated representative is established; name + contact submitted to the relevant department.",                                                                                                category: "ai-system-governance", evidenceTypes: ["attestation","report","contract","policy"],            clauseRefs: ["Art. 52","Art. 53"],               riskLevel: "high"   },
    { controlRef: "PIPL-PIPIA-001",    title: "Audit + PIPIA (Art. 54-56)",                                    description: "Periodic compliance audit of processing activities; Personal Information Protection Impact Assessment performed BEFORE processing sensitive PI / automated decision-making / entrusted processing or PI sharing or making-public / cross-border transfer / other major-impact activities. PIPIA records retained for at least 3 years.",                                                                            category: "data-protection",      evidenceTypes: ["dpia","report","attestation","procedure"],            clauseRefs: ["Art. 54-56"],                       riskLevel: "high"   },
    { controlRef: "PIPL-BREACH-001",   title: "Breach notification (Art. 57)",                                description: "Immediate remedial measures on (potential) leakage/tampering/loss; notification to the relevant department + affected individuals; documented exemption-from-individual-notification analysis where measures effectively prevent harm — subject to department override.",                                                                                                                                                category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"], clauseRefs: ["Art. 57"],                          riskLevel: "high"   },
    { controlRef: "PIPL-PEN-001",      title: "Penalty + responsible-person exposure (Art. 66-67)",            description: "Risk register reflects PIPL penalty schedule: warning + confiscation of unlawful income + service-suspension + admin fines (up to RMB 1m / RMB 50m or 5% turnover for grave violations); responsible-person fines up to RMB 1m + role-prohibition. Public-interest litigation exposure (Art. 70) where many individuals are affected.",                                                                            category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                       clauseRefs: ["Art. 66-67","Art. 70"],            riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "PIPL-Q-001", text: "Does the processing fall within PIPL territorial application — processing in the PRC, OR extraterritorial processing for the purpose of offering goods/services to or analysing the activities of natural persons within the PRC (Art. 3)?",                       category: "applicability", riskWeight: 1.0, clauseRefs: ["Art. 3"] },
    { questionRef: "PIPL-Q-002", text: "Has the Art. 13 legal basis been declared for each processing activity?",                                                                                                                                                                                            category: "legal-basis",   riskWeight: 1.0, clauseRefs: ["Art. 13"] },
    { questionRef: "PIPL-Q-003", text: "Is consent voluntary + explicit + fully-informed under Art. 14, with separate-consent + written-consent flows where required, and easy withdrawal?",                                                                                                                category: "consent",       riskWeight: 1.0, clauseRefs: ["Art. 14"] },
    { questionRef: "PIPL-Q-004", text: "Does the Art. 17 notice cover identity + contact, purpose + methods + categories + retention, rights-exercise procedures, and other legally required matters?",                                                                                                      category: "notice",        riskWeight: 0.8, clauseRefs: ["Art. 17"] },
    { questionRef: "PIPL-Q-005", text: "For automated decision-making with significant impact, is transparency + explanation + right-to-refuse provided (Art. 24)?",                                                                                                                                          category: "adm",           riskWeight: 0.9, clauseRefs: ["Art. 24"] },
    { questionRef: "PIPL-Q-006", text: "For sensitive personal information (biometric / religious / specific identity / health / financial / location / minors-under-14): specific purpose + necessity + strict protection + separate consent + Art. 17 notice with necessity-and-impact (Art. 28-32)?",   category: "spi",           riskWeight: 1.0, clauseRefs: ["Art. 28-32"] },
    { questionRef: "PIPL-Q-007", text: "For every cross-border transfer, is one of the four Art. 38 routes (CAC security assessment / certification / Standard Contract / other condition) satisfied + documented?",                                                                                          category: "transfers",     riskWeight: 1.0, clauseRefs: ["Art. 38-43"] },
    { questionRef: "PIPL-Q-008", text: "Where the entity is a Critical Information Infrastructure Operator or processes PI above the CAC volume threshold, is PI localised in the PRC + has it passed the CAC security assessment for any export (Art. 40)?",                                                category: "ciio",          riskWeight: 0.9, clauseRefs: ["Art. 38-43"] },
    { questionRef: "PIPL-Q-009", text: "Can the rights in Art. 44-50 (informed, decide, restrict/refuse, access/copy, correct/complete, delete, explanation, deceased-relative inheritance) be fulfilled, with reasons on refusal?",                                                                          category: "rights",        riskWeight: 1.0, clauseRefs: ["Art. 44-50"] },
    { questionRef: "PIPL-Q-010", text: "Are Art. 51 general obligations (internal management systems, classification, technical security, authorisations + training, contingency response) in place?",                                                                                                       category: "general-obligs",riskWeight: 0.9, clauseRefs: ["Art. 51"] },
    { questionRef: "PIPL-Q-011", text: "Has a PIPO been designated where the CAC volume threshold applies, with the name + contact reported to the CAC (Art. 52)?",                                                                                                                                          category: "pipo",          riskWeight: 0.8, clauseRefs: ["Art. 52"] },
    { questionRef: "PIPL-Q-012", text: "Where the entity is overseas + subject to Art. 3(2), is a PRC-based dedicated entity or representative designated (Art. 53)?",                                                                                                                                       category: "rep",           riskWeight: 0.8, clauseRefs: ["Art. 53"] },
    { questionRef: "PIPL-Q-013", text: "Are PIPIAs performed prior to sensitive-PI / automated-decision-making / entrustment / data-sharing / making-public / cross-border / other major-impact processing (Art. 54-56)? Records retained ≥3 years?",                                                          category: "pipia",         riskWeight: 0.9, clauseRefs: ["Art. 54-56"] },
    { questionRef: "PIPL-Q-014", text: "Can a personal-information security incident be remediated immediately + notified to the relevant department + individuals per Art. 57?",                                                                                                                            category: "breach",        riskWeight: 1.0, clauseRefs: ["Art. 57"] },
    { questionRef: "PIPL-Q-015", text: "Is penalty exposure (up to RMB 50m or 5% turnover for grave violations + responsible-person fines + role-prohibition + public-interest litigation under Art. 70) reflected in the risk register?",                                                                    category: "penalties",     riskWeight: 0.6, clauseRefs: ["Art. 66-67","Art. 70"] },
  ],
};
