import type { Framework } from "@regunav/types";

/**
 * Privacy Act 1988 (Cth) — Australia's federal privacy statute,
 * including the thirteen Australian Privacy Principles (APPs) in
 * Schedule 1 and the Notifiable Data Breaches (NDB) scheme in
 * Part IIIC. As amended by the Privacy Legislation Amendment
 * (Enforcement and Other Measures) Act 2022 (No. 83 of 2022),
 * which increased the maximum civil-penalty for serious or repeated
 * interference with privacy from AUD 2.22m to the greater of
 * AUD 50m / 30% of adjusted-turnover-in-relevant-period / 3x the
 * benefit of the conduct (Privacy Act s. 13G).
 *
 * Regulator: Office of the Australian Information Commissioner
 * (OAIC) — https://www.oaic.gov.au
 *
 * Sources:
 *   - Consolidated Act: https://www.legislation.gov.au/C2004A03712/latest
 *   - APP Guidelines:   https://www.oaic.gov.au/privacy/australian-privacy-principles-guidelines
 *   - NDB scheme:       https://www.oaic.gov.au/privacy/notifiable-data-breaches
 *
 * Clauses below are anchored to APPs (Schedule 1) and Part IIIC
 * sections of the Act. They are structural references, not legal
 * advice. See packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const PRIVACY_ACT_AU: Framework = {
  schemaVersion: 1,
  code: "PRIVACY_ACT_AU",
  name: "Australia Privacy Act",
  version: "1988 (Cth); amended 2022 (Enforcement & Other Measures)",
  description:
    "Australia's federal privacy statute. Applies to APP-entities — Commonwealth agencies and private-sector organisations with annual turnover above AUD 3 million plus the prescribed lower-threshold categories (health-service providers, traders in personal information, related-body-corporates, credit-reporting bodies, contractors to a Commonwealth contract). Establishes the thirteen Australian Privacy Principles (APPs) in Schedule 1 covering open + transparent management of personal information; anonymity and pseudonymity; collection of solicited / unsolicited / sensitive information; notification of collection; use or disclosure; direct marketing; cross-border disclosure; identifiers; quality + security; access + correction. Part IIIC contains the Notifiable Data Breaches scheme. The 2022 amendments substantially increased civil-penalty exposure for serious or repeated interference with privacy.",
  jurisdiction: ["AU"],
  referenceUrl: "https://www.oaic.gov.au/privacy/australian-privacy-principles-guidelines",

  // ─── Clauses (16 APP / Part IIIC anchors) ─────────────────────────────────
  clauses: [
    { clauseRef: "APP 1",     title: "Open and transparent management of personal information",                description: "An APP-entity must manage personal information in an open and transparent way. The entity must have a clearly expressed and up-to-date APP-privacy-policy describing: (i) the kinds of personal information collected and held; (ii) how it is collected and held; (iii) the purposes of collection, holding, use and disclosure; (iv) how an individual may access and seek correction; (v) how to complain about a breach of the APPs and how the entity will deal with the complaint; (vi) whether the entity is likely to disclose personal information to overseas recipients and, if so, the countries.", mandatory: true },
    { clauseRef: "APP 2",     title: "Anonymity and pseudonymity",                                              description: "An APP-entity must give individuals the option of not identifying themselves, or of using a pseudonym, when dealing with the entity in relation to a particular matter — unless the entity is required or authorised by law or a court/tribunal order to deal with identified individuals, or it is impracticable for the entity to deal with individuals who have not identified themselves or who have used a pseudonym.", mandatory: true },
    { clauseRef: "APP 3",     title: "Collection of solicited personal information",                            description: "An APP-entity must only collect personal information (other than sensitive information) where reasonably necessary for, or directly related to, one or more of the entity's functions or activities. Sensitive information must not be collected unless the individual consents AND the information is reasonably necessary for, or directly related to, one or more of the entity's functions or activities, OR a specified exemption applies (legal requirement, permitted general / health situation, enforcement-related activities). Collection must be by lawful and fair means and, generally, directly from the individual.", mandatory: true },
    { clauseRef: "APP 4",     title: "Dealing with unsolicited personal information",                           description: "Where an APP-entity receives personal information that it did not solicit, the entity must, within a reasonable period, determine whether or not it could have collected the information under APP 3 had it solicited it. If not, the entity must — as soon as practicable but only if lawful and reasonable to do so — destroy the information or ensure that it is de-identified.", mandatory: true },
    { clauseRef: "APP 5",     title: "Notification of the collection of personal information",                  description: "At or before the time, or as soon as practicable after, the APP-entity collects personal information, it must take reasonable steps to notify the individual of: identity + contact details of the APP-entity; the fact and circumstances of collection; whether the collection is required or authorised by law; the purposes of collection; the consequences if the personal information is not collected; the entity's usual disclosures of personal information of that kind; whether the APP-privacy-policy contains information about how to access + correct; how to complain; whether the entity is likely to disclose to overseas recipients and the countries.", mandatory: true },
    { clauseRef: "APP 6",     title: "Use or disclosure of personal information",                               description: "If an APP-entity holds personal information about an individual that was collected for a particular purpose (the primary purpose), the entity must not use or disclose the information for another purpose (a secondary purpose) unless the individual has consented OR a specified exception applies (related secondary purpose within the individual's reasonable expectations; required or authorised by law; permitted general / health situation; enforcement-related activities; biometric information to enforcement bodies, etc.). Disclosures to enforcement bodies must be recorded.", mandatory: true },
    { clauseRef: "APP 7",     title: "Direct marketing",                                                        description: "An organisation must not use or disclose personal information it holds about an individual for the purpose of direct marketing unless: (i) the information was collected from the individual + the individual would reasonably expect such use/disclosure + the organisation provides a simple means to opt-out + the individual has not opted-out; OR (ii) the information was collected from someone other than the individual or the individual would not reasonably expect such use/disclosure, but the individual has consented OR it is impracticable to obtain consent + the organisation provides a prominent + simple opt-out + the individual has not opted-out. Direct marketing using sensitive information requires consent. A 'do not contact' request must be honoured within a reasonable period, and the source of the personal information disclosed on request.", mandatory: true },
    { clauseRef: "APP 8",     title: "Cross-border disclosure of personal information",                         description: "Before an APP-entity discloses personal information about an individual to an overseas recipient, the entity must take reasonable steps to ensure that the overseas recipient does not breach the APPs (other than APP 1) in relation to the information. Where APP 8.1 applies, the disclosing entity is accountable under s. 16C for any APP-breach by the overseas recipient. Exceptions: individual has consented after being informed that APP 8.1 will not apply; substantially similar protective law / binding scheme + enforceability; required or authorised by law; permitted general / health situation; enforcement-related activities.", mandatory: true },
    { clauseRef: "APP 9",     title: "Adoption, use or disclosure of government-related identifiers",            description: "An organisation must not adopt a government-related identifier of an individual as its own identifier of the individual unless required or authorised by law (or by a court/tribunal order, or by regulation made under the Act). An organisation must not use or disclose a government-related identifier unless reasonably necessary to verify identity for its functions/activities, to fulfil obligations to a Commonwealth agency or a State/Territory authority, required or authorised by law, or a permitted general / enforcement situation.", mandatory: true },
    { clauseRef: "APP 10",    title: "Quality of personal information",                                          description: "An APP-entity must take such steps (if any) as are reasonable in the circumstances to ensure that the personal information it collects is accurate, up-to-date and complete. An APP-entity must take such steps (if any) as are reasonable to ensure that personal information it uses or discloses is, having regard to the purpose of the use or disclosure, accurate, up-to-date, complete and relevant.", mandatory: true },
    { clauseRef: "APP 11",    title: "Security of personal information",                                         description: "An APP-entity must take such steps as are reasonable in the circumstances to protect the personal information it holds from misuse, interference and loss, and from unauthorised access, modification or disclosure. Where personal information is no longer needed for any purpose for which it may be used or disclosed under the APPs and the entity is not required by law / court order / tribunal order to retain it, the entity must take such steps as are reasonable to destroy the information or ensure that it is de-identified.", mandatory: true },
    { clauseRef: "APP 12",    title: "Access to personal information",                                           description: "On request by an individual, an APP-entity must give the individual access to the personal information about the individual that the entity holds — unless a specified exception applies (serious threat to life/health/safety; unreasonable impact on the privacy of other individuals; frivolous or vexatious request; legal-professional-privilege material; commercially-sensitive decision-making process; etc.). An organisation must respond within a reasonable period after the request, and an agency within 30 days. If access is refused, the entity must provide written notice with the reasons and complaint mechanisms.", mandatory: true },
    { clauseRef: "APP 13",    title: "Correction of personal information",                                       description: "An APP-entity must take such steps (if any) as are reasonable to correct personal information it holds to ensure that it is accurate, up-to-date, complete, relevant and not misleading, having regard to the purpose for which it is held. If an APP-entity that holds personal information is satisfied that, having regard to a purpose for which the information is held, the information is inaccurate, out-of-date, incomplete, irrelevant or misleading, OR the individual requests correction, the entity must take such steps as are reasonable to correct the information. If the entity has previously disclosed corrected information to another APP-entity, the individual may request notification of the correction to that other entity (unless impracticable or unlawful).", mandatory: true },
    { clauseRef: "Part IIIC", title: "Notifiable Data Breaches (NDB) scheme",                                    description: "Where there are reasonable grounds to believe that an 'eligible data breach' has occurred (unauthorised access to, unauthorised disclosure of, or loss of personal information held by the entity, that is likely to result in serious harm to one or more individuals to whom the information relates), the entity must, as soon as practicable after becoming aware of the breach, prepare a statement to the Commissioner with prescribed contents (s. 26WK) AND notify each of the individuals to whom the information relates / who are at-risk, or — if practicable — publish the statement and take reasonable steps to publicise its contents. Where the entity only has reasonable grounds to suspect, it must carry out a reasonable + expeditious assessment within 30 days (s. 26WH).", mandatory: true },
    { clauseRef: "s. 13G",    title: "Civil penalty — serious or repeated interference with privacy",            description: "An APP-entity that does an act, or engages in a practice, that is a serious interference with the privacy of an individual, or repeatedly does any act or engages in any practice that is an interference with the privacy of one or more individuals, contravenes a civil-penalty provision. The maximum penalty (per 2022 amendments) for a body corporate is the greater of: (i) AUD 50,000,000; (ii) if the court can determine the value of the benefit obtained — 3x the value of that benefit; (iii) if the court cannot — 30% of the adjusted turnover of the body corporate during the breach turnover period.", mandatory: true },
    { clauseRef: "s. 33C",    title: "Commissioner's investigation, determination + enforcement powers",         description: "The Australian Information Commissioner may, on a complaint or on the Commissioner's own initiative, investigate an act or practice that may be an interference with the privacy of an individual or a breach of the APPs. The Commissioner may make a determination (s. 52) including a declaration that the entity must take specified steps within a specified period, must pay compensation, or must cease the conduct; accept an enforceable undertaking (s. 33E); seek a civil-penalty order from the Federal Court (s. 80W); issue an infringement notice (s. 80U); or accept an injunction. Determinations are enforceable in the Federal Court / Federal Circuit and Family Court.", mandatory: true },
  ],

  // ─── Controls (12 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "APP-POL-001",     title: "APP-privacy-policy management (APP 1)",                            description: "Clearly-expressed + up-to-date APP-privacy-policy published on the entity's website + made available on request in an appropriate form. Covers all eight APP 1.4 items including overseas-disclosure countries. Periodic review + version history. Free-of-charge availability.",                                                                                                                                                              category: "data-protection",      evidenceTypes: ["policy","screenshot","procedure","attestation"],         clauseRefs: ["APP 1"],              riskLevel: "high"    },
    { controlRef: "APP-ANON-001",    title: "Anonymity + pseudonymity option (APP 2)",                          description: "Service / matter inventory records, for each individual-facing interaction, whether anonymity / pseudonymity is offered, and — where not — the basis (legal requirement or impracticability). UI affordances support unidentified or pseudonymous interaction where offered.",                                                                                                                                                                category: "data-protection",      evidenceTypes: ["procedure","screenshot","configuration","report"],       clauseRefs: ["APP 2"],              riskLevel: "limited" },
    { controlRef: "APP-COLL-001",    title: "Collection limitation + sensitive-info consent (APP 3-4)",          description: "Collection register documents the function/activity each collection serves, lawful + fair means used, and direct-from-individual default. Sensitive information flows require recorded consent + necessity + a specified exemption analysis. Unsolicited-information assessment + destruction-or-de-identification workflow.",                                                                                                                category: "data-protection",      evidenceTypes: ["procedure","log","attestation","screenshot"],            clauseRefs: ["APP 3","APP 4"],      riskLevel: "high"    },
    { controlRef: "APP-NOT-001",     title: "Collection notice (APP 5)",                                         description: "Collection-notice template ensures all APP 5.2 matters are covered at or before / as soon as practicable after collection: identity + contact, circumstances of collection, legal requirement, purposes, consequences of non-collection, usual disclosures, APP-privacy-policy reference, overseas recipients.",                                                                                                                            category: "data-protection",      evidenceTypes: ["policy","screenshot","procedure"],                       clauseRefs: ["APP 5"],              riskLevel: "high"    },
    { controlRef: "APP-USE-001",     title: "Primary-purpose use + secondary-purpose discipline (APP 6)",        description: "Each use / disclosure is mapped to either the primary purpose, individual consent, or a specified APP 6 exception (related secondary purpose + reasonable-expectations test, required-or-authorised-by-law, permitted general / health situation, enforcement-related activities). Disclosures to enforcement bodies are recorded.",                                                                                                  category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],                clauseRefs: ["APP 6"],              riskLevel: "high"    },
    { controlRef: "APP-DM-001",      title: "Direct-marketing + opt-out (APP 7)",                                description: "Direct-marketing flows distinguish information-collected-from-the-individual (reasonable-expectations gate) vs information-collected-from-a-third-party (consent gate or impracticability + prominent opt-out). Simple opt-out mechanism honoured within a reasonable period; source of personal information disclosed on request. Sensitive-info direct marketing requires consent.",                                                  category: "data-protection",      evidenceTypes: ["procedure","screenshot","configuration","log"],          clauseRefs: ["APP 7"],              riskLevel: "high"    },
    { controlRef: "APP-XBORDER-001", title: "Cross-border disclosure + accountability (APP 8 + s. 16C)",         description: "Overseas-disclosure register classifies each recipient by APP 8 route: (i) reasonable-steps to ensure no APP-breach (accountability under s. 16C); (ii) consent after APP 8.1 disablement notice; (iii) substantially-similar-law route + enforceability; (iv) required-or-authorised-by-law / permitted general / health / enforcement. Standard data-transfer terms + audit-right + breach-reporting cascade.",                              category: "data-protection",      evidenceTypes: ["contract","procedure","report","attestation"],           clauseRefs: ["APP 8"],              riskLevel: "high"    },
    { controlRef: "APP-IDENT-001",   title: "Government-related identifier discipline (APP 9)",                  description: "Identifier register ensures no government-related identifier (TFN, Medicare, Centrelink CRN, driver-licence, etc.) is adopted as a primary identifier, except as required or authorised by law. Use / disclosure is restricted to identity verification / Commonwealth-agency obligations / law / permitted general / enforcement.",                                                                                              category: "data-protection",      evidenceTypes: ["policy","configuration","attestation","report"],         clauseRefs: ["APP 9"],              riskLevel: "high"    },
    { controlRef: "APP-QUAL-001",    title: "Personal-information quality (APP 10)",                             description: "Reasonable steps to ensure accuracy / up-to-date / completeness at collection AND, with relevance and purpose in mind, at use / disclosure. Documented sources + verification + refresh cadence by data category.",                                                                                                                                                                                                                category: "data-protection",      evidenceTypes: ["procedure","log","report","configuration"],              clauseRefs: ["APP 10"],             riskLevel: "limited" },
    { controlRef: "APP-SEC-001",     title: "Security + retention / destruction (APP 11) + NDB readiness",       description: "Reasonable security steps proportionate to circumstances — covering misuse / interference / loss / unauthorised access / modification / disclosure — including the OAIC 'Guide to securing personal information' control families (governance, ICT, access, training, physical, third-party, breach response). No-longer-needed personal information destroyed or de-identified per APP 11.2. Integrated with NDB workflow.",      category: "data-protection",      evidenceTypes: ["policy","procedure","configuration","attestation"],     clauseRefs: ["APP 11","Part IIIC"], riskLevel: "high"    },
    { controlRef: "APP-RIGHTS-001",  title: "Access + correction workflow (APP 12-13)",                          description: "Documented intake + identity-verification + fulfilment for access requests (agency: 30 days; organisation: reasonable period) + correction requests, with the prescribed exception analysis + written reasons on refusal + complaint pathway. Onwards-notification of corrections to prior disclosure recipients on request.",                                                                                                          category: "data-protection",      evidenceTypes: ["procedure","log","report","attestation"],                clauseRefs: ["APP 12","APP 13"],    riskLevel: "high"    },
    { controlRef: "NDB-001",         title: "Notifiable Data Breaches scheme + civil-penalty exposure",          description: "Documented eligible-data-breach assessment workflow with the 30-day expeditious-assessment window (s. 26WH); statement to the Commissioner with prescribed contents + individual notification (or substitute publication where individual-notification is impracticable); evidence retention. Risk register reflects s. 13G civil-penalty exposure: AUD 50m / 30% adjusted turnover / 3x benefit.",                                  category: "incident-response",    evidenceTypes: ["procedure","incident_record","report","attestation"],   clauseRefs: ["Part IIIC","s. 13G"], riskLevel: "high"    },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "AU-PA-Q-001", text: "Is the entity an 'APP-entity' (Commonwealth agency, organisation with annual turnover > AUD 3 million, or a prescribed lower-threshold category — health-service provider, trader in personal information, related body corporate, credit-reporting body, Commonwealth-contract contractor)?",                                                                                                                category: "applicability",   riskWeight: 1.0, clauseRefs: ["APP 1"] },
    { questionRef: "AU-PA-Q-002", text: "Is an APP-privacy-policy published with all eight APP 1.4 disclosures including overseas-recipient countries, and made available free of charge in an appropriate form on request?",                                                                                                                                                                                                                       category: "transparency",    riskWeight: 1.0, clauseRefs: ["APP 1"] },
    { questionRef: "AU-PA-Q-003", text: "Are individuals given the option of anonymity or pseudonymity where neither a legal requirement nor impracticability prevents it (APP 2)?",                                                                                                                                                                                                                                                                  category: "anonymity",       riskWeight: 0.7, clauseRefs: ["APP 2"] },
    { questionRef: "AU-PA-Q-004", text: "Is each collection of personal information necessary for / directly related to a function or activity, by lawful + fair means, and (generally) direct from the individual — with sensitive-information collection limited to consent + necessity or a specified exemption (APP 3)?",                                                                                                                       category: "collection",      riskWeight: 1.0, clauseRefs: ["APP 3"] },
    { questionRef: "AU-PA-Q-005", text: "Are unsolicited-personal-information receipts assessed within a reasonable period and destroyed or de-identified where collection under APP 3 would not have been permitted (APP 4)?",                                                                                                                                                                                                                     category: "collection",      riskWeight: 0.7, clauseRefs: ["APP 4"] },
    { questionRef: "AU-PA-Q-006", text: "Does the collection notice cover all APP 5.2 matters at or before / as soon as practicable after collection — identity + contact, circumstances, legal basis, purposes, consequences of non-collection, usual disclosures, APP-privacy-policy reference, overseas recipients?",                                                                                                                          category: "notice",          riskWeight: 1.0, clauseRefs: ["APP 5"] },
    { questionRef: "AU-PA-Q-007", text: "Is every use / disclosure either the primary purpose, individual-consented, or covered by an APP 6 exception (related-secondary + reasonable-expectations / required-by-law / permitted general / permitted health / enforcement)?",                                                                                                                                                                       category: "use-disclosure",  riskWeight: 1.0, clauseRefs: ["APP 6"] },
    { questionRef: "AU-PA-Q-008", text: "For direct marketing, is the reasonable-expectations or consent gate satisfied, with simple opt-out + sensitive-info-consent + source-disclosure-on-request (APP 7)?",                                                                                                                                                                                                                                     category: "direct-marketing",riskWeight: 0.9, clauseRefs: ["APP 7"] },
    { questionRef: "AU-PA-Q-009", text: "Before disclosing personal information overseas, are reasonable steps taken to ensure the recipient does not breach the APPs — OR has one of the APP 8.2 exceptions been documented (s. 16C accountability acknowledged)?",                                                                                                                                                                                category: "transfers",       riskWeight: 1.0, clauseRefs: ["APP 8"] },
    { questionRef: "AU-PA-Q-010", text: "Is the adoption / use / disclosure of government-related identifiers (TFN, Medicare, CRN, driver-licence, etc.) limited to the APP 9 permitted situations?",                                                                                                                                                                                                                                                category: "identifiers",     riskWeight: 0.8, clauseRefs: ["APP 9"] },
    { questionRef: "AU-PA-Q-011", text: "Are reasonable steps taken to keep personal information accurate + up-to-date + complete + relevant at collection AND at use / disclosure (APP 10)?",                                                                                                                                                                                                                                                       category: "quality",         riskWeight: 0.7, clauseRefs: ["APP 10"] },
    { questionRef: "AU-PA-Q-012", text: "Are reasonable security steps in place against misuse / interference / loss / unauthorised access / modification / disclosure — and is no-longer-needed personal information destroyed or de-identified (APP 11)?",                                                                                                                                                                                          category: "security",        riskWeight: 1.0, clauseRefs: ["APP 11"] },
    { questionRef: "AU-PA-Q-013", text: "Can individuals exercise the rights of access (agency: 30 days; organisation: reasonable period) and correction, with the prescribed exception analysis + written reasons on refusal (APP 12-13)?",                                                                                                                                                                                                         category: "rights",          riskWeight: 1.0, clauseRefs: ["APP 12","APP 13"] },
    { questionRef: "AU-PA-Q-014", text: "Can an eligible-data-breach assessment + statement-to-the-Commissioner + individual-notification be performed as soon as practicable, with the 30-day expeditious-assessment window observed where there is only a suspicion (Part IIIC)?",                                                                                                                                                                category: "breach",          riskWeight: 1.0, clauseRefs: ["Part IIIC"] },
    { questionRef: "AU-PA-Q-015", text: "Is the s. 13G civil-penalty exposure for serious or repeated interference with privacy (greater of AUD 50m / 30% adjusted turnover / 3x benefit) reflected in the risk register?",                                                                                                                                                                                                                          category: "penalties",       riskWeight: 0.6, clauseRefs: ["s. 13G"] },
  ],
};
