import type { Framework } from "@regunav/types";

/**
 * SOC 2 — AICPA Trust Services Criteria for Security, Availability,
 * Processing Integrity, Confidentiality and Privacy (TSP Section 100).
 * The 2017 criteria with the 2022 Points of Focus is the current revision
 * used by service-auditor attestation engagements.
 *
 * Source: AICPA Trust Services Criteria (https://www.aicpa.org).
 *
 * ⚠ The AICPA holds copyright over the TSC text. References below cite
 * each criterion by its code + outline only — they DO NOT reproduce the
 * published text. Engagements rely on the licensed TSC document. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 *
 * SOC 2 is an attestation framework, not a regulation. The "Type II"
 * report attests to the operating effectiveness of controls over a
 * period (typically 6-12 months). The service organisation describes its
 * system + selects applicable trust-services categories; an independent
 * CPA service auditor performs the engagement.
 */
export const SOC_2: Framework = {
  schemaVersion: 1,
  code: "SOC_2",
  name: "SOC 2 Type II",
  version: "2017 TSC",
  description:
    "AICPA attestation framework for service organisations. The Common Criteria (CC1-CC9) form the security baseline that every SOC 2 engagement covers; the four additional categories (Availability, Processing Integrity, Confidentiality, Privacy) are optional and elected by the service organisation. A SOC 2 Type II engagement covers a period (typically 6-12 months) and attests to operating effectiveness of controls. Independent CPA service auditor produces the report under SSAE 18 / AT-C Section 320.",
  jurisdiction: ["US", "INTERNATIONAL"],
  referenceUrl: "https://www.aicpa.org",

  // ─── Clauses (Common Criteria CC1-CC9 + 4 optional categories) ────────────
  clauses: [
    { clauseRef: "CC1",       title: "Control Environment",                                         description: "Establishes integrity and ethical values, demonstrates commitment to competence, exercises oversight responsibility, establishes structure/authority/responsibility, and demonstrates commitment to attract, develop and retain competent individuals. Five points of focus.", mandatory: true },
    { clauseRef: "CC2",       title: "Communication and Information",                                description: "Obtains or generates and uses relevant, quality information; communicates internally; communicates externally regarding matters affecting the functioning of internal control over the system. Three points of focus.", mandatory: true },
    { clauseRef: "CC3",       title: "Risk Assessment",                                              description: "Specifies suitable objectives; identifies and analyses risk; assesses fraud risk; identifies and analyses significant change. Four points of focus.", mandatory: true },
    { clauseRef: "CC4",       title: "Monitoring Activities",                                        description: "Selects, develops and performs ongoing and separate evaluations; evaluates and communicates deficiencies. Two points of focus.", mandatory: true },
    { clauseRef: "CC5",       title: "Control Activities",                                           description: "Selects and develops control activities that contribute to mitigation of risk to acceptable levels; selects and develops general controls over technology; deploys policies and procedures through which the organisation puts management directives into action. Three points of focus.", mandatory: true },
    { clauseRef: "CC6",       title: "Logical and Physical Access Controls",                         description: "Implements logical access security software, infrastructure and architectures; registers/authorises/identifies users; restricts logical and physical access; manages credentials for infrastructure and software; restricts the transmission/movement/removal of information; manages physical access; designs and implements credential change and removal; prevents/detects unauthorised access. Eight points of focus.", mandatory: true },
    { clauseRef: "CC7",       title: "System Operations",                                            description: "Detects new vulnerabilities; monitors system components and the operation of those components; designs/develops/deploys mitigation activities for security events; identifies/develops/implements responses to address potential security threats; recovers from identified security incidents. Five points of focus.", mandatory: true },
    { clauseRef: "CC8",       title: "Change Management",                                            description: "Authorises, designs, develops, configures, documents, tests, approves and implements changes to infrastructure, data, software and procedures.", mandatory: true },
    { clauseRef: "CC9",       title: "Risk Mitigation",                                              description: "Identifies, selects and develops risk-mitigation activities for risks arising from potential business disruptions; assesses and manages risks associated with vendors and business partners. Two points of focus.", mandatory: true },
    { clauseRef: "A1",        title: "Additional Criteria for Availability",                          description: "Maintains, monitors and evaluates current processing capacity and use of system components to manage capacity demand and to enable the implementation of additional capacity; authorises, designs, develops or acquires, implements, operates, approves, maintains and monitors environmental protections, software, data backup processes and recovery infrastructure to meet availability objectives; tests recovery plan procedures supporting system recovery to meet availability objectives.", mandatory: false },
    { clauseRef: "PI1",       title: "Additional Criteria for Processing Integrity",                  description: "Defines processing specifications; implements policies, procedures and controls over system inputs; performs system processing in a complete, valid, accurate, timely and authorised manner; outputs are complete and accurate; stores inputs/outputs/processing items completely, accurately and timely.", mandatory: false },
    { clauseRef: "C1",        title: "Additional Criteria for Confidentiality",                       description: "Identifies and maintains confidential information to meet objectives related to confidentiality; disposes of confidential information.", mandatory: false },
    { clauseRef: "P1-P8",     title: "Additional Criteria for Privacy",                               description: "Notice and communication of objectives (P1); choice and consent (P2); collection (P3); use, retention and disposal (P4); access (P5); disclosure and notification (P6); quality (P7); monitoring and enforcement (P8). Aligned with the AICPA/CICA Generally Accepted Privacy Principles.", mandatory: false },
  ],

  // ─── Controls (15 satisfying the Common Criteria + 4 optional categories) ─
  controls: [
    { controlRef: "SOC2-CC1-001",  title: "Control environment — integrity, ethics, oversight",        description: "Code of conduct + ethics policy, board / management oversight charter, organisational structure with defined authorities + responsibilities, hiring + retention practices for competence. Maps CC1 five POFs.",                                                                                                       category: "ai-system-governance", evidenceTypes: ["policy","attestation","training_record","report"],     clauseRefs: ["CC1"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC2-001",  title: "Communication + information",                                description: "Internal-communication mechanisms (intranet, all-hands, incident notification), external-communication mechanisms (customer status page, support channel, breach notice), information-quality controls. Maps CC2 three POFs.",                                                                                category: "ai-system-governance", evidenceTypes: ["policy","procedure","screenshot","report"],            clauseRefs: ["CC2"],   riskLevel: "limited" },
    { controlRef: "SOC2-CC3-001",  title: "Risk assessment + fraud risk + change risk",                 description: "Risk-assessment methodology, top-down + bottom-up risk identification, fraud risk register, change-risk evaluation tied to release management. Maps CC3 four POFs.",                                                                                                                                          category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                    clauseRefs: ["CC3"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC4-001",  title: "Monitoring activities + deficiency tracking",                description: "Ongoing + separate evaluations, deficiency register, root-cause analysis, communication of deficiencies up the management chain. Maps CC4 two POFs.",                                                                                                                                                              category: "logging-monitoring",  evidenceTypes: ["report","procedure","log","attestation"],              clauseRefs: ["CC4"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC5-001",  title: "Control activities + general IT controls",                   description: "Selected control activities mapped to mitigated risks, GITCs (access management, change management, computer operations), policies + procedures documented and operating. Maps CC5 three POFs.",                                                                                                                  category: "ai-system-governance", evidenceTypes: ["policy","procedure","configuration","report"],         clauseRefs: ["CC5"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC6-001",  title: "Logical access — IAM + MFA + privileged access",             description: "Identity provisioning + deprovisioning, MFA on all human access (incl. customer support), least-privilege access reviews, privileged-access monitoring, credential management. Maps CC6 logical-access POFs.",                                                                                                    category: "identity-access",     evidenceTypes: ["policy","configuration","log","attestation"],          clauseRefs: ["CC6"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC6-002",  title: "Physical access + transmission security",                    description: "Data-centre physical access controls (badge, visitor log, mantrap, monitoring), encryption in transit + at rest, removable-media controls, secure-disposal procedures. Maps CC6 physical + transmission POFs.",                                                                                                category: "physical-security",   evidenceTypes: ["policy","screenshot","configuration","attestation"],   clauseRefs: ["CC6"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC7-001",  title: "System operations — vulnerability + incident response",      description: "Vulnerability-management programme, SIEM + alerting, security-incident response runbook, post-incident review, threat-intel integration. Maps CC7 five POFs.",                                                                                                                                                    category: "incident-response",   evidenceTypes: ["report","incident_record","configuration","procedure"],clauseRefs: ["CC7"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC8-001",  title: "Change management",                                          description: "Documented change-management workflow with peer review + approval, segregation of duties between developer and release approver, separation of dev/test/prod, rollback plan, post-implementation review. Maps CC8.",                                                                                            category: "change-management",   evidenceTypes: ["procedure","log","configuration","attestation"],       clauseRefs: ["CC8"],   riskLevel: "high"   },
    { controlRef: "SOC2-CC9-001",  title: "Risk mitigation — BCM + vendor risk",                        description: "Business-continuity programme with tested DR, vendor due-diligence procedure, vendor-tier risk register, contractual flow-down of security obligations. Maps CC9 two POFs.",                                                                                                                                    category: "business-continuity", evidenceTypes: ["procedure","report","contract","attestation"],         clauseRefs: ["CC9"],   riskLevel: "high"   },
    { controlRef: "SOC2-A1-001",   title: "Availability — capacity + recovery + tested DR",             description: "Capacity-management + monitoring, redundancy across availability zones / regions, backup + restore testing, environmental protection (UPS, fire suppression). Maps A1 additional criteria.",                                                                                                                  category: "business-continuity", evidenceTypes: ["configuration","report","attestation","log"],          clauseRefs: ["A1"],    riskLevel: "high"   },
    { controlRef: "SOC2-PI1-001",  title: "Processing integrity — input + processing + output controls", description: "Documented processing specifications, input validation, in-process integrity checks (idempotency, checksums), output reconciliation. Maps PI1 additional criteria.",                                                                                                                                              category: "data-protection",     evidenceTypes: ["procedure","configuration","report","log"],            clauseRefs: ["PI1"],   riskLevel: "high"   },
    { controlRef: "SOC2-C1-001",   title: "Confidentiality — identification + disposal",                description: "Information classification, encryption defaults for confidential data, retention + secure-disposal procedures, customer-data isolation in multi-tenant environments. Maps C1 additional criteria.",                                                                                                                category: "data-protection",     evidenceTypes: ["policy","configuration","procedure","attestation"],    clauseRefs: ["C1"],    riskLevel: "high"   },
    { controlRef: "SOC2-P1-001",   title: "Privacy — notice + choice + collection + retention + disposal", description: "Privacy notice, choice + consent capture, collection limited to declared purpose, retention schedule, secure disposal. Aligns to AICPA Privacy Principles P1-P4.",                                                                                                                                            category: "data-protection",     evidenceTypes: ["policy","procedure","screenshot","report"],            clauseRefs: ["P1-P8"], riskLevel: "high"   },
    { controlRef: "SOC2-P5-001",   title: "Privacy — access + disclosure + quality + monitoring",        description: "Data-subject access mechanism, disclosure tracking + breach notification, data-quality controls, privacy-monitoring + enforcement programme. Aligns to AICPA Privacy Principles P5-P8.",                                                                                                                          category: "data-protection",     evidenceTypes: ["procedure","log","report","attestation"],              clauseRefs: ["P1-P8"], riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "SOC2-Q-001", text: "Is the entity a service organisation seeking SOC 2 attestation, with the report period defined (typically 6-12 months for Type II)?",                                                            category: "applicability", riskWeight: 1.0, clauseRefs: ["CC1"] },
    { questionRef: "SOC2-Q-002", text: "Have applicable trust-services categories been elected (Common Criteria is mandatory; Availability/Processing Integrity/Confidentiality/Privacy optional)?",                                     category: "categories",    riskWeight: 1.0, clauseRefs: ["CC1","A1","PI1","C1","P1-P8"] },
    { questionRef: "SOC2-Q-003", text: "Is the control environment documented (code of conduct, oversight, organisational structure, competence framework) — CC1?",                                                                       category: "control-env",    riskWeight: 0.7, clauseRefs: ["CC1"] },
    { questionRef: "SOC2-Q-004", text: "Are internal + external communication mechanisms in place (CC2)?",                                                                                                                                category: "comms",          riskWeight: 0.6, clauseRefs: ["CC2"] },
    { questionRef: "SOC2-Q-005", text: "Is a risk-assessment process operating that covers operational, fraud and change risks (CC3)?",                                                                                                    category: "risk",           riskWeight: 0.9, clauseRefs: ["CC3"] },
    { questionRef: "SOC2-Q-006", text: "Are ongoing + separate evaluations performed and deficiencies tracked + communicated (CC4)?",                                                                                                      category: "monitoring",     riskWeight: 0.7, clauseRefs: ["CC4"] },
    { questionRef: "SOC2-Q-007", text: "Are general IT controls (access, change, computer operations) selected and operating (CC5)?",                                                                                                      category: "control-act",    riskWeight: 0.8, clauseRefs: ["CC5"] },
    { questionRef: "SOC2-Q-008", text: "Are logical access controls (IAM, MFA, least-privilege reviews, credential management) implemented (CC6)?",                                                                                       category: "logical-access", riskWeight: 0.9, clauseRefs: ["CC6"] },
    { questionRef: "SOC2-Q-009", text: "Are physical access + transmission-security controls implemented (CC6)?",                                                                                                                          category: "physical",       riskWeight: 0.8, clauseRefs: ["CC6"] },
    { questionRef: "SOC2-Q-010", text: "Are vulnerability management + SIEM + incident response operating (CC7)?",                                                                                                                          category: "operations",     riskWeight: 0.9, clauseRefs: ["CC7"] },
    { questionRef: "SOC2-Q-011", text: "Is change management with peer review + segregation of duties + dev/test/prod separation operating (CC8)?",                                                                                        category: "change",         riskWeight: 0.8, clauseRefs: ["CC8"] },
    { questionRef: "SOC2-Q-012", text: "Are business-continuity + vendor-risk programmes operating (CC9)?",                                                                                                                                  category: "risk-mit",       riskWeight: 0.8, clauseRefs: ["CC9"] },
    { questionRef: "SOC2-Q-013", text: "If Availability is elected, is capacity-management + redundancy + tested DR operating (A1)?",                                                                                                       category: "availability",   riskWeight: 0.7, clauseRefs: ["A1"] },
    { questionRef: "SOC2-Q-014", text: "If Processing Integrity is elected, are input/process/output controls operating (PI1)?",                                                                                                            category: "processing",     riskWeight: 0.7, clauseRefs: ["PI1"] },
    { questionRef: "SOC2-Q-015", text: "If Confidentiality is elected, are information-classification + encryption + secure-disposal controls operating (C1)?",                                                                             category: "confidentiality",riskWeight: 0.7, clauseRefs: ["C1"] },
    { questionRef: "SOC2-Q-016", text: "If Privacy is elected, are P1-P8 controls (notice/choice/collection/use+retention/access/disclosure/quality/monitoring) operating?",                                                                category: "privacy",        riskWeight: 0.7, clauseRefs: ["P1-P8"] },
    { questionRef: "SOC2-Q-017", text: "Has an independent CPA service auditor been engaged under SSAE 18 / AT-C Section 320 for the Type II period?",                                                                                     category: "auditor",        riskWeight: 0.8, clauseRefs: ["CC1"] },
  ],
};
