import type { Framework } from "@regunav/types";

/**
 * SOC 1 (Service Organization Controls 1) — Type II.
 *
 * SOC 1 examinations report on the design (Type I) and operating
 * effectiveness over a period of time (Type II) of a service
 * organization's controls that are likely to be relevant to user
 * entities' Internal Control over Financial Reporting (ICFR).
 *
 * Standards:
 *   - AICPA SSAE No. 18, AT-C section 320 — "Reporting on an
 *     Examination of Controls at a Service Organization Relevant
 *     to User Entities' Internal Control over Financial Reporting"
 *   - AICPA SOC 1 — SOC for Service Organizations: ICFR Audit Guide
 *
 * Unlike SOC 2 (which uses the standardised Trust Services Criteria),
 * SOC 1 control objectives are designed by management of the service
 * organization, in collaboration with the service auditor, to address
 * the assertions in management's description of the system (the
 * "description criteria") and the controls relied upon by user
 * auditors. The clauses below capture the most-cited control-objective
 * domains across the SOC 1 industry — they are structural references
 * and a starting framework, not a substitute for management's
 * description of the system.
 *
 * Body: American Institute of Certified Public Accountants (AICPA) —
 * https://www.aicpa-cima.com
 *
 * Sources:
 *   - AICPA SOC 1 Audit Guide:
 *     https://www.aicpa-cima.com/professional-insights/audit
 *   - SSAE 18 portal:
 *     https://www.aicpa-cima.com/resources/article/ssae-18-clarified-statements-on-standards-for-attestation-engagements
 *
 * Clauses, controls and questions cite SSAE 18 AT-C 320 paragraphs and
 * the SOC 1 description criteria (DC). They are structural references,
 * not legal advice. See packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const SOC_1: Framework = {
  schemaVersion: 1,
  code: "SOC_1",
  name: "SOC 1 Type II",
  version: "SSAE 18 AT-C 320 (2017)",
  description:
    "AICPA Service Organization Controls 1 (SOC 1) Type II examination — reports on the design and operating effectiveness of a service organization's controls likely to be relevant to user entities' Internal Control over Financial Reporting (ICFR). The examination is conducted by an independent service auditor under SSAE 18 AT-C 320. Type II covers a specified period (commonly 6 or 12 months) and includes the service auditor's tests of operating effectiveness. The framework captured here is the standard set of control-objective domains across the industry — logical access; change management; computer operations; system development; data transmission; physical security; data processing integrity — plus the structural requirements for the management description of the system (DC 1-8), the management assertion, CUECs (complementary user-entity controls), CSOCs (complementary subservice-organization controls), and carve-out vs inclusive-method subservice handling.",
  jurisdiction: ["US","GLOBAL"],
  referenceUrl: "https://www.aicpa-cima.com/professional-insights/audit",

  // ─── Clauses (13 SSAE 18 / SOC 1 anchors) ─────────────────────────────────
  clauses: [
    { clauseRef: "AT-C 320.09",   title: "Engagement scope + description criteria (DC 1-8)",                description: "Management of the service organization prepares a description of the service organization's system that meets the description criteria. The description criteria are: (DC 1) the types of services provided; (DC 2) the principal service commitments and system requirements; (DC 3) the components of the system used to provide the services (infrastructure, software, people, procedures, data); (DC 4) the boundaries or aspects of the system covered by the description; (DC 5) how the system captures + addresses significant events + conditions other than transactions; (DC 6) the process used to prepare reports + other information; (DC 7) services performed by subservice organizations (inclusive or carve-out method); (DC 8) any applicable trust-services criteria not addressed.", mandatory: true },
    { clauseRef: "AT-C 320.30",   title: "Management's written assertion",                                   description: "Management of the service organization provides a written assertion that, throughout the specified period, (i) the description fairly presents the service organization's system in accordance with the description criteria; (ii) the controls stated in the description were suitably designed to provide reasonable assurance that the control objectives stated in the description would be achieved if the controls operated effectively; and (iii) the controls operated effectively to achieve the control objectives.", mandatory: true },
    { clauseRef: "AT-C 320.A23",  title: "Risk assessment + control objectives",                              description: "Management identifies the risks that threaten the achievement of the service organization's service commitments and system requirements, and the risks that user auditors are likely to consider relevant to user-entity ICFR. For each significant risk, management defines a control objective stating the aim of the controls and the controls intended to achieve that objective. Control objectives are commonly grouped into the standard SOC 1 domains.", mandatory: true },
    { clauseRef: "SOC 1 CO-LA",   title: "Logical access controls",                                          description: "Control objectives covering: provisioning of user access (timely provisioning + management approval + segregation of duties); authentication (passwords + multi-factor authentication + session management); authorisation (role-based access + least-privilege + privileged-access management); periodic user-access review; timely deprovisioning on termination or role change; segregation between development / test / production environments; remote-access controls; audit logging of authentication + authorisation events. Failure of any logical-access objective is typically considered relevant to ICFR for any service organization handling user-entity financial data.", mandatory: true },
    { clauseRef: "SOC 1 CO-CM",   title: "Change management controls",                                       description: "Control objectives covering: documented SDLC + change-management policy; classification of changes (standard / normal / emergency); change requests with business justification; impact + risk assessment; peer code review; testing in non-production environments; segregation between developers and production-deployment authority; CAB (Change Advisory Board) or equivalent approval for non-emergency changes; back-out / rollback procedures; post-implementation review; production-deploy logs preserved for the audit period.", mandatory: true },
    { clauseRef: "SOC 1 CO-CO",   title: "Computer operations controls",                                     description: "Control objectives covering: job-scheduling + monitoring + failure-handling; batch processing controls (input completeness + processing accuracy + output completeness); incident management (detection / categorisation / response / root-cause analysis / preventive action); backup + restoration (frequency + retention + restore-test cadence); availability monitoring + capacity management; service-level objective tracking. Operations failures with ICFR impact (e.g., a missed batch) are reportable as control deviations.", mandatory: true },
    { clauseRef: "SOC 1 CO-SD",   title: "System development life cycle controls",                            description: "Control objectives covering: defined SDLC methodology (e.g., agile / waterfall); requirements gathering + design + development + testing + deployment phases; documented requirements + design artefacts; unit + integration + user-acceptance testing with evidence; data migration controls for any system change involving financial data; vendor SDLC oversight for outsourced development. Separation between development and production environments + access boundaries.", mandatory: true },
    { clauseRef: "SOC 1 CO-DT",   title: "Data transmission + interface controls",                            description: "Control objectives covering: secure data transmission with encryption-in-transit (TLS) over public networks; integrity controls (file-hash, sequence numbering, control totals); transmission acknowledgement + reconciliation; failure-handling + retransmission; interface controls between systems within scope and to subservice organisations + user entities (input completeness, accuracy of mapping, error-queue management).", mandatory: true },
    { clauseRef: "SOC 1 CO-PS",   title: "Physical + environmental security controls",                        description: "Control objectives covering: physical-access controls to data centres + offices housing in-scope systems (badge / biometric / visitor logs); environmental controls (fire-suppression / climate / power / UPS / generator); media handling + secure-disposal; tampering / theft prevention. Where the service organization uses a cloud or co-location subservice, these objectives are typically carve-out — the subservice organization's SOC 1 / SOC 2 report covers them and the service organization includes a CSOC describing reliance.", mandatory: true },
    { clauseRef: "SOC 1 CO-DPI",  title: "Data processing integrity + application controls",                   description: "Control objectives covering: input validation (edit checks, range checks, mandatory fields); processing accuracy (calculations, postings, aggregations); output completeness (totals, sequence numbers, exception reports); reconciliations between subsidiary records and the general ledger or upstream/downstream systems; manual key-control activities supporting automated processes; period-end procedures relevant to user-entity ICFR.", mandatory: true },
    { clauseRef: "AT-C 320.34",   title: "Subservice organizations — carve-out vs inclusive",                  description: "Where the service organization uses a subservice organization that performs services relevant to user entities' ICFR, the description must (i) identify the subservice organization, (ii) state the method used (carve-out: the description excludes the subservice organization's controls; or inclusive: the description includes them and the subservice organization's management also provides an assertion + the subservice organization's controls are tested), and (iii) describe the Complementary Subservice Organization Controls (CSOCs) that the service organization assumes the subservice organization implements.", mandatory: true },
    { clauseRef: "AT-C 320.A48",  title: "Complementary User Entity Controls (CUECs)",                         description: "The description identifies the Complementary User Entity Controls (CUECs) — controls that management has assumed will be implemented by user entities and that are necessary, in combination with the service organization's controls, for the related control objectives to be achieved. Common examples: user entities are responsible for the timely deprovisioning of their personnel; review of access reports provided by the service organization; accuracy + completeness of data submitted; review of output reports for reasonableness.", mandatory: true },
    { clauseRef: "AT-C 320.41",   title: "Service auditor's report contents",                                  description: "The service auditor's report includes: title and addressee; management's description of the service organization's system; identification of the criteria; reference to management's assertion; the service auditor's opinion on (a) fair presentation of the description, (b) suitable design of controls, (c) operating effectiveness of controls (Type II); description of the tests of controls + results; restricted-use paragraph (intended only for management of the service organization, user entities + their auditors); date; service-auditor signature and city/state.", mandatory: true },
  ],

  // ─── Controls (14 satisfying the clauses above) ──────────────────────────
  controls: [
    { controlRef: "SOC1-DESC-001",   title: "System description + management assertion preparation",                description: "Annual preparation of the management description of the service organization's system meeting all eight description criteria (DC 1-8); written management assertion covering fair presentation + design suitability + operating effectiveness; sign-off by appropriate level of management before service-auditor fieldwork.",                                                                                                                                                                                                                       category: "ai-system-governance", evidenceTypes: ["report","attestation","policy","procedure"],         clauseRefs: ["AT-C 320.09","AT-C 320.30"], riskLevel: "high"    },
    { controlRef: "SOC1-RA-001",     title: "Annual risk assessment + control-objective mapping",                    description: "Documented annual risk assessment that identifies risks to service commitments + system requirements + ICFR; mapping of each significant risk to a control objective; mapping of each control objective to specific controls; sign-off by management.",                                                                                                                                                                                                                                                                                       category: "ai-system-governance", evidenceTypes: ["report","procedure","attestation"],                  clauseRefs: ["AT-C 320.A23"],              riskLevel: "high"    },
    { controlRef: "SOC1-LA-PROV",    title: "User provisioning + RBAC + privileged-access management",                 description: "Documented provisioning workflow with management approval + role-based access + segregation-of-duties; privileged-access workflow with break-glass + monitored sessions + time-bounded grants; automated SoD-conflict detection where feasible.",                                                                                                                                                                                                                                                                              category: "access-control",       evidenceTypes: ["procedure","log","configuration","screenshot"],     clauseRefs: ["SOC 1 CO-LA"],               riskLevel: "high"    },
    { controlRef: "SOC1-LA-AUTH",    title: "Authentication + MFA + session controls",                                description: "Password policy aligned with NIST SP 800-63B; MFA required for production + admin + remote access; session-timeout + concurrent-session-limit + re-auth on privilege escalation; account-lockout policy; SSO + IdP centralisation where applicable.",                                                                                                                                                                                                                                                                            category: "access-control",       evidenceTypes: ["policy","configuration","screenshot","attestation"], clauseRefs: ["SOC 1 CO-LA"],               riskLevel: "high"    },
    { controlRef: "SOC1-LA-REVIEW",  title: "Periodic access review + termination deprovisioning",                     description: "Quarterly user-access review with sampling + remediation evidence; termination workflow triggers deprovisioning within defined SLA (commonly 24h for standard; immediate for involuntary); role-change reviews; documented exception-handling.",                                                                                                                                                                                                                                                                                  category: "access-control",       evidenceTypes: ["procedure","log","report","attestation"],            clauseRefs: ["SOC 1 CO-LA"],               riskLevel: "high"    },
    { controlRef: "SOC1-CM-001",     title: "Change management — SDLC, peer review, deploy approval",                  description: "Documented change-management policy with classification (standard / normal / emergency); change requests with business justification + impact + back-out plan; mandatory peer code review with two-eyes principle; CAB or equivalent approval for non-emergency production changes; segregation between developers and production-deployment authority; deploy logs + diff retained for the audit period.",                                                                                                                              category: "secure-sdlc",          evidenceTypes: ["procedure","log","screenshot","attestation","policy"],clauseRefs: ["SOC 1 CO-CM"],               riskLevel: "high"    },
    { controlRef: "SOC1-CM-EM",      title: "Emergency change controls",                                              description: "Defined emergency-change criteria; expedited approval pathway with retrospective ratification within a defined period (commonly 48-72h); post-implementation review for every emergency change.",                                                                                                                                                                                                                                                                                                                                   category: "secure-sdlc",          evidenceTypes: ["procedure","log","attestation","report"],            clauseRefs: ["SOC 1 CO-CM"],               riskLevel: "high"    },
    { controlRef: "SOC1-CO-001",     title: "Job scheduling + monitoring + incident management",                       description: "Documented job schedule with failure-detection + escalation; centralised monitoring + alerting with on-call rotation; incident-management workflow (detect / categorise / respond / RCA / preventive); incident ticket retention for the audit period; SLO + MTTR tracking.",                                                                                                                                                                                                                                                  category: "incident-response",    evidenceTypes: ["procedure","log","incident_record","report"],        clauseRefs: ["SOC 1 CO-CO"],               riskLevel: "high"    },
    { controlRef: "SOC1-CO-BR",      title: "Backup + restoration controls",                                          description: "Documented backup policy with frequency + retention by data classification; offsite / cross-region replication; annual restore-test with documented evidence; recovery-point-objective + recovery-time-objective alignment; encrypted backups + access controls on restore.",                                                                                                                                                                                                                                                    category: "data-protection",      evidenceTypes: ["policy","procedure","configuration","attestation","report"], clauseRefs: ["SOC 1 CO-CO"],          riskLevel: "high"    },
    { controlRef: "SOC1-SD-001",     title: "System development life cycle + environment segregation",                  description: "Defined SDLC with phase exit criteria; documented requirements + design + test artefacts; unit + integration + UAT testing with evidence; data-migration controls for any change touching financial data; explicit boundary + access controls between dev / test / staging / production.",                                                                                                                                                                                                                                              category: "secure-sdlc",          evidenceTypes: ["procedure","report","configuration","attestation"],  clauseRefs: ["SOC 1 CO-SD"],               riskLevel: "high"    },
    { controlRef: "SOC1-DT-001",     title: "Data transmission + interface integrity",                                description: "TLS-in-transit on all external interfaces; file-hash / control-total / sequence-number integrity checks on batch transmissions; transmission acknowledgement + reconciliation; documented error-queue + retransmission workflow; interface-specifications maintained as living documents.",                                                                                                                                                                                                                                category: "cryptography",         evidenceTypes: ["procedure","configuration","log","report"],          clauseRefs: ["SOC 1 CO-DT"],               riskLevel: "high"    },
    { controlRef: "SOC1-PS-001",     title: "Physical + environmental security (carve-out reliance)",                  description: "Where data centres are operated by a subservice organization, the SOC 1 / SOC 2 / ISO 27001 report of that subservice organization is obtained annually + reviewed for any qualified opinions or exceptions; documented reliance + CSOC mapping in the description. For any self-operated facility: badge / biometric / visitor logs + environmental controls + media-handling procedures.",                                                                                                                                       category: "physical-security",    evidenceTypes: ["report","attestation","procedure","contract"],       clauseRefs: ["SOC 1 CO-PS","AT-C 320.34"], riskLevel: "high"    },
    { controlRef: "SOC1-DPI-001",    title: "Data processing integrity + application controls",                        description: "Input validation (edit checks / range / mandatory) at every interface; processing-accuracy controls (calculation reviews / posting reconciliations / aggregation totals); output controls (exception reports / sequence numbers / totals); reconciliation cadence between subsidiary records + general ledger; documented manual key controls supporting automated flows.",                                                                                                                                                  category: "data-protection",      evidenceTypes: ["procedure","log","report","configuration","screenshot"], clauseRefs: ["SOC 1 CO-DPI"],          riskLevel: "high"    },
    { controlRef: "SOC1-SUB-001",    title: "Subservice + CUEC documentation + monitoring",                            description: "Annual register of subservice organizations + reliance method (carve-out / inclusive); CSOCs documented for each carve-out reliance; subservice-organization SOC report annual review + remediation tracking. CUECs documented in the system description + communicated to user entities through the contract / portal; periodic reminder + acknowledgement collection where practicable.",                                                                                                                                       category: "ai-system-governance", evidenceTypes: ["contract","report","procedure","attestation"],       clauseRefs: ["AT-C 320.34","AT-C 320.A48"],riskLevel: "high"    },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "SOC1-Q-001",  text: "Is the service organization in scope for SOC 1 — i.e., do its services provide a function that is likely to be relevant to user entities' Internal Control over Financial Reporting (ICFR)?",                                                                                                            category: "applicability",      riskWeight: 1.0, clauseRefs: ["AT-C 320.09"] },
    { questionRef: "SOC1-Q-002",  text: "Is there an annual management description of the system meeting all eight description criteria (DC 1-8) — services / commitments / components / boundaries / events / reporting / subservices / TSC-not-addressed?",                                                                                  category: "description",        riskWeight: 1.0, clauseRefs: ["AT-C 320.09"] },
    { questionRef: "SOC1-Q-003",  text: "Does management provide a written assertion covering fair presentation + suitable design + operating effectiveness of the controls?",                                                                                                                                                                    category: "assertion",          riskWeight: 1.0, clauseRefs: ["AT-C 320.30"] },
    { questionRef: "SOC1-Q-004",  text: "Has an annual risk assessment been performed mapping significant risks to control objectives to specific controls?",                                                                                                                                                                                       category: "risk-assessment",    riskWeight: 1.0, clauseRefs: ["AT-C 320.A23"] },
    { questionRef: "SOC1-Q-005",  text: "Are logical-access controls in place — provisioning approval + MFA + RBAC + privileged-access management + quarterly access review + termination deprovisioning?",                                                                                                                                          category: "logical-access",     riskWeight: 1.0, clauseRefs: ["SOC 1 CO-LA"] },
    { questionRef: "SOC1-Q-006",  text: "Is change management documented + enforced — classification + peer review + CAB approval + segregation between developer and production-deploy authority + deploy logs retained?",                                                                                                                        category: "change-management",  riskWeight: 1.0, clauseRefs: ["SOC 1 CO-CM"] },
    { questionRef: "SOC1-Q-007",  text: "Is there a defined emergency-change pathway with retrospective ratification + post-implementation review?",                                                                                                                                                                                                category: "change-management",  riskWeight: 0.7, clauseRefs: ["SOC 1 CO-CM"] },
    { questionRef: "SOC1-Q-008",  text: "Are computer-operations controls in place — job scheduling + monitoring + incident management with RCA + backup + annual restore-test?",                                                                                                                                                                  category: "operations",         riskWeight: 1.0, clauseRefs: ["SOC 1 CO-CO"] },
    { questionRef: "SOC1-Q-009",  text: "Is there an SDLC methodology + documented phase artefacts + UAT evidence + dev/test/staging/production segregation?",                                                                                                                                                                                       category: "sdlc",               riskWeight: 0.9, clauseRefs: ["SOC 1 CO-SD"] },
    { questionRef: "SOC1-Q-010",  text: "Are data-transmission controls in place — TLS-in-transit + integrity checks + acknowledgement + error-queue handling?",                                                                                                                                                                                     category: "data-transmission",  riskWeight: 0.9, clauseRefs: ["SOC 1 CO-DT"] },
    { questionRef: "SOC1-Q-011",  text: "For data-centre physical + environmental security, is the subservice-organization SOC report obtained annually + CSOC mapping documented (or are self-operated physical controls + environmental controls evidenced)?",                                                                                  category: "physical-security",  riskWeight: 0.8, clauseRefs: ["SOC 1 CO-PS","AT-C 320.34"] },
    { questionRef: "SOC1-Q-012",  text: "Are data-processing-integrity + application controls in place — input validation + processing accuracy + output controls + reconciliations + manual key controls?",                                                                                                                                          category: "data-processing",    riskWeight: 1.0, clauseRefs: ["SOC 1 CO-DPI"] },
    { questionRef: "SOC1-Q-013",  text: "Is the subservice-organization register maintained with reliance method (carve-out / inclusive) + CSOCs documented?",                                                                                                                                                                                       category: "subservice",         riskWeight: 0.9, clauseRefs: ["AT-C 320.34"] },
    { questionRef: "SOC1-Q-014",  text: "Are Complementary User Entity Controls (CUECs) identified in the description and communicated to user entities (via contract, customer portal, or periodic reminder)?",                                                                                                                                       category: "cuecs",              riskWeight: 0.8, clauseRefs: ["AT-C 320.A48"] },
    { questionRef: "SOC1-Q-015",  text: "Does the service auditor's report contain all AT-C 320.41 required elements — opinion on fair presentation + design + operating effectiveness + tests-of-controls description + restricted-use paragraph + auditor signature?",                                                                          category: "report",             riskWeight: 0.7, clauseRefs: ["AT-C 320.41"] },
    { questionRef: "SOC1-Q-016",  text: "Is the examination performed by a service auditor that meets SSAE 18 independence + competence requirements?",                                                                                                                                                                                              category: "auditor",            riskWeight: 0.7, clauseRefs: ["AT-C 320.09"] },
  ],
};
