import type { Framework } from "@regunav/types";

/**
 * UK GDPR + Data Protection Act 2018 (DPA 2018) — the UK's data-protection
 * regime after Brexit. The UK GDPR is the EU GDPR (Regulation (EU)
 * 2016/679) as it forms part of domestic law in the United Kingdom by
 * virtue of the European Union (Withdrawal) Act 2018, as modified by the
 * Data Protection, Privacy and Electronic Communications (Amendments
 * etc) (EU Exit) Regulations 2019. The DPA 2018 supplements the UK GDPR
 * with national derogations and provides the framework for the
 * Information Commissioner's Office (ICO).
 *
 * Sources:
 *   - https://www.legislation.gov.uk/ukpga/2018/12/contents (DPA 2018)
 *   - https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/ (ICO)
 *
 * Since most articles of the UK GDPR mirror the EU GDPR 1:1 (this
 * framework module references EU GDPR for the shared text — see
 * packages/frameworks/src/gdpr.ts), this module captures the UK-specific
 * deltas:
 *
 *   - Supervisory authority is the ICO (not EDPB / national EU DPAs)
 *   - DPA 2018 Schedules 1-3 provide UK derogations for special-category
 *     data, criminal-records data, scientific research, immigration etc.
 *   - ICO statutory codes of practice (Children's Code, Data-Sharing Code,
 *     Direct-Marketing Code) interpret the regulator's expectations
 *   - UK adequacy decisions are made by the UK government (e.g. via the
 *     UK-US Data Bridge for transfers to certified US recipients)
 *   - International-transfer mechanism: International Data Transfer
 *     Agreement (IDTA) + Addendum, or the UK addendum to the EU SCCs;
 *     Transfer Risk Assessment (TRA) is mandatory
 *   - Maximum administrative fine: £17,500,000 or 4% of total worldwide
 *     annual turnover, whichever is higher (Article 83 + DPA 2018 §157)
 *
 * Clauses, controls and questions below cite the published text + ICO
 * guidance. They are structural references, not legal advice. See
 * packages/ontology/LEGAL_DISCLAIMER.md.
 */
export const UK_GDPR: Framework = {
  schemaVersion: 1,
  code: "UK_GDPR",
  name: "UK GDPR + DPA 2018",
  version: "2018",
  description:
    "UK data-protection regime: UK GDPR (the EU GDPR retained in domestic law and amended for the UK context) plus the Data Protection Act 2018. Applies to controllers + processors established in the UK and, under Art. 3(2), to those outside the UK that offer goods/services to or monitor data subjects in the UK. Supervisory authority is the Information Commissioner's Office (ICO). This module focuses on the UK-specific deltas vs EU GDPR (which is populated separately at packages/frameworks/src/gdpr.ts).",
  jurisdiction: ["UK"],
  referenceUrl: "https://www.legislation.gov.uk/ukpga/2018/12/contents",

  // ─── Clauses (16 — UK-GDPR-specific articles + DPA 2018 + ICO codes) ──────
  clauses: [
    { clauseRef: "UK GDPR Art. 3",  title: "Territorial scope (UK)",                                          description: "UK GDPR applies to the processing of personal data in the context of the activities of an establishment of a controller or processor in the United Kingdom, regardless of where the processing takes place. It also applies to the processing of personal data of data subjects in the UK by a controller/processor not established in the UK where the processing relates to the offering of goods or services to data subjects in the UK or the monitoring of their behaviour as far as their behaviour takes place within the UK.", mandatory: true },
    { clauseRef: "UK GDPR Art. 27", title: "Representatives of controllers or processors not established in the UK", description: "Controllers or processors not established in the UK that are subject to Art. 3(2) shall designate in writing a representative in the UK, unless the exemptions in Art. 27(2) apply. The representative shall be mandated by the controller/processor to be addressed by the ICO and data subjects on all matters related to processing.", mandatory: true },
    { clauseRef: "UK GDPR Art. 33", title: "Breach notification to the ICO",                                  description: "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the Information Commissioner's Office, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. Submitted via the ICO's online breach-reporting portal.", mandatory: true },
    { clauseRef: "UK GDPR Art. 35", title: "Data protection impact assessment (DPIA)",                         description: "Where a type of processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to the processing, carry out a DPIA. The ICO has published a list of processing operations that always require a DPIA, including processing involving children, large-scale monitoring of a publicly accessible area, and innovative use of technology with novel applications.", mandatory: true },
    { clauseRef: "UK GDPR Art. 45", title: "Transfers on the basis of an adequacy decision (UK adequacy)",     description: "Transfers may take place where the UK Secretary of State has decided that the third country, a territory or one or more specified sectors within that third country, or the international organisation in question, ensures an adequate level of protection. Examples in force: UK-US Data Bridge (2023) for recipients certified under the EU-US Data Privacy Framework's UK extension; transitional UK adequacy regulations covering the EEA.", mandatory: true },
    { clauseRef: "UK GDPR Art. 46", title: "Transfers subject to appropriate safeguards (IDTA)",               description: "In the absence of an adequacy decision, transfers shall be subject to appropriate safeguards. The UK-specific safeguards are the International Data Transfer Agreement (IDTA) issued by the ICO and the UK Addendum to the EU Standard Contractual Clauses. A Transfer Risk Assessment (TRA) is required to evaluate the third-country regime and supplementary measures.", mandatory: true },
    { clauseRef: "UK GDPR Art. 83", title: "Administrative fines (UK)",                                        description: "Maximum administrative fine: £17,500,000 or, in the case of an undertaking, up to 4% of the total worldwide annual turnover of the preceding financial year, whichever is higher (the lower tier is £8,700,000 or 2%). DPA 2018 §157 confirms the conversion of EU GDPR euro amounts to GBP.", mandatory: true },
    { clauseRef: "DPA 2018 Pt 2 Sch 1", title: "Special-category and criminal-records derogations",            description: "Schedule 1 sets out the conditions for processing special-category personal data under Art. 9(2)(b)/(g)/(h)/(i)/(j) UK GDPR and for processing personal data relating to criminal convictions and offences (employment + social-security obligations; substantial public interest; health/social-care; research; etc.). Each condition has specific safeguards and an associated 'appropriate policy document' requirement.", mandatory: true },
    { clauseRef: "DPA 2018 Pt 3",   title: "Law-enforcement processing",                                       description: "Implements the EU Law Enforcement Directive (2016/680) as it forms part of UK domestic law. Applies to processing for the purposes of the prevention, investigation, detection or prosecution of criminal offences or the execution of criminal penalties. Sets out the law-enforcement-specific principles, data-subject rights and oversight by the ICO.", mandatory: false },
    { clauseRef: "DPA 2018 Pt 4",   title: "Intelligence services processing",                                 description: "Applies to the processing of personal data by the UK intelligence services (Security Service, Secret Intelligence Service, GCHQ). Aligned with the modernised Council of Europe Convention 108+.", mandatory: false },
    { clauseRef: "DPA 2018 §137-181",title: "ICO powers and functions",                                         description: "Establishes the Information Commissioner's Office, sets out its general functions, investigation and enforcement powers (information notices, assessment notices, enforcement notices, penalty notices), and complaint-handling procedures. The ICO is the UK's single national supervisory authority.", mandatory: true },
    { clauseRef: "ICO Children's Code", title: "Age-Appropriate Design Code (ICO statutory code)",              description: "Statutory code of practice issued under DPA 2018 §123 setting out how online services likely to be accessed by children should comply with the UK GDPR. 15 standards covering best-interests-of-the-child, DPIA, age-appropriate application, transparency, detrimental use of data, policies, default settings, data minimisation, data sharing, geolocation, parental controls, profiling, nudge techniques, connected toys + devices, online tools.", mandatory: false },
    { clauseRef: "ICO Data-Sharing Code", title: "Data-Sharing Code (ICO statutory code)",                      description: "Statutory code of practice under DPA 2018 §121 providing practical guidance on sharing personal data in compliance with the UK GDPR + DPA 2018. Covers the fairness + transparency principles, lawful bases, data-sharing agreements, DPIA, vulnerable individuals, children.", mandatory: false },
    { clauseRef: "ICO Direct-Marketing Code", title: "Direct-Marketing Code (ICO statutory code)",              description: "Statutory code of practice under DPA 2018 §125 on direct marketing under both UK GDPR and the Privacy and Electronic Communications Regulations 2003 (PECR). Covers consent, soft-opt-in, list-broker checks, profiling for marketing, marketing to children.", mandatory: false },
    { clauseRef: "PECR 2003",         title: "Privacy and Electronic Communications Regulations 2003",         description: "Implements the EU ePrivacy Directive (2002/58/EC) as part of UK law. Covers cookies + similar technologies, electronic-marketing (email, SMS, automated calls), traffic data, security of public communications services. Sits alongside the UK GDPR; the ICO enforces both.", mandatory: false },
    { clauseRef: "Records mgmt + accountability (UK GDPR Art. 5(2) + DPA 2018)", title: "Accountability evidence trail",                                description: "Both UK GDPR Art. 5(2) and DPA 2018 require controllers to demonstrate compliance. The ICO Accountability Framework groups required evidence into 10 categories (leadership + oversight; policies + procedures; training + awareness; ROPA; transparency; individual rights; lawful basis; contracts + DPAs; risk + DPIAs; breach + incident management).", mandatory: true },
  ],

  // ─── Controls (10 — UK-specific deltas over the shared GDPR controls) ─────
  controls: [
    { controlRef: "UK-GDPR-ART27-001",    title: "UK representative (Art. 27)",                                  description: "Where the controller/processor is not established in the UK but is subject to Art. 3(2), designate a UK-based representative in writing with a mandate to be addressed by data subjects and the ICO. Document the representative's contact details in the privacy notice.",                                                                                                                                                  category: "data-protection", evidenceTypes: ["contract","procedure","report","attestation"],         clauseRefs: ["UK GDPR Art. 27"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-BREACH-001",   title: "ICO breach notification + 72-hour workflow",                  description: "Breach-notification workflow that submits to the ICO via the online portal within 72 hours of becoming aware (or with justified delay); template body covering the Art. 33 mandatory content; ICO reference-number capture for the audit trail.",                                                                                                                                                                          category: "incident-response", evidenceTypes: ["procedure","incident_record","report","attestation"],  clauseRefs: ["UK GDPR Art. 33"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-DPIA-001",     title: "DPIA aligned with ICO list",                                    description: "DPIA process aligned with the ICO's published 'list of processing operations that require a DPIA' (incl. processing of children's data, large-scale public monitoring, innovative tech). DPO consultation logged; consultation with the ICO under Art. 36 where residual high risk.",                                                                                                                                       category: "data-protection", evidenceTypes: ["dpia","report","procedure","attestation"],              clauseRefs: ["UK GDPR Art. 35"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-XBORDER-001",  title: "International transfers — adequacy + IDTA + TRA",              description: "For transfers outside the UK: rely on a UK adequacy regulation (e.g. UK-US Data Bridge, transitional UK adequacy regs for EEA), or use the IDTA / UK Addendum to EU SCCs; in either case complete a Transfer Risk Assessment evaluating the third-country regime + supplementary measures.",                                                                                                                                    category: "data-protection", evidenceTypes: ["contract","report","attestation","configuration"],     clauseRefs: ["UK GDPR Art. 45","UK GDPR Art. 46"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-SPECIAL-001",  title: "DPA 2018 Schedule 1 conditions + appropriate policy document", description: "For each Schedule 1 condition relied upon to process special-category or criminal-records data, an 'appropriate policy document' (APD) is in place describing how the relevant principles are complied with, the retention + erasure policy, and oversight arrangements.",                                                                                                                                                category: "data-protection", evidenceTypes: ["policy","report","attestation"],                       clauseRefs: ["DPA 2018 Pt 2 Sch 1"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-CHILDREN-001", title: "Children's Code (Age-Appropriate Design Code) conformance",   description: "For online services likely to be accessed by children: 15-standards conformance against the ICO Children's Code, age-assurance approach, DPIA tailored to children, default privacy-protective settings, transparency in age-appropriate language.",                                                                                                                                                                        category: "data-protection", evidenceTypes: ["screenshot","report","procedure","attestation"],       clauseRefs: ["ICO Children's Code"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-PECR-001",     title: "PECR conformance — cookies + electronic marketing",            description: "Cookie banner + consent management aligned with PECR Reg. 6; soft-opt-in for direct marketing where applicable (PECR Reg. 22); preference centre + suppression list; auditable consent records.",                                                                                                                                                                                                                              category: "data-protection", evidenceTypes: ["screenshot","configuration","procedure","report"],    clauseRefs: ["PECR 2003"], riskLevel: "high"   },
    { controlRef: "UK-GDPR-MARKETING-001",title: "Direct-Marketing Code conformance",                            description: "Direct-marketing operations comply with the ICO Direct-Marketing Code: consent capture for B2C marketing, soft-opt-in evidence, list-broker due diligence, opt-out fulfilment within reasonable time, marketing-to-children restrictions.",                                                                                                                                                                                  category: "data-protection", evidenceTypes: ["procedure","log","screenshot","report"],                clauseRefs: ["ICO Direct-Marketing Code"], riskLevel: "limited" },
    { controlRef: "UK-GDPR-FINES-001",    title: "Penalty-exposure awareness (£17.5m / 4% tier)",                description: "ICO penalty exposure (£17.5m or 4% global annual turnover; £8.7m or 2% for lower-tier infringements) reflected in the risk register + reported to the executive risk committee.",                                                                                                                                                                                                                                        category: "ai-system-governance", evidenceTypes: ["report","attestation","policy"],                       clauseRefs: ["UK GDPR Art. 83"], riskLevel: "limited" },
    { controlRef: "UK-GDPR-ACCFW-001",    title: "ICO Accountability Framework evidence trail",                  description: "Evidence inventoried against the ICO Accountability Framework's ten categories (leadership + oversight; policies + procedures; training + awareness; ROPA; transparency; individual rights; lawful basis; contracts + DPAs; risk + DPIAs; breach + incident management).",                                                                                                                                                  category: "data-protection", evidenceTypes: ["report","attestation","procedure","training_record"],   clauseRefs: ["Records mgmt + accountability (UK GDPR Art. 5(2) + DPA 2018)"], riskLevel: "high"   },
  ],

  // ─── Self-assessment questions (used at framework activation) ────────────
  questions: [
    { questionRef: "UK-GDPR-Q-001",  text: "Does processing fall within the UK GDPR's territorial scope (UK establishment, offering of goods/services to UK data subjects, or monitoring of their behaviour in the UK)?",                                  category: "applicability",     riskWeight: 1.0, clauseRefs: ["UK GDPR Art. 3"] },
    { questionRef: "UK-GDPR-Q-002",  text: "Where the controller/processor is not established in the UK and subject to Art. 3(2), is a UK-based representative designated (Art. 27)?",                                                                    category: "representative",    riskWeight: 0.9, clauseRefs: ["UK GDPR Art. 27"] },
    { questionRef: "UK-GDPR-Q-003",  text: "Can a personal data breach be notified to the ICO within 72 hours of awareness via the ICO online portal (Art. 33)?",                                                                                          category: "breach",            riskWeight: 1.0, clauseRefs: ["UK GDPR Art. 33"] },
    { questionRef: "UK-GDPR-Q-004",  text: "Is a DPIA performed for all processing on the ICO's published 'list of operations that require a DPIA' (Art. 35)?",                                                                                            category: "dpia",              riskWeight: 0.9, clauseRefs: ["UK GDPR Art. 35"] },
    { questionRef: "UK-GDPR-Q-005",  text: "For transfers outside the UK, do you rely on a UK adequacy regulation (e.g. UK-US Data Bridge) or on the IDTA / UK Addendum + a documented Transfer Risk Assessment (Art. 45-46)?",                            category: "transfers",         riskWeight: 1.0, clauseRefs: ["UK GDPR Art. 45","UK GDPR Art. 46"] },
    { questionRef: "UK-GDPR-Q-006",  text: "For special-category or criminal-records data processed under DPA 2018 Schedule 1, is the matching 'appropriate policy document' (APD) in place?",                                                              category: "special-category",  riskWeight: 1.0, clauseRefs: ["DPA 2018 Pt 2 Sch 1"] },
    { questionRef: "UK-GDPR-Q-007",  text: "Where the service is likely to be accessed by children, is the ICO Children's Code (15 standards) implemented?",                                                                                                category: "children",          riskWeight: 0.9, clauseRefs: ["ICO Children's Code"] },
    { questionRef: "UK-GDPR-Q-008",  text: "Is the Data-Sharing Code applied to any data-sharing arrangement with other controllers?",                                                                                                                      category: "data-sharing",      riskWeight: 0.7, clauseRefs: ["ICO Data-Sharing Code"] },
    { questionRef: "UK-GDPR-Q-009",  text: "Are cookies + electronic-marketing operations compliant with PECR (cookie consent, soft-opt-in, suppression list)?",                                                                                            category: "pecr",              riskWeight: 0.8, clauseRefs: ["PECR 2003"] },
    { questionRef: "UK-GDPR-Q-010",  text: "Are direct-marketing operations aligned with the ICO Direct-Marketing Code (consent capture, list-broker DD, opt-out fulfilment)?",                                                                              category: "marketing",         riskWeight: 0.7, clauseRefs: ["ICO Direct-Marketing Code"] },
    { questionRef: "UK-GDPR-Q-011",  text: "Is the maximum UK penalty exposure (£17.5m or 4% global annual turnover; £8.7m or 2% lower-tier) reflected in the risk register?",                                                                              category: "fines",             riskWeight: 0.5, clauseRefs: ["UK GDPR Art. 83"] },
    { questionRef: "UK-GDPR-Q-012",  text: "Is evidence aligned with the ICO Accountability Framework's 10 categories so demonstrable compliance can be produced on demand?",                                                                                category: "accountability",    riskWeight: 0.8, clauseRefs: ["Records mgmt + accountability (UK GDPR Art. 5(2) + DPA 2018)"] },
    { questionRef: "UK-GDPR-Q-013",  text: "Have the underlying EU-GDPR-mirroring controls been implemented per packages/frameworks/src/gdpr.ts (Article 5 principles, lawful basis, six rights, DPIA, by-design, security, breach, DPO etc.)?",            category: "eu-gdpr-mirror",    riskWeight: 1.0, clauseRefs: ["UK GDPR Art. 3"] },
  ],
};
